// Generated by CS2Dumper — 2026-07-17T15:19:48Z
// Curated client.dll schema fields for Internal use (not the full dump).
#pragma once
#include <cstddef>

namespace cs2_dumper::cheat_fields {

    // C_BaseEntity
    namespace C_BaseEntity {
        constexpr std::ptrdiff_t m_CBodyComponent = 0x30; // CBodyComponent*
        constexpr std::ptrdiff_t m_NetworkTransmitComponent = 0x38; // CNetworkTransmitComponent
        constexpr std::ptrdiff_t m_nLastThinkTick = 0x328; // GameTick_t
        constexpr std::ptrdiff_t m_pGameSceneNode = 0x330; // CGameSceneNode*
        constexpr std::ptrdiff_t m_pRenderComponent = 0x338; // CRenderComponent*
        constexpr std::ptrdiff_t m_pCollision = 0x340; // CCollisionProperty*
        constexpr std::ptrdiff_t m_iMaxHealth = 0x348; // int32
        constexpr std::ptrdiff_t m_iHealth = 0x34C; // int32
        constexpr std::ptrdiff_t m_flDamageAccumulator = 0x350; // float32
        constexpr std::ptrdiff_t m_lifeState = 0x354; // uint8
        constexpr std::ptrdiff_t m_bTakesDamage = 0x355; // bool
        constexpr std::ptrdiff_t m_nTakeDamageFlags = 0x358; // TakeDamageFlags_t
        constexpr std::ptrdiff_t m_nPlatformType = 0x360; // EntityPlatformTypes_t
        constexpr std::ptrdiff_t m_ubInterpolationFrame = 0x361; // uint8
        constexpr std::ptrdiff_t m_hSceneObjectController = 0x364; // CHandle<C_BaseEntity>
        constexpr std::ptrdiff_t m_nNoInterpolationTick = 0x368; // int32
        constexpr std::ptrdiff_t m_nVisibilityNoInterpolationTick = 0x36C; // int32
        constexpr std::ptrdiff_t m_flProxyRandomValue = 0x370; // float32
        constexpr std::ptrdiff_t m_iEFlags = 0x374; // int32
        constexpr std::ptrdiff_t m_nWaterType = 0x378; // uint8
        constexpr std::ptrdiff_t m_bInterpolateEvenWithNoModel = 0x379; // bool
        constexpr std::ptrdiff_t m_bPredictionEligible = 0x37A; // bool
        constexpr std::ptrdiff_t m_bApplyLayerMatchIDToModel = 0x37B; // bool
        constexpr std::ptrdiff_t m_tokLayerMatchID = 0x37C; // CUtlStringToken
        constexpr std::ptrdiff_t m_nSubclassID = 0x380; // CUtlStringToken
        constexpr std::ptrdiff_t m_nSimulationTick = 0x390; // int32
        constexpr std::ptrdiff_t m_iCurrentThinkContext = 0x394; // int32
        constexpr std::ptrdiff_t m_aThinkFunctions = 0x398; // CUtlVector<thinkfunc_t>
        constexpr std::ptrdiff_t m_bDisabledContextThinks = 0x3B0; // bool
        constexpr std::ptrdiff_t m_flAnimTime = 0x3B4; // float32
        constexpr std::ptrdiff_t m_flSimulationTime = 0x3B8; // float32
        constexpr std::ptrdiff_t m_nSceneObjectOverrideFlags = 0x3BC; // uint8
        constexpr std::ptrdiff_t m_bHasSuccessfullyInterpolated = 0x3BD; // bool
        constexpr std::ptrdiff_t m_bHasAddedVarsToInterpolation = 0x3BE; // bool
        constexpr std::ptrdiff_t m_bRenderEvenWhenNotSuccessfullyInterpolated = 0x3BF; // bool
        constexpr std::ptrdiff_t m_nInterpolationLatchDirtyFlags = 0x3C0; // int32[2]
        constexpr std::ptrdiff_t m_ListEntry = 0x3C8; // uint16[11]
        constexpr std::ptrdiff_t m_flCreateTime = 0x3E0; // GameTime_t
        constexpr std::ptrdiff_t m_EntClientFlags = 0x3E4; // uint16
        constexpr std::ptrdiff_t m_bClientSideRagdoll = 0x3E6; // bool
        constexpr std::ptrdiff_t m_iTeamNum = 0x3E7; // uint8
        constexpr std::ptrdiff_t m_spawnflags = 0x3E8; // uint32
        constexpr std::ptrdiff_t m_nNextThinkTick = 0x3EC; // GameTick_t
        constexpr std::ptrdiff_t m_fFlags = 0x3F4; // uint32
        constexpr std::ptrdiff_t m_vecAbsVelocity = 0x3F8; // Vector
        constexpr std::ptrdiff_t m_vecServerVelocity = 0x404; // CNetworkVelocityVector
        constexpr std::ptrdiff_t m_vecVelocity = 0x430; // CNetworkVelocityVector
        constexpr std::ptrdiff_t m_vecBaseVelocity = 0x510; // Vector
        constexpr std::ptrdiff_t m_hEffectEntity = 0x51C; // CHandle<C_BaseEntity>
        constexpr std::ptrdiff_t m_hOwnerEntity = 0x520; // CHandle<C_BaseEntity>
        constexpr std::ptrdiff_t m_MoveCollide = 0x524; // MoveCollide_t
        constexpr std::ptrdiff_t m_MoveType = 0x525; // MoveType_t
        constexpr std::ptrdiff_t m_nActualMoveType = 0x526; // MoveType_t
        constexpr std::ptrdiff_t m_flWaterLevel = 0x528; // float32
        constexpr std::ptrdiff_t m_fEffects = 0x52C; // uint32
        constexpr std::ptrdiff_t m_hGroundEntity = 0x530; // CHandle<C_BaseEntity>
        constexpr std::ptrdiff_t m_nGroundBodyIndex = 0x534; // int32
        constexpr std::ptrdiff_t m_flFriction = 0x538; // float32
        constexpr std::ptrdiff_t m_flElasticity = 0x53C; // float32
        constexpr std::ptrdiff_t m_flGravityScale = 0x540; // float32
        constexpr std::ptrdiff_t m_flTimeScale = 0x544; // float32
        constexpr std::ptrdiff_t m_bAnimatedEveryTick = 0x548; // bool
        constexpr std::ptrdiff_t m_bGravityDisabled = 0x549; // bool
        constexpr std::ptrdiff_t m_flNavIgnoreUntilTime = 0x54C; // GameTime_t
        constexpr std::ptrdiff_t m_hThink = 0x550; // uint16
        constexpr std::ptrdiff_t m_fBBoxVisFlags = 0x560; // uint8
        constexpr std::ptrdiff_t m_flActualGravityScale = 0x564; // float32
        constexpr std::ptrdiff_t m_bGravityActuallyDisabled = 0x568; // bool
        constexpr std::ptrdiff_t m_bPredictable = 0x569; // bool
        constexpr std::ptrdiff_t m_bRenderWithViewModels = 0x56A; // bool
        constexpr std::ptrdiff_t m_nFirstPredictableCommand = 0x56C; // int32
        constexpr std::ptrdiff_t m_nLastPredictableCommand = 0x570; // int32
        constexpr std::ptrdiff_t m_hOldMoveParent = 0x574; // CHandle<C_BaseEntity>
        constexpr std::ptrdiff_t m_Particles = 0x578; // CParticleProperty
        constexpr std::ptrdiff_t m_vecAngVelocity = 0x5A8; // QAngle
        constexpr std::ptrdiff_t m_DataChangeEventRef = 0x5B4; // int32
        constexpr std::ptrdiff_t m_dependencies = 0x5B8; // CUtlVector<CEntityHandle>
        constexpr std::ptrdiff_t m_nCreationTick = 0x5D0; // int32
        constexpr std::ptrdiff_t m_bAnimTimeChanged = 0x5E1; // bool
        constexpr std::ptrdiff_t m_bSimulationTimeChanged = 0x5E2; // bool
        constexpr std::ptrdiff_t m_sUniqueHammerID = 0x5F0; // CUtlString
        constexpr std::ptrdiff_t m_nBloodType = 0x5F8; // BloodType
    }

    // C_BasePlayerPawn : CBaseAnimGraph
    namespace C_BasePlayerPawn {
        constexpr std::ptrdiff_t m_pWeaponServices = 0x1208; // CPlayer_WeaponServices*
        constexpr std::ptrdiff_t m_pItemServices = 0x1210; // CPlayer_ItemServices*
        constexpr std::ptrdiff_t m_pAutoaimServices = 0x1218; // CPlayer_AutoaimServices*
        constexpr std::ptrdiff_t m_pObserverServices = 0x1220; // CPlayer_ObserverServices*
        constexpr std::ptrdiff_t m_pWaterServices = 0x1228; // CPlayer_WaterServices*
        constexpr std::ptrdiff_t m_pUseServices = 0x1230; // CPlayer_UseServices*
        constexpr std::ptrdiff_t m_pFlashlightServices = 0x1238; // CPlayer_FlashlightServices*
        constexpr std::ptrdiff_t m_pCameraServices = 0x1240; // CPlayer_CameraServices*
        constexpr std::ptrdiff_t m_pMovementServices = 0x1248; // CPlayer_MovementServices*
        constexpr std::ptrdiff_t m_ServerViewAngleChanges = 0x1258; // C_UtlVectorEmbeddedNetworkVar<ViewAngleServerChange_t>
        constexpr std::ptrdiff_t v_angle = 0x12C0; // QAngle
        constexpr std::ptrdiff_t v_anglePrevious = 0x12CC; // QAngle
        constexpr std::ptrdiff_t m_iHideHUD = 0x12D8; // uint32
        constexpr std::ptrdiff_t m_skybox3d = 0x12E0; // sky3dparams_t
        constexpr std::ptrdiff_t m_flDeathTime = 0x1370; // GameTime_t
        constexpr std::ptrdiff_t m_vecPredictionError = 0x1374; // Vector
        constexpr std::ptrdiff_t m_flPredictionErrorTime = 0x1380; // GameTime_t
        constexpr std::ptrdiff_t m_vecLastCameraSetupLocalOrigin = 0x13A0; // Vector
        constexpr std::ptrdiff_t m_flLastCameraSetupTime = 0x13AC; // GameTime_t
        constexpr std::ptrdiff_t m_flFOVSensitivityAdjust = 0x13B0; // float32
        constexpr std::ptrdiff_t m_flMouseSensitivity = 0x13B4; // float32
        constexpr std::ptrdiff_t m_vOldOrigin = 0x13B8; // Vector
        constexpr std::ptrdiff_t m_flOldSimulationTime = 0x13C4; // float32
        constexpr std::ptrdiff_t m_nLastExecutedCommandNumber = 0x13C8; // int32
        constexpr std::ptrdiff_t m_nLastExecutedCommandTick = 0x13CC; // int32
        constexpr std::ptrdiff_t m_hController = 0x13D0; // CHandle<CBasePlayerController>
        constexpr std::ptrdiff_t m_hDefaultController = 0x13D4; // CHandle<CBasePlayerController>
        constexpr std::ptrdiff_t m_bIsSwappingToPredictableController = 0x13D8; // bool
    }

    // C_CSPlayerPawn : C_CSPlayerPawnBase
    namespace C_CSPlayerPawn {
        constexpr std::ptrdiff_t m_pBulletServices = 0x1490; // CCSPlayer_BulletServices*
        constexpr std::ptrdiff_t m_pHostageServices = 0x1498; // CCSPlayer_HostageServices*
        constexpr std::ptrdiff_t m_pBuyServices = 0x14A0; // CCSPlayer_BuyServices*
        constexpr std::ptrdiff_t m_pGlowServices = 0x14A8; // CCSPlayer_GlowServices*
        constexpr std::ptrdiff_t m_pActionTrackingServices = 0x14B0; // CCSPlayer_ActionTrackingServices*
        constexpr std::ptrdiff_t m_pAimPunchServices = 0x14B8; // CCSPlayer_AimPunchServices*
        constexpr std::ptrdiff_t m_pDamageReactServices = 0x14C0; // CCSPlayer_DamageReactServices*
        constexpr std::ptrdiff_t m_flHealthShotBoostExpirationTime = 0x14C8; // GameTime_t
        constexpr std::ptrdiff_t m_flLastFiredWeaponTime = 0x14CC; // GameTime_t
        constexpr std::ptrdiff_t m_bHasFemaleVoice = 0x14D0; // bool
        constexpr std::ptrdiff_t m_flLandingTimeSeconds = 0x14D4; // float32
        constexpr std::ptrdiff_t m_flOldFallVelocity = 0x14D8; // float32
        constexpr std::ptrdiff_t m_szLastPlaceName = 0x14DC; // char[18]
        constexpr std::ptrdiff_t m_bPrevDefuser = 0x14EE; // bool
        constexpr std::ptrdiff_t m_bPrevHelmet = 0x14EF; // bool
        constexpr std::ptrdiff_t m_nPrevArmorVal = 0x14F0; // int32
        constexpr std::ptrdiff_t m_nPrevGrenadeAmmoCount = 0x14F4; // int32
        constexpr std::ptrdiff_t m_unPreviousWeaponHash = 0x14F8; // uint32
        constexpr std::ptrdiff_t m_unWeaponHash = 0x14FC; // uint32
        constexpr std::ptrdiff_t m_bInBuyZone = 0x1500; // bool
        constexpr std::ptrdiff_t m_bPreviouslyInBuyZone = 0x1501; // bool
        constexpr std::ptrdiff_t m_bInLanding = 0x1502; // bool
        constexpr std::ptrdiff_t m_flLandingStartTime = 0x1504; // float32
        constexpr std::ptrdiff_t m_bInHostageRescueZone = 0x1508; // bool
        constexpr std::ptrdiff_t m_bInBombZone = 0x1509; // bool
        constexpr std::ptrdiff_t m_bIsBuyMenuOpen = 0x150A; // bool
        constexpr std::ptrdiff_t m_flTimeOfLastInjury = 0x150C; // GameTime_t
        constexpr std::ptrdiff_t m_flNextSprayDecalTime = 0x1510; // GameTime_t
        constexpr std::ptrdiff_t m_iRetakesOffering = 0x1670; // int32
        constexpr std::ptrdiff_t m_iRetakesOfferingCard = 0x1674; // int32
        constexpr std::ptrdiff_t m_bRetakesHasDefuseKit = 0x1678; // bool
        constexpr std::ptrdiff_t m_bRetakesMVPLastRound = 0x1679; // bool
        constexpr std::ptrdiff_t m_iRetakesMVPBoostItem = 0x167C; // int32
        constexpr std::ptrdiff_t m_RetakesMVPBoostExtraUtility = 0x1680; // loadout_slot_t
        constexpr std::ptrdiff_t m_bNeedToReApplyGloves = 0x1685; // bool
        constexpr std::ptrdiff_t m_EconGloves = 0x1688; // C_EconItemView
        constexpr std::ptrdiff_t m_nEconGlovesChanged = 0x1AF8; // uint8
        constexpr std::ptrdiff_t m_bMustSyncRagdollState = 0x1AF9; // bool
        constexpr std::ptrdiff_t m_nRagdollDamageBone = 0x1AFC; // int32
        constexpr std::ptrdiff_t m_vRagdollDamageForce = 0x1B00; // Vector
        constexpr std::ptrdiff_t m_szRagdollDamageWeaponName = 0x1B0C; // char[64]
        constexpr std::ptrdiff_t m_bRagdollDamageHeadshot = 0x1B4C; // bool
        constexpr std::ptrdiff_t m_vRagdollServerOrigin = 0x1B50; // VectorWS
        constexpr std::ptrdiff_t m_lastLandTime = 0x1B5C; // GameTime_t
        constexpr std::ptrdiff_t m_bOnGroundLastTick = 0x1B60; // bool
        constexpr std::ptrdiff_t m_hHudModelArms = 0x1B7C; // CHandle<C_CS2HudModelArms>
        constexpr std::ptrdiff_t m_qDeathEyeAngles = 0x1B80; // QAngle
        constexpr std::ptrdiff_t m_bLeftHanded = 0x1B8C; // bool
        constexpr std::ptrdiff_t m_fSwitchedHandednessTime = 0x1B90; // GameTime_t
        constexpr std::ptrdiff_t m_flViewmodelOffsetX = 0x1B94; // float32
        constexpr std::ptrdiff_t m_flViewmodelOffsetY = 0x1B98; // float32
        constexpr std::ptrdiff_t m_flViewmodelOffsetZ = 0x1B9C; // float32
        constexpr std::ptrdiff_t m_flViewmodelFOV = 0x1BA0; // float32
        constexpr std::ptrdiff_t m_vecPlayerPatchEconIndices = 0x1BA4; // uint32[5]
        constexpr std::ptrdiff_t m_GunGameImmunityColor = 0x1BE8; // Color
        constexpr std::ptrdiff_t m_vecBulletHitModels = 0x1C38; // CUtlVector<C_BulletHitModel*>
        constexpr std::ptrdiff_t m_bIsWalking = 0x1C50; // bool
        constexpr std::ptrdiff_t m_entitySpottedState = 0x1C58; // EntitySpottedState_t
        constexpr std::ptrdiff_t m_bIsScoped = 0x1C70; // bool
        constexpr std::ptrdiff_t m_bResumeZoom = 0x1C71; // bool
        constexpr std::ptrdiff_t m_bIsDefusing = 0x1C72; // bool
        constexpr std::ptrdiff_t m_bIsGrabbingHostage = 0x1C73; // bool
        constexpr std::ptrdiff_t m_iBlockingUseActionInProgress = 0x1C74; // CSPlayerBlockingUseAction_t
        constexpr std::ptrdiff_t m_flEmitSoundTime = 0x1C78; // GameTime_t
        constexpr std::ptrdiff_t m_bInNoDefuseArea = 0x1C7C; // bool
        constexpr std::ptrdiff_t m_nWhichBombZone = 0x1C80; // int32
        constexpr std::ptrdiff_t m_iShotsFired = 0x1C84; // int32
        constexpr std::ptrdiff_t m_flFlinchStack = 0x1C88; // float32
        constexpr std::ptrdiff_t m_flVelocityModifier = 0x1C8C; // float32
        constexpr std::ptrdiff_t m_bWaitForNoAttack = 0x1C90; // bool
        constexpr std::ptrdiff_t m_ignoreLadderJumpTime = 0x1C94; // float32
        constexpr std::ptrdiff_t m_bKilledByHeadshot = 0x1C99; // bool
        constexpr std::ptrdiff_t m_ArmorValue = 0x1C9C; // int32
        constexpr std::ptrdiff_t m_unCurrentEquipmentValue = 0x1CA0; // uint16
        constexpr std::ptrdiff_t m_unRoundStartEquipmentValue = 0x1CA2; // uint16
        constexpr std::ptrdiff_t m_unFreezetimeEndEquipmentValue = 0x1CA4; // uint16
        constexpr std::ptrdiff_t m_nLastKillerIndex = 0x1CA8; // CEntityIndex
        constexpr std::ptrdiff_t m_bOldIsScoped = 0x1CAC; // bool
        constexpr std::ptrdiff_t m_bHasDeathInfo = 0x1CAD; // bool
        constexpr std::ptrdiff_t m_flDeathInfoTime = 0x1CB0; // float32
        constexpr std::ptrdiff_t m_vecDeathInfoOrigin = 0x1CB4; // VectorWS
        constexpr std::ptrdiff_t m_grenadeParameterStashTime = 0x1CF0; // GameTime_t
        constexpr std::ptrdiff_t m_bGrenadeParametersStashed = 0x1CF4; // bool
        constexpr std::ptrdiff_t m_angStashedShootAngles = 0x1CF8; // QAngle
        constexpr std::ptrdiff_t m_vecStashedGrenadeThrowPosition = 0x1D04; // VectorWS
        constexpr std::ptrdiff_t m_vecStashedVelocity = 0x1D10; // Vector
        constexpr std::ptrdiff_t m_bShouldAutobuyDMWeapons = 0x3250; // bool
        constexpr std::ptrdiff_t m_fImmuneToGunGameDamageTime = 0x3254; // GameTime_t
        constexpr std::ptrdiff_t m_bGunGameImmunity = 0x3258; // bool
        constexpr std::ptrdiff_t m_fImmuneToGunGameDamageTimeLast = 0x325C; // GameTime_t
        constexpr std::ptrdiff_t m_fMolotovDamageTime = 0x3260; // float32
        constexpr std::ptrdiff_t m_nPlayerInfernoBodyFx = 0x32CC; // ParticleIndex_t
        constexpr std::ptrdiff_t m_angEyeAngles = 0x3340; // QAngle
        constexpr std::ptrdiff_t m_arrOldEyeAnglesTimes = 0x33D0; // GameTime_t[4]
        constexpr std::ptrdiff_t m_arrOldEyeAngles = 0x33E0; // QAngle[4]
        constexpr std::ptrdiff_t m_angEyeAnglesVelocity = 0x3410; // QAngle
        constexpr std::ptrdiff_t m_iIDEntIndex = 0x341C; // CEntityIndex
        constexpr std::ptrdiff_t m_delayTargetIDTimer = 0x3420; // CountdownTimer
        constexpr std::ptrdiff_t m_iTargetItemEntIdx = 0x3438; // CEntityIndex
        constexpr std::ptrdiff_t m_iOldIDEntIndex = 0x343C; // CEntityIndex
        constexpr std::ptrdiff_t m_holdTargetIDTimer = 0x3440; // CountdownTimer
    }

    // C_CSPlayerPawnBase : C_BasePlayerPawn
    namespace C_CSPlayerPawnBase {
        constexpr std::ptrdiff_t m_pPingServices = 0x13F0; // CCSPlayer_PingServices*
        constexpr std::ptrdiff_t m_previousPlayerState = 0x13F8; // CSPlayerState
        constexpr std::ptrdiff_t m_iPlayerState = 0x13FC; // CSPlayerState
        constexpr std::ptrdiff_t m_bHasMovedSinceSpawn = 0x1400; // bool
        constexpr std::ptrdiff_t m_flLastSpawnTimeIndex = 0x1404; // GameTime_t
        constexpr std::ptrdiff_t m_iProgressBarDuration = 0x1408; // int32
        constexpr std::ptrdiff_t m_flProgressBarStartTime = 0x140C; // float32
        constexpr std::ptrdiff_t m_flClientDeathTime = 0x1410; // GameTime_t
        constexpr std::ptrdiff_t m_flFlashBangTime = 0x1414; // float32
        constexpr std::ptrdiff_t m_flFlashScreenshotAlpha = 0x1418; // float32
        constexpr std::ptrdiff_t m_flFlashOverlayAlpha = 0x141C; // float32
        constexpr std::ptrdiff_t m_bFlashBuildUp = 0x1420; // bool
        constexpr std::ptrdiff_t m_bFlashDspHasBeenCleared = 0x1421; // bool
        constexpr std::ptrdiff_t m_bFlashScreenshotHasBeenGrabbed = 0x1422; // bool
        constexpr std::ptrdiff_t m_flFlashMaxAlpha = 0x1424; // float32
        constexpr std::ptrdiff_t m_flFlashDuration = 0x1428; // float32
        constexpr std::ptrdiff_t m_flClientHealthFadeChangeTimestamp = 0x142C; // GameTime_t
        constexpr std::ptrdiff_t m_nClientHealthFadeParityValue = 0x1430; // int32
        constexpr std::ptrdiff_t m_fNextThinkPushAway = 0x1434; // float32
        constexpr std::ptrdiff_t m_flCurrentMusicStartTime = 0x143C; // float32
        constexpr std::ptrdiff_t m_flMusicRoundStartTime = 0x1440; // float32
        constexpr std::ptrdiff_t m_bDeferStartMusicOnWarmup = 0x1444; // bool
        constexpr std::ptrdiff_t m_flLastSmokeOverlayAlpha = 0x1448; // float32
        constexpr std::ptrdiff_t m_flLastSmokeAge = 0x144C; // float32
        constexpr std::ptrdiff_t m_vLastSmokeOverlayColor = 0x1450; // Vector
        constexpr std::ptrdiff_t m_hOriginalController = 0x1478; // CHandle<CCSPlayerController>
    }

    // CCSPlayerController : CBasePlayerController
    namespace CCSPlayerController {
        constexpr std::ptrdiff_t m_pInGameMoneyServices = 0x810; // CCSPlayerController_InGameMoneyServices*
        constexpr std::ptrdiff_t m_pInventoryServices = 0x818; // CCSPlayerController_InventoryServices*
        constexpr std::ptrdiff_t m_pActionTrackingServices = 0x820; // CCSPlayerController_ActionTrackingServices*
        constexpr std::ptrdiff_t m_pDamageServices = 0x828; // CCSPlayerController_DamageServices*
        constexpr std::ptrdiff_t m_iPing = 0x830; // uint32
        constexpr std::ptrdiff_t m_bHasCommunicationAbuseMute = 0x834; // bool
        constexpr std::ptrdiff_t m_uiCommunicationMuteFlags = 0x838; // uint32
        constexpr std::ptrdiff_t m_szCrosshairCodes = 0x840; // CUtlSymbolLarge
        constexpr std::ptrdiff_t m_iPendingTeamNum = 0x848; // uint8
        constexpr std::ptrdiff_t m_flForceTeamTime = 0x84C; // GameTime_t
        constexpr std::ptrdiff_t m_iCompTeammateColor = 0x850; // int32
        constexpr std::ptrdiff_t m_bEverPlayedOnTeam = 0x854; // bool
        constexpr std::ptrdiff_t m_flPreviousForceJoinTeamTime = 0x858; // GameTime_t
        constexpr std::ptrdiff_t m_szClan = 0x860; // CUtlSymbolLarge
        constexpr std::ptrdiff_t m_sSanitizedPlayerName = 0x868; // CUtlString
        constexpr std::ptrdiff_t m_iCoachingTeam = 0x870; // int32
        constexpr std::ptrdiff_t m_nPlayerDominated = 0x878; // uint64
        constexpr std::ptrdiff_t m_nPlayerDominatingMe = 0x880; // uint64
        constexpr std::ptrdiff_t m_iCompetitiveRanking = 0x888; // int32
        constexpr std::ptrdiff_t m_iCompetitiveWins = 0x88C; // int32
        constexpr std::ptrdiff_t m_iCompetitiveRankType = 0x890; // int8
        constexpr std::ptrdiff_t m_iCompetitiveRankingPredicted_Win = 0x894; // int32
        constexpr std::ptrdiff_t m_iCompetitiveRankingPredicted_Loss = 0x898; // int32
        constexpr std::ptrdiff_t m_iCompetitiveRankingPredicted_Tie = 0x89C; // int32
        constexpr std::ptrdiff_t m_nEndMatchNextMapVote = 0x8A0; // int32
        constexpr std::ptrdiff_t m_unActiveQuestId = 0x8A4; // uint16
        constexpr std::ptrdiff_t m_rtActiveMissionPeriod = 0x8A8; // uint32
        constexpr std::ptrdiff_t m_nQuestProgressReason = 0x8AC; // QuestProgress::Reason
        constexpr std::ptrdiff_t m_unPlayerTvControlFlags = 0x8B0; // uint32
        constexpr std::ptrdiff_t m_iDraftIndex = 0x8E0; // int32
        constexpr std::ptrdiff_t m_msQueuedModeDisconnectionTimestamp = 0x8E4; // uint32
        constexpr std::ptrdiff_t m_uiAbandonRecordedReason = 0x8E8; // uint32
        constexpr std::ptrdiff_t m_eNetworkDisconnectionReason = 0x8EC; // uint32
        constexpr std::ptrdiff_t m_bCannotBeKicked = 0x8F0; // bool
        constexpr std::ptrdiff_t m_bEverFullyConnected = 0x8F1; // bool
        constexpr std::ptrdiff_t m_bAbandonAllowsSurrender = 0x8F2; // bool
        constexpr std::ptrdiff_t m_bAbandonOffersInstantSurrender = 0x8F3; // bool
        constexpr std::ptrdiff_t m_bDisconnection1MinWarningPrinted = 0x8F4; // bool
        constexpr std::ptrdiff_t m_bScoreReported = 0x8F5; // bool
        constexpr std::ptrdiff_t m_nDisconnectionTick = 0x8F8; // int32
        constexpr std::ptrdiff_t m_bControllingBot = 0x908; // bool
        constexpr std::ptrdiff_t m_bHasControlledBotThisRound = 0x909; // bool
        constexpr std::ptrdiff_t m_bHasBeenControlledByPlayerThisRound = 0x90A; // bool
        constexpr std::ptrdiff_t m_nBotsControlledThisRound = 0x90C; // int32
        constexpr std::ptrdiff_t m_bCanControlObservedBot = 0x910; // bool
        constexpr std::ptrdiff_t m_hPlayerPawn = 0x914; // CHandle<C_CSPlayerPawn>
        constexpr std::ptrdiff_t m_hObserverPawn = 0x918; // CHandle<C_CSObserverPawn>
        constexpr std::ptrdiff_t m_bPawnIsAlive = 0x91C; // bool
        constexpr std::ptrdiff_t m_iPawnHealth = 0x920; // uint32
        constexpr std::ptrdiff_t m_iPawnArmor = 0x924; // int32
        constexpr std::ptrdiff_t m_bPawnHasDefuser = 0x928; // bool
        constexpr std::ptrdiff_t m_bPawnHasHelmet = 0x929; // bool
        constexpr std::ptrdiff_t m_nPawnCharacterDefIndex = 0x92A; // uint16
        constexpr std::ptrdiff_t m_iPawnLifetimeStart = 0x92C; // int32
        constexpr std::ptrdiff_t m_iPawnLifetimeEnd = 0x930; // int32
        constexpr std::ptrdiff_t m_iPawnBotDifficulty = 0x934; // int32
        constexpr std::ptrdiff_t m_hOriginalControllerOfCurrentPawn = 0x938; // CHandle<CCSPlayerController>
        constexpr std::ptrdiff_t m_iScore = 0x93C; // int32
        constexpr std::ptrdiff_t m_recentKillQueue = 0x940; // uint8[8]
        constexpr std::ptrdiff_t m_nFirstKill = 0x948; // uint8
        constexpr std::ptrdiff_t m_nKillCount = 0x949; // uint8
        constexpr std::ptrdiff_t m_bMvpNoMusic = 0x94A; // bool
        constexpr std::ptrdiff_t m_eMvpReason = 0x94C; // int32
        constexpr std::ptrdiff_t m_iMusicKitID = 0x950; // int32
        constexpr std::ptrdiff_t m_iMusicKitMVPs = 0x954; // int32
        constexpr std::ptrdiff_t m_iMVPs = 0x958; // int32
        constexpr std::ptrdiff_t m_bIsPlayerNameDirty = 0x95C; // bool
        constexpr std::ptrdiff_t m_bFireBulletsSeedSynchronized = 0x95D; // bool
    }

    // CBasePlayerController : C_BaseEntity
    namespace CBasePlayerController {
        constexpr std::ptrdiff_t m_CommandContext = 0x608; // C_CommandContext
        constexpr std::ptrdiff_t m_nInButtonsWhichAreToggles = 0x6B0; // uint64
        constexpr std::ptrdiff_t m_nTickBase = 0x6B8; // uint32
        constexpr std::ptrdiff_t m_hPawn = 0x6BC; // CHandle<C_BasePlayerPawn>
        constexpr std::ptrdiff_t m_bKnownTeamMismatch = 0x6C0; // bool
        constexpr std::ptrdiff_t m_hPredictedPawn = 0x6C4; // CHandle<C_BasePlayerPawn>
        constexpr std::ptrdiff_t m_nSplitScreenSlot = 0x6C8; // CSplitScreenSlot
        constexpr std::ptrdiff_t m_hSplitOwner = 0x6CC; // CHandle<CBasePlayerController>
        constexpr std::ptrdiff_t m_hSplitScreenPlayers = 0x6D0; // CUtlVector<CHandle<CBasePlayerController>>
        constexpr std::ptrdiff_t m_bIsHLTV = 0x6E8; // bool
        constexpr std::ptrdiff_t m_iConnected = 0x6EC; // PlayerConnectedState
        constexpr std::ptrdiff_t m_iMostConnected = 0x6F0; // PlayerConnectedState
        constexpr std::ptrdiff_t m_iszPlayerName = 0x6F4; // char[128]
        constexpr std::ptrdiff_t m_steamID = 0x780; // uint64
        constexpr std::ptrdiff_t m_bIsLocalPlayerController = 0x788; // bool
        constexpr std::ptrdiff_t m_bNoClipEnabled = 0x789; // bool
        constexpr std::ptrdiff_t m_iDesiredFOV = 0x78C; // uint32
    }

    // CGameSceneNode
    namespace CGameSceneNode {
        constexpr std::ptrdiff_t m_bDirtyHierarchy = 0x0; // bitfield:1
        constexpr std::ptrdiff_t m_bDirtyBoneMergeInfo = 0x0; // bitfield:1
        constexpr std::ptrdiff_t m_bNetworkedPositionChanged = 0x0; // bitfield:1
        constexpr std::ptrdiff_t m_bNetworkedAnglesChanged = 0x0; // bitfield:1
        constexpr std::ptrdiff_t m_bNetworkedScaleChanged = 0x0; // bitfield:1
        constexpr std::ptrdiff_t m_bWillBeCallingPostDataUpdate = 0x0; // bitfield:1
        constexpr std::ptrdiff_t m_bBoneMergeFlex = 0x0; // bitfield:1
        constexpr std::ptrdiff_t m_nLatchAbsOrigin = 0x0; // bitfield:2
        constexpr std::ptrdiff_t m_bDirtyBoneMergeBoneToRoot = 0x0; // bitfield:1
        constexpr std::ptrdiff_t m_nodeToWorld = 0x10; // CTransformWS
        constexpr std::ptrdiff_t m_pOwner = 0x30; // CEntityInstance*
        constexpr std::ptrdiff_t m_pParent = 0x38; // CGameSceneNode*
        constexpr std::ptrdiff_t m_pChild = 0x40; // CGameSceneNode*
        constexpr std::ptrdiff_t m_pNextSibling = 0x48; // CGameSceneNode*
        constexpr std::ptrdiff_t m_hParent = 0x70; // CGameSceneNodeHandle
        constexpr std::ptrdiff_t m_vecOrigin = 0x80; // CNetworkOriginCellCoordQuantizedVector
        constexpr std::ptrdiff_t m_angRotation = 0xB8; // QAngle
        constexpr std::ptrdiff_t m_flScale = 0xC4; // float32
        constexpr std::ptrdiff_t m_vecAbsOrigin = 0xC8; // VectorWS
        constexpr std::ptrdiff_t m_angAbsRotation = 0xD4; // QAngle
        constexpr std::ptrdiff_t m_flAbsScale = 0xE0; // float32
        constexpr std::ptrdiff_t m_vecWrappedLocalOrigin = 0xE4; // Vector
        constexpr std::ptrdiff_t m_angWrappedLocalRotation = 0xF0; // QAngle
        constexpr std::ptrdiff_t m_flWrappedScale = 0xFC; // float32
        constexpr std::ptrdiff_t m_nParentAttachmentOrBone = 0x100; // int16
        constexpr std::ptrdiff_t m_bDebugAbsOriginChanges = 0x102; // bool
        constexpr std::ptrdiff_t m_bDormant = 0x103; // bool
        constexpr std::ptrdiff_t m_bForceParentToBeNetworked = 0x104; // bool
        constexpr std::ptrdiff_t m_nHierarchicalDepth = 0x107; // uint8
        constexpr std::ptrdiff_t m_nHierarchyType = 0x108; // uint8
        constexpr std::ptrdiff_t m_nDoNotSetAnimTimeInInvalidatePhysicsCount = 0x109; // uint8
        constexpr std::ptrdiff_t m_name = 0x10C; // CUtlStringToken
        constexpr std::ptrdiff_t m_hierarchyAttachName = 0x120; // CUtlStringToken
        constexpr std::ptrdiff_t m_flClientLocalScale = 0x124; // float32
    }

    // CGlowProperty
    namespace CGlowProperty {
        constexpr std::ptrdiff_t m_fGlowColor = 0x8; // Vector
        constexpr std::ptrdiff_t m_iGlowType = 0x30; // int32
        constexpr std::ptrdiff_t m_iGlowTeam = 0x34; // int32
        constexpr std::ptrdiff_t m_nGlowRange = 0x38; // int32
        constexpr std::ptrdiff_t m_nGlowRangeMin = 0x3C; // int32
        constexpr std::ptrdiff_t m_glowColorOverride = 0x40; // Color
        constexpr std::ptrdiff_t m_bFlashing = 0x44; // bool
        constexpr std::ptrdiff_t m_flGlowTime = 0x48; // float32
        constexpr std::ptrdiff_t m_flGlowStartTime = 0x4C; // float32
        constexpr std::ptrdiff_t m_bEligibleForScreenHighlight = 0x50; // bool
        constexpr std::ptrdiff_t m_bGlowing = 0x51; // bool
    }

    // CCollisionProperty
    namespace CCollisionProperty {
        constexpr std::ptrdiff_t m_collisionAttribute = 0x10; // VPhysicsCollisionAttribute_t
        constexpr std::ptrdiff_t m_vecMins = 0x40; // Vector
        constexpr std::ptrdiff_t m_vecMaxs = 0x4C; // Vector
        constexpr std::ptrdiff_t m_usSolidFlags = 0x5A; // uint8
        constexpr std::ptrdiff_t m_nSolidType = 0x5B; // SolidType_t
        constexpr std::ptrdiff_t m_triggerBloat = 0x5C; // uint8
        constexpr std::ptrdiff_t m_nSurroundType = 0x5D; // SurroundingBoundsType_t
        constexpr std::ptrdiff_t m_CollisionGroup = 0x5E; // uint8
        constexpr std::ptrdiff_t m_nEnablePhysics = 0x5F; // uint8
        constexpr std::ptrdiff_t m_flBoundingRadius = 0x60; // float32
        constexpr std::ptrdiff_t m_vecSpecifiedSurroundingMins = 0x64; // Vector
        constexpr std::ptrdiff_t m_vecSpecifiedSurroundingMaxs = 0x70; // Vector
        constexpr std::ptrdiff_t m_vecSurroundingMaxs = 0x7C; // Vector
        constexpr std::ptrdiff_t m_vecSurroundingMins = 0x88; // Vector
        constexpr std::ptrdiff_t m_vCapsuleCenter1 = 0x94; // Vector
        constexpr std::ptrdiff_t m_vCapsuleCenter2 = 0xA0; // Vector
        constexpr std::ptrdiff_t m_flCapsuleRadius = 0xAC; // float32
    }

    // CHitboxComponent : CEntityComponent
    namespace CHitboxComponent {
        constexpr std::ptrdiff_t m_flBoundsExpandRadius = 0x14; // float32
    }

    // EntitySpottedState_t
    namespace EntitySpottedState_t {
        constexpr std::ptrdiff_t m_bSpotted = 0x8; // bool
        constexpr std::ptrdiff_t m_bSpottedByMask = 0xC; // uint32[2]
    }

    // C_SmokeGrenadeProjectile : C_BaseCSGrenadeProjectile
    namespace C_SmokeGrenadeProjectile {
        constexpr std::ptrdiff_t m_nSmokeEffectTickBegin = 0x1278; // int32
        constexpr std::ptrdiff_t m_bDidSmokeEffect = 0x127C; // bool
        constexpr std::ptrdiff_t m_nRandomSeed = 0x1280; // int32
        constexpr std::ptrdiff_t m_vSmokeColor = 0x1284; // Vector
        constexpr std::ptrdiff_t m_vSmokeDetonationPos = 0x1290; // VectorWS
        constexpr std::ptrdiff_t m_VoxelFrameData = 0x12A0; // C_NetworkUtlVectorBase<uint8>
        constexpr std::ptrdiff_t m_nVoxelFrameDataSize = 0x12B8; // int32
        constexpr std::ptrdiff_t m_nVoxelUpdate = 0x12BC; // int32
        constexpr std::ptrdiff_t m_bSmokeVolumeDataReceived = 0x12C0; // bool
        constexpr std::ptrdiff_t m_bSmokeEffectSpawned = 0x12C1; // bool
    }

    // C_Inferno : C_BaseModelEntity
    namespace C_Inferno {
        constexpr std::ptrdiff_t m_nfxFireDamageEffect = 0xFF0; // ParticleIndex_t
        constexpr std::ptrdiff_t m_hInfernoPointsSnapshot = 0xFF8; // CStrongHandle<InfoForResourceTypeIParticleSnapshot>
        constexpr std::ptrdiff_t m_hInfernoFillerPointsSnapshot = 0x1000; // CStrongHandle<InfoForResourceTypeIParticleSnapshot>
        constexpr std::ptrdiff_t m_hInfernoOutlinePointsSnapshot = 0x1008; // CStrongHandle<InfoForResourceTypeIParticleSnapshot>
        constexpr std::ptrdiff_t m_hInfernoClimbingOutlinePointsSnapshot = 0x1010; // CStrongHandle<InfoForResourceTypeIParticleSnapshot>
        constexpr std::ptrdiff_t m_hInfernoDecalsSnapshot = 0x1018; // CStrongHandle<InfoForResourceTypeIParticleSnapshot>
        constexpr std::ptrdiff_t m_firePositions = 0x1020; // VectorWS[64]
        constexpr std::ptrdiff_t m_fireParentPositions = 0x1320; // VectorWS[64]
        constexpr std::ptrdiff_t m_bFireIsBurning = 0x1620; // bool[64]
        constexpr std::ptrdiff_t m_BurnNormal = 0x1660; // Vector[64]
        constexpr std::ptrdiff_t m_fireCount = 0x1960; // int32
        constexpr std::ptrdiff_t m_nInfernoType = 0x1964; // int32
        constexpr std::ptrdiff_t m_nFireLifetime = 0x1968; // float32
        constexpr std::ptrdiff_t m_bInPostEffectTime = 0x196C; // bool
        constexpr std::ptrdiff_t m_lastFireCount = 0x1970; // int32
        constexpr std::ptrdiff_t m_nFireEffectTickBegin = 0x1974; // int32
        constexpr std::ptrdiff_t m_drawableCount = 0x8580; // int32
        constexpr std::ptrdiff_t m_blosCheck = 0x8584; // bool
        constexpr std::ptrdiff_t m_nlosperiod = 0x8588; // int32
        constexpr std::ptrdiff_t m_maxFireHalfWidth = 0x858C; // float32
        constexpr std::ptrdiff_t m_maxFireHeight = 0x8590; // float32
        constexpr std::ptrdiff_t m_minBounds = 0x8594; // VectorWS
        constexpr std::ptrdiff_t m_maxBounds = 0x85A0; // VectorWS
        constexpr std::ptrdiff_t m_flLastGrassBurnThink = 0x85AC; // float32
    }

    // C_BaseCSGrenadeProjectile : C_BaseGrenade
    namespace C_BaseCSGrenadeProjectile {
        constexpr std::ptrdiff_t m_vInitialPosition = 0x11C8; // VectorWS
        constexpr std::ptrdiff_t m_vInitialVelocity = 0x11D4; // Vector
        constexpr std::ptrdiff_t m_nBounces = 0x11E0; // int32
        constexpr std::ptrdiff_t m_nExplodeEffectIndex = 0x11E8; // CStrongHandle<InfoForResourceTypeIParticleSystemDefinition>
        constexpr std::ptrdiff_t m_nExplodeEffectTickBegin = 0x11F0; // int32
        constexpr std::ptrdiff_t m_vecExplodeEffectOrigin = 0x11F4; // VectorWS
        constexpr std::ptrdiff_t m_flSpawnTime = 0x1200; // GameTime_t
        constexpr std::ptrdiff_t vecLastTrailLinePos = 0x1204; // Vector
        constexpr std::ptrdiff_t flNextTrailLineTime = 0x1210; // GameTime_t
        constexpr std::ptrdiff_t m_bExplodeEffectBegan = 0x1214; // bool
        constexpr std::ptrdiff_t m_bCanCreateGrenadeTrail = 0x1215; // bool
        constexpr std::ptrdiff_t m_nSnapshotTrajectoryEffectIndex = 0x1218; // ParticleIndex_t
        constexpr std::ptrdiff_t m_hSnapshotTrajectoryParticleSnapshot = 0x1220; // CStrongHandle<InfoForResourceTypeIParticleSnapshot>
        constexpr std::ptrdiff_t m_arrTrajectoryTrailPoints = 0x1228; // CUtlVector<Vector>
        constexpr std::ptrdiff_t m_arrTrajectoryTrailPointCreationTimes = 0x1240; // CUtlVector<float32>
        constexpr std::ptrdiff_t m_flTrajectoryTrailEffectCreationTime = 0x1258; // float32
    }

    // C_PlantedC4 : CBaseAnimGraph
    namespace C_PlantedC4 {
        constexpr std::ptrdiff_t m_bBombTicking = 0x11A0; // bool
        constexpr std::ptrdiff_t m_nBombSite = 0x11A4; // int32
        constexpr std::ptrdiff_t m_nSourceSoundscapeHash = 0x11A8; // int32
        constexpr std::ptrdiff_t m_entitySpottedState = 0x11B0; // EntitySpottedState_t
        constexpr std::ptrdiff_t m_flNextGlow = 0x11C8; // GameTime_t
        constexpr std::ptrdiff_t m_flNextBeep = 0x11CC; // GameTime_t
        constexpr std::ptrdiff_t m_flC4Blow = 0x11D0; // GameTime_t
        constexpr std::ptrdiff_t m_bCannotBeDefused = 0x11D4; // bool
        constexpr std::ptrdiff_t m_bHasExploded = 0x11D5; // bool
        constexpr std::ptrdiff_t m_flTimerLength = 0x11D8; // float32
        constexpr std::ptrdiff_t m_bBeingDefused = 0x11DC; // bool
        constexpr std::ptrdiff_t m_bTriggerWarning = 0x11E0; // float32
        constexpr std::ptrdiff_t m_bExplodeWarning = 0x11E4; // float32
        constexpr std::ptrdiff_t m_bC4Activated = 0x11E8; // bool
        constexpr std::ptrdiff_t m_bTenSecWarning = 0x11E9; // bool
        constexpr std::ptrdiff_t m_flDefuseLength = 0x11EC; // float32
        constexpr std::ptrdiff_t m_flDefuseCountDown = 0x11F0; // GameTime_t
        constexpr std::ptrdiff_t m_bBombDefused = 0x11F4; // bool
        constexpr std::ptrdiff_t m_hBombDefuser = 0x11F8; // CHandle<C_CSPlayerPawn>
        constexpr std::ptrdiff_t m_AttributeManager = 0x1200; // C_AttributeContainer
        constexpr std::ptrdiff_t m_hDefuserMultimeter = 0x16D0; // CHandle<C_Multimeter>
        constexpr std::ptrdiff_t m_flNextRadarFlashTime = 0x16D4; // GameTime_t
        constexpr std::ptrdiff_t m_bRadarFlash = 0x16D8; // bool
        constexpr std::ptrdiff_t m_pBombDefuser = 0x16DC; // CHandle<C_CSPlayerPawn>
        constexpr std::ptrdiff_t m_fLastDefuseTime = 0x16E0; // GameTime_t
        constexpr std::ptrdiff_t m_pPredictionOwner = 0x16E8; // CBasePlayerController*
        constexpr std::ptrdiff_t m_vecC4ExplodeSpectatePos = 0x16F0; // VectorWS
        constexpr std::ptrdiff_t m_vecC4ExplodeSpectateAng = 0x16FC; // QAngle
        constexpr std::ptrdiff_t m_flC4ExplodeSpectateDuration = 0x1708; // float32
    }

    // C_CSWeaponBase : C_BasePlayerWeapon
    namespace C_CSWeaponBase {
        constexpr std::ptrdiff_t m_iWeaponGameplayAnimState = 0x1778; // WeaponGameplayAnimState
        constexpr std::ptrdiff_t m_flWeaponGameplayAnimStateTimestamp = 0x177C; // GameTime_t
        constexpr std::ptrdiff_t m_flInspectCancelCompleteTime = 0x1780; // GameTime_t
        constexpr std::ptrdiff_t m_bInspectPending = 0x1784; // bool
        constexpr std::ptrdiff_t m_bInspectShouldLoop = 0x1785; // bool
        constexpr std::ptrdiff_t m_flCrosshairDistance = 0x17B0; // float32
        constexpr std::ptrdiff_t m_iAmmoLastCheck = 0x17B4; // int32
        constexpr std::ptrdiff_t m_nLastEmptySoundCmdNum = 0x17B8; // int32
        constexpr std::ptrdiff_t m_bFireOnEmpty = 0x17BC; // bool
        constexpr std::ptrdiff_t m_OnPlayerPickup = 0x17C0; // CEntityIOOutput
        constexpr std::ptrdiff_t m_weaponMode = 0x17D8; // CSWeaponMode
        constexpr std::ptrdiff_t m_flTurningInaccuracyDelta = 0x17DC; // float32
        constexpr std::ptrdiff_t m_vecTurningInaccuracyEyeDirLast = 0x17E0; // Vector
        constexpr std::ptrdiff_t m_flTurningInaccuracy = 0x17EC; // float32
        constexpr std::ptrdiff_t m_fAccuracyPenalty = 0x17F0; // float32
        constexpr std::ptrdiff_t m_flLastAccuracyUpdateTime = 0x17F4; // GameTime_t
        constexpr std::ptrdiff_t m_fAccuracySmoothedForZoom = 0x17F8; // float32
        constexpr std::ptrdiff_t m_iRecoilIndex = 0x17FC; // int32
        constexpr std::ptrdiff_t m_flRecoilIndex = 0x1800; // float32
        constexpr std::ptrdiff_t m_bBurstMode = 0x1804; // bool
        constexpr std::ptrdiff_t m_flLastBurstModeChangeTime = 0x1808; // GameTime_t
        constexpr std::ptrdiff_t m_nPostponeFireReadyTicks = 0x180C; // GameTick_t
        constexpr std::ptrdiff_t m_flPostponeFireReadyFrac = 0x1810; // float32
        constexpr std::ptrdiff_t m_bInReload = 0x1814; // bool
        constexpr std::ptrdiff_t m_nDeployTick = 0x1818; // GameTick_t
        constexpr std::ptrdiff_t m_flDroppedAtTime = 0x181C; // GameTime_t
        constexpr std::ptrdiff_t m_bIsHauledBack = 0x1824; // bool
        constexpr std::ptrdiff_t m_bSilencerOn = 0x1825; // bool
        constexpr std::ptrdiff_t m_flTimeSilencerSwitchComplete = 0x1828; // GameTime_t
        constexpr std::ptrdiff_t m_flWeaponActionPlaybackRate = 0x182C; // float32
        constexpr std::ptrdiff_t m_iOriginalTeamNumber = 0x1830; // int32
        constexpr std::ptrdiff_t m_iMostRecentTeamNumber = 0x1834; // int32
        constexpr std::ptrdiff_t m_bDroppedNearBuyZone = 0x1838; // bool
        constexpr std::ptrdiff_t m_flNextAttackRenderTimeOffset = 0x183C; // float32
        constexpr std::ptrdiff_t m_bClearWeaponIdentifyingUGC = 0x18E0; // bool
        constexpr std::ptrdiff_t m_bVisualsDataSet = 0x18E1; // bool
        constexpr std::ptrdiff_t m_bUIWeapon = 0x18E2; // bool
        constexpr std::ptrdiff_t m_nCustomEconReloadEventId = 0x18E4; // int32
        constexpr std::ptrdiff_t m_bCanBePickedUp = 0x18F0; // bool
        constexpr std::ptrdiff_t m_nextPrevOwnerUseTime = 0x18F4; // GameTime_t
        constexpr std::ptrdiff_t m_hPrevOwner = 0x18F8; // CHandle<C_CSPlayerPawn>
        constexpr std::ptrdiff_t m_nDropTick = 0x18FC; // GameTick_t
        constexpr std::ptrdiff_t m_bWasActiveWeaponWhenDropped = 0x1900; // bool
        constexpr std::ptrdiff_t m_donated = 0x1924; // bool
        constexpr std::ptrdiff_t m_fLastShotTime = 0x1928; // GameTime_t
        constexpr std::ptrdiff_t m_bWasOwnedByCT = 0x192C; // bool
        constexpr std::ptrdiff_t m_bWasOwnedByTerrorist = 0x192D; // bool
        constexpr std::ptrdiff_t m_flNextClientFireBulletTime = 0x1930; // float32
        constexpr std::ptrdiff_t m_flNextClientFireBulletTime_Repredict = 0x1934; // float32
        constexpr std::ptrdiff_t m_IronSightController = 0x1990; // C_IronSightController
        constexpr std::ptrdiff_t m_iIronSightMode = 0x1A40; // int32
        constexpr std::ptrdiff_t m_flLastLOSTraceFailureTime = 0x1AB8; // GameTime_t
        constexpr std::ptrdiff_t m_flWatTickOffset = 0x1B18; // float32
        constexpr std::ptrdiff_t m_flLastShakeTime = 0x1B2C; // GameTime_t
    }

    // C_BasePlayerWeapon : C_EconEntity
    namespace C_BasePlayerWeapon {
        constexpr std::ptrdiff_t m_nNextPrimaryAttackTick = 0x16F0; // GameTick_t
        constexpr std::ptrdiff_t m_flNextPrimaryAttackTickRatio = 0x16F4; // float32
        constexpr std::ptrdiff_t m_nNextSecondaryAttackTick = 0x16F8; // GameTick_t
        constexpr std::ptrdiff_t m_flNextSecondaryAttackTickRatio = 0x16FC; // float32
        constexpr std::ptrdiff_t m_iClip1 = 0x1700; // int32
        constexpr std::ptrdiff_t m_iClip2 = 0x1704; // int32
        constexpr std::ptrdiff_t m_pReserveAmmo = 0x1708; // int32[2]
    }

    // C_EconEntity : CBaseAnimGraph
    namespace C_EconEntity {
        constexpr std::ptrdiff_t m_flFlexDelayTime = 0x1190; // float32
        constexpr std::ptrdiff_t m_flFlexDelayedWeight = 0x1198; // float32*
        constexpr std::ptrdiff_t m_bAttributesInitialized = 0x11A0; // bool
        constexpr std::ptrdiff_t m_AttributeManager = 0x11A8; // C_AttributeContainer
        constexpr std::ptrdiff_t m_OriginalOwnerXuidLow = 0x1678; // uint32
        constexpr std::ptrdiff_t m_OriginalOwnerXuidHigh = 0x167C; // uint32
        constexpr std::ptrdiff_t m_nFallbackPaintKit = 0x1680; // int32
        constexpr std::ptrdiff_t m_nFallbackSeed = 0x1684; // int32
        constexpr std::ptrdiff_t m_flFallbackWear = 0x1688; // float32
        constexpr std::ptrdiff_t m_nFallbackStatTrak = 0x168C; // int32
        constexpr std::ptrdiff_t m_bClientside = 0x1690; // bool
        constexpr std::ptrdiff_t m_bParticleSystemsCreated = 0x1691; // bool
        constexpr std::ptrdiff_t m_vecAttachedParticles = 0x1698; // CUtlVector<int32>
        constexpr std::ptrdiff_t m_hViewmodelAttachment = 0x16B0; // CHandle<CBaseAnimGraph>
        constexpr std::ptrdiff_t m_iOldTeam = 0x16B4; // int32
        constexpr std::ptrdiff_t m_bAttachmentDirty = 0x16B8; // bool
        constexpr std::ptrdiff_t m_nUnloadedModelIndex = 0x16BC; // int32
        constexpr std::ptrdiff_t m_iNumOwnerValidationRetries = 0x16C0; // int32
        constexpr std::ptrdiff_t m_hOldProvidee = 0x16D0; // CHandle<C_BaseEntity>
        constexpr std::ptrdiff_t m_vecAttachedModels = 0x16D8; // CUtlVector<C_EconEntity::AttachedModelData_t>
    }

    // C_EconWearable : C_EconEntity
    namespace C_EconWearable {
        constexpr std::ptrdiff_t m_nForceSkin = 0x16F0; // int32
        constexpr std::ptrdiff_t m_bAlwaysAllow = 0x16F4; // bool
    }

    // C_AttributeContainer : CAttributeManager
    namespace C_AttributeContainer {
        constexpr std::ptrdiff_t m_Item = 0x50; // C_EconItemView
        constexpr std::ptrdiff_t m_iExternalItemProviderRegisteredToken = 0x4C0; // int32
        constexpr std::ptrdiff_t m_ullRegisteredAsItemID = 0x4C8; // uint64
    }

    // C_EconItemView
    namespace C_EconItemView {
        constexpr std::ptrdiff_t m_bInventoryImageRgbaRequested = 0x60; // bool
        constexpr std::ptrdiff_t m_bInventoryImageTriedCache = 0x61; // bool
        constexpr std::ptrdiff_t m_nInventoryImageRgbaWidth = 0x80; // int32
        constexpr std::ptrdiff_t m_nInventoryImageRgbaHeight = 0x84; // int32
        constexpr std::ptrdiff_t m_szCurrentLoadCachedFileName = 0x88; // char[260]
        constexpr std::ptrdiff_t m_bRestoreCustomMaterialAfterPrecache = 0x1B8; // bool
        constexpr std::ptrdiff_t m_iItemDefinitionIndex = 0x1BA; // uint16
        constexpr std::ptrdiff_t m_iEntityQuality = 0x1BC; // int32
        constexpr std::ptrdiff_t m_iEntityLevel = 0x1C0; // uint32
        constexpr std::ptrdiff_t m_iItemID = 0x1C8; // uint64
        constexpr std::ptrdiff_t m_iItemIDHigh = 0x1D0; // uint32
        constexpr std::ptrdiff_t m_iItemIDLow = 0x1D4; // uint32
        constexpr std::ptrdiff_t m_iAccountID = 0x1D8; // uint32
        constexpr std::ptrdiff_t m_iInventoryPosition = 0x1DC; // uint32
        constexpr std::ptrdiff_t m_bInitialized = 0x1E8; // bool
        constexpr std::ptrdiff_t m_bDisallowSOC = 0x1E9; // bool
        constexpr std::ptrdiff_t m_bIsStoreItem = 0x1EA; // bool
        constexpr std::ptrdiff_t m_bIsTradeItem = 0x1EB; // bool
        constexpr std::ptrdiff_t m_iEntityQuantity = 0x1EC; // int32
        constexpr std::ptrdiff_t m_iRarityOverride = 0x1F0; // int32
        constexpr std::ptrdiff_t m_iQualityOverride = 0x1F4; // int32
        constexpr std::ptrdiff_t m_iOriginOverride = 0x1F8; // int32
        constexpr std::ptrdiff_t m_ubStyleOverride = 0x1FC; // uint8
        constexpr std::ptrdiff_t m_unClientFlags = 0x1FD; // uint8
        constexpr std::ptrdiff_t m_AttributeList = 0x208; // CAttributeList
        constexpr std::ptrdiff_t m_NetworkedDynamicAttributes = 0x280; // CAttributeList
        constexpr std::ptrdiff_t m_szCustomName = 0x2F8; // char[161]
        constexpr std::ptrdiff_t m_szCustomNameOverride = 0x399; // char[161]
        constexpr std::ptrdiff_t m_bInitializedTags = 0x468; // bool
    }

    // CCSWeaponBaseVData
    namespace CCSWeaponBaseVData {
        constexpr std::ptrdiff_t m_WeaponType = 0x520; // CSWeaponType
        constexpr std::ptrdiff_t m_WeaponCategory = 0x524; // CSWeaponCategory
        constexpr std::ptrdiff_t m_szAnimSkeleton = 0x528; // CResourceNameTyped<CWeakHandle<InfoForResourceTypeCNmSkeleton>>
        constexpr std::ptrdiff_t m_vecMuzzlePos0 = 0x608; // Vector
        constexpr std::ptrdiff_t m_vecMuzzlePos1 = 0x614; // Vector
        constexpr std::ptrdiff_t m_szTracerParticle = 0x620; // CResourceNameTyped<CWeakHandle<InfoForResourceTypeIParticleSystemDefinition>>
        constexpr std::ptrdiff_t m_GearSlot = 0x700; // gear_slot_t
        constexpr std::ptrdiff_t m_GearSlotPosition = 0x704; // int32
        constexpr std::ptrdiff_t m_DefaultLoadoutSlot = 0x708; // loadout_slot_t
        constexpr std::ptrdiff_t m_nPrice = 0x70C; // int32
        constexpr std::ptrdiff_t m_nKillAward = 0x710; // int32
        constexpr std::ptrdiff_t m_nPrimaryReserveAmmoMax = 0x714; // int32
        constexpr std::ptrdiff_t m_nSecondaryReserveAmmoMax = 0x718; // int32
        constexpr std::ptrdiff_t m_bMeleeWeapon = 0x71C; // bool
        constexpr std::ptrdiff_t m_bHasBurstMode = 0x71D; // bool
        constexpr std::ptrdiff_t m_bIsRevolver = 0x71E; // bool
        constexpr std::ptrdiff_t m_bCannotShootUnderwater = 0x71F; // bool
        constexpr std::ptrdiff_t m_szName = 0x720; // CGlobalSymbol
        constexpr std::ptrdiff_t m_eSilencerType = 0x728; // CSWeaponSilencerType
        constexpr std::ptrdiff_t m_nCrosshairMinDistance = 0x72C; // int32
        constexpr std::ptrdiff_t m_nCrosshairDeltaDistance = 0x730; // int32
        constexpr std::ptrdiff_t m_bIsFullAuto = 0x734; // bool
        constexpr std::ptrdiff_t m_nNumBullets = 0x738; // int32
        constexpr std::ptrdiff_t m_bReloadsSingleShells = 0x73C; // bool
        constexpr std::ptrdiff_t m_flCycleTime = 0x740; // CFiringModeFloat
        constexpr std::ptrdiff_t m_flCycleTimeWhenInBurstMode = 0x748; // float32
        constexpr std::ptrdiff_t m_flTimeBetweenBurstShots = 0x74C; // float32
        constexpr std::ptrdiff_t m_flMaxSpeed = 0x750; // CFiringModeFloat
        constexpr std::ptrdiff_t m_flSpread = 0x758; // CFiringModeFloat
        constexpr std::ptrdiff_t m_flInaccuracyCrouch = 0x760; // CFiringModeFloat
        constexpr std::ptrdiff_t m_flInaccuracyStand = 0x768; // CFiringModeFloat
        constexpr std::ptrdiff_t m_flInaccuracyJump = 0x770; // CFiringModeFloat
        constexpr std::ptrdiff_t m_flInaccuracyLand = 0x778; // CFiringModeFloat
        constexpr std::ptrdiff_t m_flInaccuracyLadder = 0x780; // CFiringModeFloat
        constexpr std::ptrdiff_t m_flInaccuracyFire = 0x788; // CFiringModeFloat
        constexpr std::ptrdiff_t m_flInaccuracyMove = 0x790; // CFiringModeFloat
        constexpr std::ptrdiff_t m_flRecoilAngle = 0x798; // CFiringModeFloat
        constexpr std::ptrdiff_t m_flRecoilAngleVariance = 0x7A0; // CFiringModeFloat
        constexpr std::ptrdiff_t m_flRecoilMagnitude = 0x7A8; // CFiringModeFloat
        constexpr std::ptrdiff_t m_flRecoilMagnitudeVariance = 0x7B0; // CFiringModeFloat
        constexpr std::ptrdiff_t m_nTracerFrequency = 0x7B8; // CFiringModeInt
        constexpr std::ptrdiff_t m_flInaccuracyJumpInitial = 0x7C0; // float32
        constexpr std::ptrdiff_t m_flInaccuracyJumpApex = 0x7C4; // float32
        constexpr std::ptrdiff_t m_flInaccuracyReload = 0x7C8; // float32
        constexpr std::ptrdiff_t m_flDeployDuration = 0x7CC; // float32
        constexpr std::ptrdiff_t m_flDisallowAttackAfterReloadStartDuration = 0x7D0; // float32
        constexpr std::ptrdiff_t m_nBurstShotCount = 0x7D4; // int32
        constexpr std::ptrdiff_t m_bAllowBurstHolster = 0x7D8; // bool
        constexpr std::ptrdiff_t m_nRecoilSeed = 0x7DC; // int32
        constexpr std::ptrdiff_t m_nSpreadSeed = 0x7E0; // int32
        constexpr std::ptrdiff_t m_flAttackMovespeedFactor = 0x7E4; // float32
        constexpr std::ptrdiff_t m_flInaccuracyPitchShift = 0x7E8; // float32
        constexpr std::ptrdiff_t m_flInaccuracyAltSoundThreshold = 0x7EC; // float32
        constexpr std::ptrdiff_t m_szUseRadioSubtitle = 0x7F0; // CUtlString
        constexpr std::ptrdiff_t m_bUnzoomsAfterShot = 0x7F8; // bool
        constexpr std::ptrdiff_t m_bHideViewModelWhenZoomed = 0x7F9; // bool
        constexpr std::ptrdiff_t m_nZoomLevels = 0x7FC; // int32
        constexpr std::ptrdiff_t m_nZoomFOV1 = 0x800; // int32
        constexpr std::ptrdiff_t m_nZoomFOV2 = 0x804; // int32
        constexpr std::ptrdiff_t m_flZoomTime0 = 0x808; // float32
        constexpr std::ptrdiff_t m_flZoomTime1 = 0x80C; // float32
        constexpr std::ptrdiff_t m_flZoomTime2 = 0x810; // float32
        constexpr std::ptrdiff_t m_flIronSightPullUpSpeed = 0x814; // float32
        constexpr std::ptrdiff_t m_flIronSightPutDownSpeed = 0x818; // float32
        constexpr std::ptrdiff_t m_flIronSightFOV = 0x81C; // float32
        constexpr std::ptrdiff_t m_flIronSightPivotForward = 0x820; // float32
        constexpr std::ptrdiff_t m_flIronSightLooseness = 0x824; // float32
        constexpr std::ptrdiff_t m_nDamage = 0x828; // int32
        constexpr std::ptrdiff_t m_flHeadshotMultiplier = 0x82C; // float32
        constexpr std::ptrdiff_t m_flArmorRatio = 0x830; // float32
        constexpr std::ptrdiff_t m_flPenetration = 0x834; // float32
        constexpr std::ptrdiff_t m_flRange = 0x838; // float32
        constexpr std::ptrdiff_t m_flRangeModifier = 0x83C; // float32
        constexpr std::ptrdiff_t m_flFlinchVelocityModifierLarge = 0x840; // float32
        constexpr std::ptrdiff_t m_flFlinchVelocityModifierSmall = 0x844; // float32
        constexpr std::ptrdiff_t m_flRecoveryTimeCrouch = 0x848; // float32
        constexpr std::ptrdiff_t m_flRecoveryTimeStand = 0x84C; // float32
        constexpr std::ptrdiff_t m_flRecoveryTimeCrouchFinal = 0x850; // float32
        constexpr std::ptrdiff_t m_flRecoveryTimeStandFinal = 0x854; // float32
        constexpr std::ptrdiff_t m_nRecoveryTransitionStartBullet = 0x858; // int32
        constexpr std::ptrdiff_t m_nRecoveryTransitionEndBullet = 0x85C; // int32
        constexpr std::ptrdiff_t m_flThrowVelocity = 0x860; // float32
        constexpr std::ptrdiff_t m_vSmokeColor = 0x864; // Vector
        constexpr std::ptrdiff_t m_szAnimClass = 0x870; // CGlobalSymbol
    }

    // CBasePlayerWeaponVData
    namespace CBasePlayerWeaponVData {
        constexpr std::ptrdiff_t m_szWorldModel = 0x28; // CResourceNameTyped<CWeakHandle<InfoForResourceTypeCModel>>
        constexpr std::ptrdiff_t m_szWorldModelAg2Override = 0x108; // CResourceNameTyped<CWeakHandle<InfoForResourceTypeCModel>>
        constexpr std::ptrdiff_t m_sToolsOnlyOwnerModelName = 0x1E8; // CResourceNameTyped<CWeakHandle<InfoForResourceTypeCModel>>
        constexpr std::ptrdiff_t m_bBuiltRightHanded = 0x2C8; // bool
        constexpr std::ptrdiff_t m_bAllowFlipping = 0x2C9; // bool
        constexpr std::ptrdiff_t m_sMuzzleAttachment = 0x2D0; // CAttachmentNameSymbolWithStorage
        constexpr std::ptrdiff_t m_szMuzzleFlashParticle = 0x2F0; // CResourceNameTyped<CWeakHandle<InfoForResourceTypeIParticleSystemDefinition>>
        constexpr std::ptrdiff_t m_szMuzzleFlashParticleConfig = 0x3D0; // CUtlString
        constexpr std::ptrdiff_t m_szBarrelSmokeParticle = 0x3D8; // CResourceNameTyped<CWeakHandle<InfoForResourceTypeIParticleSystemDefinition>>
        constexpr std::ptrdiff_t m_nMuzzleSmokeShotThreshold = 0x4B8; // uint8
        constexpr std::ptrdiff_t m_flMuzzleSmokeTimeout = 0x4BC; // float32
        constexpr std::ptrdiff_t m_flMuzzleSmokeDecrementRate = 0x4C0; // float32
        constexpr std::ptrdiff_t m_bGenerateMuzzleLight = 0x4C4; // bool
        constexpr std::ptrdiff_t m_bLinkedCooldowns = 0x4C5; // bool
        constexpr std::ptrdiff_t m_iFlags = 0x4C6; // ItemFlagTypes_t
        constexpr std::ptrdiff_t m_iWeight = 0x4C8; // int32
        constexpr std::ptrdiff_t m_bAutoSwitchTo = 0x4CC; // bool
        constexpr std::ptrdiff_t m_bAutoSwitchFrom = 0x4CD; // bool
        constexpr std::ptrdiff_t m_nPrimaryAmmoType = 0x4CE; // AmmoIndex_t
        constexpr std::ptrdiff_t m_nSecondaryAmmoType = 0x4CF; // AmmoIndex_t
        constexpr std::ptrdiff_t m_iMaxClip1 = 0x4D0; // int32
        constexpr std::ptrdiff_t m_iMaxClip2 = 0x4D4; // int32
        constexpr std::ptrdiff_t m_iDefaultClip1 = 0x4D8; // int32
        constexpr std::ptrdiff_t m_iDefaultClip2 = 0x4DC; // int32
        constexpr std::ptrdiff_t m_bReserveAmmoAsClips = 0x4E0; // bool
        constexpr std::ptrdiff_t m_bTreatAsSingleClip = 0x4E1; // bool
        constexpr std::ptrdiff_t m_bKeepLoadedAmmo = 0x4E2; // bool
        constexpr std::ptrdiff_t m_iRumbleEffect = 0x4E4; // RumbleEffect_t
        constexpr std::ptrdiff_t m_flDropSpeed = 0x4E8; // float32
        constexpr std::ptrdiff_t m_iSlot = 0x4EC; // int32
        constexpr std::ptrdiff_t m_iPosition = 0x4F0; // int32
        constexpr std::ptrdiff_t m_aShootSounds = 0x4F8; // CUtlOrderedMap<WeaponSound_t,CSoundEventName>
    }

    // CPlayer_WeaponServices : CPlayerPawnComponent
    namespace CPlayer_WeaponServices {
        constexpr std::ptrdiff_t m_hMyWeapons = 0x48; // C_NetworkUtlVectorBase<CHandle<C_BasePlayerWeapon>>
        constexpr std::ptrdiff_t m_hActiveWeapon = 0x60; // CHandle<C_BasePlayerWeapon>
        constexpr std::ptrdiff_t m_hLastWeapon = 0x64; // CHandle<C_BasePlayerWeapon>
        constexpr std::ptrdiff_t m_iAmmo = 0x68; // uint16[32]
    }

    // CCSPlayer_WeaponServices : CPlayer_WeaponServices
    namespace CCSPlayer_WeaponServices {
        constexpr std::ptrdiff_t m_flNextAttack = 0xD0; // GameTime_t
        constexpr std::ptrdiff_t m_nOldTotalShootPositionHistoryCount = 0xD4; // uint32
        constexpr std::ptrdiff_t m_nOldTotalInputHistoryCount = 0x370; // uint32
        constexpr std::ptrdiff_t m_networkAnimTiming = 0x1588; // C_NetworkUtlVectorBase<uint8>
        constexpr std::ptrdiff_t m_bBlockInspectUntilNextGraphUpdate = 0x15A0; // bool
    }

    // CPlayer_CameraServices : CPlayerPawnComponent
    namespace CPlayer_CameraServices {
        constexpr std::ptrdiff_t m_vecCsViewPunchAngle = 0x48; // QAngle
        constexpr std::ptrdiff_t m_nCsViewPunchAngleTick = 0x54; // GameTick_t
        constexpr std::ptrdiff_t m_flCsViewPunchAngleTickRatio = 0x58; // float32
        constexpr std::ptrdiff_t m_PlayerFog = 0x60; // C_fogplayerparams_t
        constexpr std::ptrdiff_t m_hColorCorrectionCtrl = 0xA0; // CHandle<C_ColorCorrection>
        constexpr std::ptrdiff_t m_hViewEntity = 0xA4; // CHandle<C_BaseEntity>
        constexpr std::ptrdiff_t m_hTonemapController = 0xA8; // CHandle<C_TonemapController2>
        constexpr std::ptrdiff_t m_audio = 0xB0; // audioparams_t
        constexpr std::ptrdiff_t m_PostProcessingVolumes = 0x128; // C_NetworkUtlVectorBase<CHandle<C_PostProcessingVolume>>
        constexpr std::ptrdiff_t m_flOldPlayerZ = 0x140; // float32
        constexpr std::ptrdiff_t m_flOldPlayerViewOffsetZ = 0x144; // float32
        constexpr std::ptrdiff_t m_CurrentFog = 0x148; // fogparams_t
        constexpr std::ptrdiff_t m_hOldFogController = 0x1B0; // CHandle<C_FogController>
        constexpr std::ptrdiff_t m_bOverrideFogColor = 0x1B4; // bool[5]
        constexpr std::ptrdiff_t m_OverrideFogColor = 0x1B9; // Color[5]
        constexpr std::ptrdiff_t m_bOverrideFogStartEnd = 0x1CD; // bool[5]
        constexpr std::ptrdiff_t m_fOverrideFogStart = 0x1D4; // float32[5]
        constexpr std::ptrdiff_t m_fOverrideFogEnd = 0x1E8; // float32[5]
        constexpr std::ptrdiff_t m_hActivePostProcessingVolume = 0x1FC; // CHandle<C_PostProcessingVolume>
        constexpr std::ptrdiff_t m_angDemoViewAngles = 0x200; // QAngle
    }

    // CCSPlayerBase_CameraServices : CPlayer_CameraServices
    namespace CCSPlayerBase_CameraServices {
        constexpr std::ptrdiff_t m_iFOV = 0x290; // uint32
        constexpr std::ptrdiff_t m_iFOVStart = 0x294; // uint32
        constexpr std::ptrdiff_t m_flFOVTime = 0x298; // GameTime_t
        constexpr std::ptrdiff_t m_flFOVRate = 0x29C; // float32
        constexpr std::ptrdiff_t m_hZoomOwner = 0x2A0; // CHandle<C_BaseEntity>
        constexpr std::ptrdiff_t m_flLastShotFOV = 0x2A4; // float32
    }

    // CCSPlayer_CameraServices : CCSPlayerBase_CameraServices
    namespace CCSPlayer_CameraServices {
        constexpr std::ptrdiff_t m_flDeathCamTilt = 0x2A8; // float32
        constexpr std::ptrdiff_t m_vClientScopeInaccuracy = 0x2B0; // Vector
    }

    // CPlayer_MovementServices : CPlayerPawnComponent
    namespace CPlayer_MovementServices {
        constexpr std::ptrdiff_t m_nImpulse = 0x48; // int32
        constexpr std::ptrdiff_t m_nButtons = 0x50; // CInButtonState
        constexpr std::ptrdiff_t m_nQueuedButtonDownMask = 0x70; // uint64
        constexpr std::ptrdiff_t m_nQueuedButtonChangeMask = 0x78; // uint64
        constexpr std::ptrdiff_t m_nButtonDoublePressed = 0x80; // uint64
        constexpr std::ptrdiff_t m_pButtonPressedCmdNumber = 0x88; // uint32[64]
        constexpr std::ptrdiff_t m_nLastCommandNumberProcessed = 0x188; // uint32
        constexpr std::ptrdiff_t m_nToggleButtonDownMask = 0x190; // uint64
        constexpr std::ptrdiff_t m_flCmdForwardMove = 0x1A0; // float32
        constexpr std::ptrdiff_t m_flCmdLeftMove = 0x1A4; // float32
        constexpr std::ptrdiff_t m_flCmdUpMove = 0x1A8; // float32
        constexpr std::ptrdiff_t m_flMaxspeed = 0x1AC; // float32
        constexpr std::ptrdiff_t m_arrForceSubtickMoveWhen = 0x1B0; // float32[4]
        constexpr std::ptrdiff_t m_flForwardMove = 0x1C0; // float32
        constexpr std::ptrdiff_t m_flLeftMove = 0x1C4; // float32
        constexpr std::ptrdiff_t m_flUpMove = 0x1C8; // float32
        constexpr std::ptrdiff_t m_vecLastMovementImpulses = 0x1CC; // Vector
        constexpr std::ptrdiff_t m_vecOldViewAngles = 0x240; // QAngle
    }

    // CCSPlayer_MovementServices : CPlayer_MovementServices_Humanoid
    namespace CCSPlayer_MovementServices {
        constexpr std::ptrdiff_t m_AnimationState = 0x310; // CCSPlayerAnimationState
        constexpr std::ptrdiff_t m_bUsingGroundTopologyOffset = 0x3F0; // bool
        constexpr std::ptrdiff_t m_flUsingGroundTopologyOffsetTransitionSmoothing = 0x3F4; // float32
        constexpr std::ptrdiff_t m_vecLadderNormal = 0x3F8; // Vector
        constexpr std::ptrdiff_t m_nLadderSurfacePropIndex = 0x404; // int32
        constexpr std::ptrdiff_t m_bDucked = 0x408; // bool
        constexpr std::ptrdiff_t m_flDuckAmount = 0x40C; // float32
        constexpr std::ptrdiff_t m_flDuckSpeed = 0x410; // float32
        constexpr std::ptrdiff_t m_bDuckOverride = 0x414; // bool
        constexpr std::ptrdiff_t m_bDesiresDuck = 0x415; // bool
        constexpr std::ptrdiff_t m_bDucking = 0x416; // bool
        constexpr std::ptrdiff_t m_flDuckRootOffset = 0x418; // float32
        constexpr std::ptrdiff_t m_flDuckViewOffset = 0x41C; // float32
        constexpr std::ptrdiff_t m_flLastDuckTime = 0x420; // float32
        constexpr std::ptrdiff_t m_flBombPlantViewOffset = 0x424; // float32
        constexpr std::ptrdiff_t m_vecLastPositionAtFullCrouchSpeed = 0x430; // Vector2D
        constexpr std::ptrdiff_t m_duckUntilOnGround = 0x438; // bool
        constexpr std::ptrdiff_t m_bHasWalkMovedSinceLastJump = 0x439; // bool
        constexpr std::ptrdiff_t m_bInStuckTest = 0x43A; // bool
        constexpr std::ptrdiff_t m_nTraceCount = 0x648; // int32
        constexpr std::ptrdiff_t m_StuckLast = 0x64C; // int32
        constexpr std::ptrdiff_t m_bSpeedCropped = 0x650; // bool
        constexpr std::ptrdiff_t m_nOldWaterLevel = 0x654; // int32
        constexpr std::ptrdiff_t m_flWaterEntryTime = 0x658; // float32
        constexpr std::ptrdiff_t m_vecForward = 0x65C; // Vector
        constexpr std::ptrdiff_t m_vecLeft = 0x668; // Vector
        constexpr std::ptrdiff_t m_vecUp = 0x674; // Vector
        constexpr std::ptrdiff_t m_nGameCodeHasMovedPlayerAfterCommand = 0x680; // int32
        constexpr std::ptrdiff_t m_fStashGrenadeParameterWhen = 0x684; // GameTime_t
        constexpr std::ptrdiff_t m_bUseFrictionStashedSpeed = 0x688; // bool
        constexpr std::ptrdiff_t m_flUseFrictionStashedSpeedUntilFrac = 0x68C; // float32
        constexpr std::ptrdiff_t m_flFrictionStashedSpeed = 0x690; // float32
        constexpr std::ptrdiff_t m_flStamina = 0x694; // float32
        constexpr std::ptrdiff_t m_flHeightAtJumpStart = 0x698; // float32
        constexpr std::ptrdiff_t m_flMaxJumpHeightThisJump = 0x69C; // float32
        constexpr std::ptrdiff_t m_flMaxJumpHeightLastJump = 0x6A0; // float32
        constexpr std::ptrdiff_t m_flStaminaAtJumpStart = 0x6A4; // float32
        constexpr std::ptrdiff_t m_flVelMulAtJumpStart = 0x6A8; // float32
        constexpr std::ptrdiff_t m_flAccumulatedJumpError = 0x6AC; // float32
        constexpr std::ptrdiff_t m_LegacyJump = 0x6B0; // CCSPlayerLegacyJump
        constexpr std::ptrdiff_t m_ModernJump = 0x6C8; // CCSPlayerModernJump
        constexpr std::ptrdiff_t m_nLastJumpTick = 0x700; // GameTick_t
        constexpr std::ptrdiff_t m_flLastJumpFrac = 0x704; // float32
        constexpr std::ptrdiff_t m_flLastJumpVelocityZ = 0x708; // float32
        constexpr std::ptrdiff_t m_bJumpApexPending = 0x70C; // bool
        constexpr std::ptrdiff_t m_flTicksSinceLastSurfingDetected = 0x710; // float32
        constexpr std::ptrdiff_t m_bWasSurfing = 0x714; // bool
        constexpr std::ptrdiff_t m_vecWalkWishVel = 0x7A4; // Vector2D
        constexpr std::ptrdiff_t m_bHasEverProcessedCommand = 0xFD0; // bool
    }

    // CCSPlayerModernJump
    namespace CCSPlayerModernJump {
        constexpr std::ptrdiff_t m_nLastActualJumpPressTick = 0x10; // GameTick_t
        constexpr std::ptrdiff_t m_flLastActualJumpPressFrac = 0x14; // float32
        constexpr std::ptrdiff_t m_nLastUsableJumpPressTick = 0x18; // GameTick_t
        constexpr std::ptrdiff_t m_flLastUsableJumpPressFrac = 0x1C; // float32
        constexpr std::ptrdiff_t m_nLastLandedTick = 0x20; // GameTick_t
        constexpr std::ptrdiff_t m_flLastLandedFrac = 0x24; // float32
        constexpr std::ptrdiff_t m_flLastLandedVelocityX = 0x28; // float32
        constexpr std::ptrdiff_t m_flLastLandedVelocityY = 0x2C; // float32
        constexpr std::ptrdiff_t m_flLastLandedVelocityZ = 0x30; // float32
    }

    // CEntityIdentity
    namespace CEntityIdentity {
        constexpr std::ptrdiff_t m_nameStringTableIndex = 0x14; // int32
        constexpr std::ptrdiff_t m_name = 0x18; // CUtlSymbolLarge
        constexpr std::ptrdiff_t m_designerName = 0x20; // CUtlSymbolLarge
        constexpr std::ptrdiff_t m_flags = 0x30; // uint32
        constexpr std::ptrdiff_t m_worldGroupId = 0x38; // WorldGroupId_t
        constexpr std::ptrdiff_t m_fDataObjectTypes = 0x3C; // uint32
        constexpr std::ptrdiff_t m_PathIndex = 0x40; // ChangeAccessorFieldPathIndex_t
        constexpr std::ptrdiff_t m_pAttributes = 0x48; // CEntityAttributeTable*
        constexpr std::ptrdiff_t m_pPrev = 0x50; // CEntityIdentity*
        constexpr std::ptrdiff_t m_pNext = 0x58; // CEntityIdentity*
        constexpr std::ptrdiff_t m_pPrevByClass = 0x60; // CEntityIdentity*
        constexpr std::ptrdiff_t m_pNextByClass = 0x68; // CEntityIdentity*
    }

    // CEntityInstance
    namespace CEntityInstance {
        constexpr std::ptrdiff_t m_iszPrivateVScripts = 0x8; // CUtlSymbolLarge
        constexpr std::ptrdiff_t m_pEntity = 0x10; // CEntityIdentity*
        constexpr std::ptrdiff_t m_CScriptComponent = 0x28; // CScriptComponent*
    }

    // CBodyComponent : CEntityComponent
    namespace CBodyComponent {
        constexpr std::ptrdiff_t m_pSceneNode = 0x8; // CGameSceneNode*
        constexpr std::ptrdiff_t __m_pChainEntity = 0x48; // CNetworkVarChainer
    }

    // CBodyComponentSkeletonInstance : CBodyComponent
    namespace CBodyComponentSkeletonInstance {
        constexpr std::ptrdiff_t m_skeletonInstance = 0x80; // CSkeletonInstance
    }

    // CSkeletonInstance : CGameSceneNode
    namespace CSkeletonInstance {
        constexpr std::ptrdiff_t m_modelState = 0x140; // CModelState
        constexpr std::ptrdiff_t m_bUseParentRenderBounds = 0x3F0; // bool
        constexpr std::ptrdiff_t m_bDisableSolidCollisionsForHierarchy = 0x3F1; // bool
        constexpr std::ptrdiff_t m_bDirtyMotionType = 0x3F2; // bool
        constexpr std::ptrdiff_t m_bIsGeneratingLatchedParentSpaceState = 0x3F3; // bool
        constexpr std::ptrdiff_t m_materialGroup = 0x3F8; // CUtlStringToken
        constexpr std::ptrdiff_t m_nHitboxSet = 0x3FC; // uint8
    }

    // CModelState
    namespace CModelState {
        constexpr std::ptrdiff_t m_hModel = 0xA0; // CStrongHandle<InfoForResourceTypeCModel>
        constexpr std::ptrdiff_t m_ModelName = 0xA8; // CUtlSymbolLarge
        constexpr std::ptrdiff_t m_pVPhysicsAggregate = 0xE0; // IPhysAggregateInstance*
        constexpr std::ptrdiff_t m_flRootBoneOffset_x = 0xE8; // float32
        constexpr std::ptrdiff_t m_flRootBoneOffset_y = 0xEC; // float32
        constexpr std::ptrdiff_t m_flRootBoneOffset_z = 0xF0; // float32
        constexpr std::ptrdiff_t m_nRootBoneOffsetResetSerialNumber = 0xF4; // uint8
        constexpr std::ptrdiff_t m_bClientClothCreationSuppressed = 0x110; // bool
        constexpr std::ptrdiff_t m_nAnimStateNoInterpSerialNumber = 0x200; // uint8
        constexpr std::ptrdiff_t m_MeshGroupMask = 0x208; // uint64
        constexpr std::ptrdiff_t m_nBodyGroupChoices = 0x258; // C_NetworkUtlVectorBase<int32>
        constexpr std::ptrdiff_t m_nIdealMotionType = 0x2A2; // int8
        constexpr std::ptrdiff_t m_nForceLOD = 0x2A3; // int8
        constexpr std::ptrdiff_t m_nClothUpdateFlags = 0x2A4; // int8
    }

    // CBaseAnimGraph : C_BaseModelEntity
    namespace CBaseAnimGraph {
        constexpr std::ptrdiff_t m_graphControllerManager = 0xFB0; // CAnimGraphControllerManager
        constexpr std::ptrdiff_t m_pMainGraphController = 0x1048; // CAnimGraphControllerPtr
        constexpr std::ptrdiff_t m_bInitiallyPopulateInterpHistory = 0x1050; // bool
        constexpr std::ptrdiff_t m_bSuppressAnimEventSounds = 0x1052; // bool
        constexpr std::ptrdiff_t m_OnLayerCycleUpdated = 0x1058; // CEntityOutputTemplate<float32>
        constexpr std::ptrdiff_t m_OnExternalChoreoGraphChanged = 0x1078; // CEntityIOOutput
        constexpr std::ptrdiff_t m_bAnimGraphUpdateEnabled = 0x1098; // bool
        constexpr std::ptrdiff_t m_bAnimationUpdateScheduled = 0x1099; // bool
        constexpr std::ptrdiff_t m_vecForce = 0x109C; // Vector
        constexpr std::ptrdiff_t m_nForceBone = 0x10A8; // int32
        constexpr std::ptrdiff_t m_pClientsideRagdoll = 0x10B0; // CBaseAnimGraph*
        constexpr std::ptrdiff_t m_bBuiltRagdoll = 0x10B8; // bool
        constexpr std::ptrdiff_t m_pRagdollControl = 0x10C8; // IPhysicsRagdollControl*
        constexpr std::ptrdiff_t m_RagdollPose = 0x10D0; // PhysicsRagdollPose_t
        constexpr std::ptrdiff_t m_bRagdollEnabled = 0x1118; // bool
        constexpr std::ptrdiff_t m_bRagdollClientSide = 0x1119; // bool
        constexpr std::ptrdiff_t m_bHasAnimatedMaterialAttributes = 0x1128; // bool
    }

    // PhysicsRagdollPose_t
    namespace PhysicsRagdollPose_t {
        constexpr std::ptrdiff_t m_Transforms = 0x8; // C_NetworkUtlVectorBase<CTransform>
        constexpr std::ptrdiff_t m_hOwner = 0x20; // CHandle<C_BaseEntity>
        constexpr std::ptrdiff_t m_bSetFromDebugHistory = 0x24; // bool
    }

    // C_BaseModelEntity : C_BaseEntity
    namespace C_BaseModelEntity {
        constexpr std::ptrdiff_t m_CRenderComponent = 0xAF0; // CRenderComponent*
        constexpr std::ptrdiff_t m_CHitboxComponent = 0xAF8; // CHitboxComponent
        constexpr std::ptrdiff_t m_pChoreoComponent = 0xB10; // CChoreoComponent*
        constexpr std::ptrdiff_t m_nDestructiblePartInitialStateDestructed0 = 0xB18; // HitGroup_t
        constexpr std::ptrdiff_t m_nDestructiblePartInitialStateDestructed1 = 0xB1C; // HitGroup_t
        constexpr std::ptrdiff_t m_nDestructiblePartInitialStateDestructed2 = 0xB20; // HitGroup_t
        constexpr std::ptrdiff_t m_nDestructiblePartInitialStateDestructed3 = 0xB24; // HitGroup_t
        constexpr std::ptrdiff_t m_nDestructiblePartInitialStateDestructed4 = 0xB28; // HitGroup_t
        constexpr std::ptrdiff_t m_nDestructiblePartInitialStateDestructed0_PartIndex = 0xB2C; // int32
        constexpr std::ptrdiff_t m_nDestructiblePartInitialStateDestructed1_PartIndex = 0xB30; // int32
        constexpr std::ptrdiff_t m_nDestructiblePartInitialStateDestructed2_PartIndex = 0xB34; // int32
        constexpr std::ptrdiff_t m_nDestructiblePartInitialStateDestructed3_PartIndex = 0xB38; // int32
        constexpr std::ptrdiff_t m_nDestructiblePartInitialStateDestructed4_PartIndex = 0xB3C; // int32
        constexpr std::ptrdiff_t m_bDestructiblePartInitialStateDestructed0_GenerateBreakpieces = 0xB40; // bool
        constexpr std::ptrdiff_t m_bDestructiblePartInitialStateDestructed1_GenerateBreakpieces = 0xB41; // bool
        constexpr std::ptrdiff_t m_bDestructiblePartInitialStateDestructed2_GenerateBreakpieces = 0xB42; // bool
        constexpr std::ptrdiff_t m_bDestructiblePartInitialStateDestructed3_GenerateBreakpieces = 0xB43; // bool
        constexpr std::ptrdiff_t m_bDestructiblePartInitialStateDestructed4_GenerateBreakpieces = 0xB44; // bool
        constexpr std::ptrdiff_t m_pDestructiblePartsSystemComponent = 0xB48; // CDestructiblePartsComponent*
        constexpr std::ptrdiff_t m_bInitModelEffects = 0xC70; // bool
        constexpr std::ptrdiff_t m_bDoingModelEffects = 0xC71; // bool
        constexpr std::ptrdiff_t m_iOldHealth = 0xC74; // int32
        constexpr std::ptrdiff_t m_nRenderMode = 0xC78; // RenderMode_t
        constexpr std::ptrdiff_t m_nRenderFX = 0xC79; // RenderFx_t
        constexpr std::ptrdiff_t m_bAllowFadeInView = 0xC7A; // bool
        constexpr std::ptrdiff_t m_clrRender = 0xC98; // Color
        constexpr std::ptrdiff_t m_vecRenderAttributes = 0xCA0; // C_UtlVectorEmbeddedNetworkVar<EntityRenderAttribute_t>
        constexpr std::ptrdiff_t m_bRenderToCubemaps = 0xD20; // bool
        constexpr std::ptrdiff_t m_bNoInterpolate = 0xD21; // bool
        constexpr std::ptrdiff_t m_Collision = 0xD28; // CCollisionProperty
        constexpr std::ptrdiff_t m_Glow = 0xDE0; // CGlowProperty
        constexpr std::ptrdiff_t m_flGlowBackfaceMult = 0xE38; // float32
        constexpr std::ptrdiff_t m_fadeMinDist = 0xE3C; // float32
        constexpr std::ptrdiff_t m_fadeMaxDist = 0xE40; // float32
        constexpr std::ptrdiff_t m_flFadeScale = 0xE44; // float32
        constexpr std::ptrdiff_t m_flShadowStrength = 0xE48; // float32
        constexpr std::ptrdiff_t m_nObjectCulling = 0xE4C; // uint8
        constexpr std::ptrdiff_t m_nRequiredDecalRtEncoding = 0xE4D; // DecalRtEncoding_t
        constexpr std::ptrdiff_t m_bodyGroupChoices = 0xE50; // CUtlOrderedMap<CGlobalSymbol,int32>
        constexpr std::ptrdiff_t m_vecViewOffset = 0xE78; // CNetworkViewOffsetVector
        constexpr std::ptrdiff_t m_pClientAlphaProperty = 0xF58; // CClientAlphaProperty*
        constexpr std::ptrdiff_t m_ClientOverrideTint = 0xF60; // Color
        constexpr std::ptrdiff_t m_bUseClientOverrideTint = 0xF64; // bool
        constexpr std::ptrdiff_t m_bvDisabledHitGroups = 0xFA0; // uint32[1]
    }

} // namespace cs2_dumper::cheat_fields
