// Generated by CS2Dumper — 2026-07-17T15:19:48Z
// IEngineCvar / CConVar layout + curated ConVar name index.
#pragma once
#include <cstddef>
#include <cstdint>

namespace cs2_dumper::convars {

    namespace layout {
        // IEngineCvar (or list indirection base)
        constexpr std::ptrdiff_t count = 0x30;
        constexpr std::ptrdiff_t array = 0x50;
        constexpr std::ptrdiff_t list_indirection = 0x0; // 0 = inline
        constexpr std::ptrdiff_t engine_cvar_rva = 0x3A44F0; // tier0.dll, 0 if heap
        constexpr bool found = true;

        // CConVar
        constexpr std::ptrdiff_t CConVar_szName = 0x0;
        constexpr std::ptrdiff_t CConVar_szDescription = 0x20;
        constexpr std::ptrdiff_t CConVar_nType = 0x28;
        constexpr std::ptrdiff_t CConVar_nFlags = 0x30;
        constexpr std::ptrdiff_t CConVar_value = 0x58; // CVValue_t
        constexpr std::ptrdiff_t Node_stride = 0x10;
    }

    // Important ConVars present in this build (name list — resolve live via VEngineCvar007)
    namespace important {
        constexpr const char* sv_cheats = "sv_cheats";
        constexpr const char* cam_idealdist = "cam_idealdist";
        constexpr const char* cam_collision = "cam_collision";
        constexpr const char* c_thirdpersonshoulder = "c_thirdpersonshoulder";
        constexpr const char* rate = "rate";
        constexpr const char* fps_max = "fps_max";
        constexpr const char* mp_damage_scale_ct_head = "mp_damage_scale_ct_head";
        constexpr const char* mp_damage_scale_t_head = "mp_damage_scale_t_head";
        constexpr const char* weapon_accuracy_nospread = "weapon_accuracy_nospread";
        constexpr const char* weapon_debug_spread_show = "weapon_debug_spread_show";
        constexpr const char* cl_interp_ratio = "cl_interp_ratio";
    }

    constexpr std::size_t total_count = 4018;
} // namespace cs2_dumper::convars
