// Generated by CS2Dumper — 2026-07-17T15:19:48Z
// Module: engine2.dll
namespace CS2Dumper.Schemas;

public static partial class CEmptyEntityInstance {
}

public static partial class CEntityAttributeTable {
    public const nint m_Attributes = 0x0; // CUtlOrderedMap<CUtlStringTokenNoRegistration,Attribute_t>
    public const nint m_Names = 0x28; // CUtlOrderedMap<CUtlStringTokenNoRegistration,CUtlString>
}

public static partial class CEntityComponent {
}

public static partial class CEntityComponentHelper {
    public const nint m_flags = 0x8; // uint32
    public const nint m_pInfo = 0x10; // EntComponentInfo_t*
    public const nint m_nPriority = 0x18; // int32
    public const nint m_pNext = 0x20; // CEntityComponentHelper*
}

public static partial class CEntityIOOutput {
}

public static partial class CEntityIdentity {
    public const nint m_nameStringTableIndex = 0x14; // int32
    public const nint m_name = 0x18; // CUtlSymbolLarge
    public const nint m_designerName = 0x20; // CUtlSymbolLarge
    public const nint m_flags = 0x30; // uint32
    public const nint m_worldGroupId = 0x38; // WorldGroupId_t
    public const nint m_fDataObjectTypes = 0x3C; // uint32
    public const nint m_PathIndex = 0x40; // ChangeAccessorFieldPathIndex_t
    public const nint m_pAttributes = 0x48; // CEntityAttributeTable*
    public const nint m_pPrev = 0x50; // CEntityIdentity*
    public const nint m_pNext = 0x58; // CEntityIdentity*
    public const nint m_pPrevByClass = 0x60; // CEntityIdentity*
    public const nint m_pNextByClass = 0x68; // CEntityIdentity*
}

public static partial class CEntityInstance {
    public const nint m_iszPrivateVScripts = 0x8; // CUtlSymbolLarge
    public const nint m_pEntity = 0x10; // CEntityIdentity*
    public const nint m_CScriptComponent = 0x28; // CScriptComponent*
}

public static partial class CEntityKeyValues {
}

public static partial class CNetworkVarChainer {
    public const nint m_PathIndex = 0x20; // ChangeAccessorFieldPathIndex_t
}

public static partial class CScriptComponent {
    public const nint m_scriptClassName = 0x30; // CUtlSymbolLarge
}

public static partial class CVariantDefaultAllocator {
}

public static partial class EngineLoopState_t {
    public const nint m_nPlatWindowWidth = 0x18; // int32
    public const nint m_nPlatWindowHeight = 0x1C; // int32
    public const nint m_nRenderWidth = 0x20; // int32
    public const nint m_nRenderHeight = 0x24; // int32
}

public static partial class EntComponentInfo_t {
    public const nint m_pName = 0x0; // char*
    public const nint m_pCPPClassname = 0x8; // char*
    public const nint m_pNetworkDataReferencedDescription = 0x10; // char*
    public const nint m_pNetworkDataReferencedPtrPropDescription = 0x18; // char*
    public const nint m_nRuntimeIndex = 0x20; // int32
    public const nint m_nFlags = 0x24; // uint32
    public const nint m_pBaseClassComponentHelper = 0x60; // CEntityComponentHelper*
}

public static partial class EntInput_t {
}

public static partial class EntityIOQueuePrioritizedEvent_t {
    public const nint m_flFireTime = 0x4; // GameTime_t
    public const nint m_targetType = 0x8; // EntityIOTargetType_t
    public const nint m_pTarget = 0x10; // CUtlSymbolLarge
    public const nint m_pTargetInput = 0x18; // CUtlSymbolLarge
    public const nint m_hActivator = 0x20; // CEntityHandle
    public const nint m_hCaller = 0x24; // CEntityHandle
    public const nint m_hEntTarget = 0x28; // CEntityHandle
    public const nint m_variantValue = 0x30; // CVariantBase<CVariantDefaultAllocator>
}

public static partial class EventAdvanceTick_t {
    public const nint m_nCurrentTick = 0x30; // int32
    public const nint m_nCurrentTickThisFrame = 0x34; // int32
    public const nint m_nTotalTicksThisFrame = 0x38; // int32
    public const nint m_nTotalTicks = 0x3C; // int32
}

public static partial class EventAppShutdown_t {
    public const nint m_nDummy0 = 0x0; // int32
}

public static partial class EventBugBugComplete_t {
    public const nint m_pPayload = 0x0; // EventBugBug_t*
}

public static partial class EventBugBug_t {
}

public static partial class EventClientAdvanceNonRenderedFrame_t {
}

public static partial class EventClientAdvanceTick_t {
}

public static partial class EventClientFrameSimulate_t {
    public const nint m_LoopState = 0x0; // EngineLoopState_t
    public const nint m_flRealTime = 0x28; // float32
    public const nint m_flFrameTime = 0x2C; // float32
    public const nint m_bScheduleSendTickPacket = 0x30; // bool
}

public static partial class EventClientOutput_t {
    public const nint m_LoopState = 0x0; // EngineLoopState_t
    public const nint m_flRenderTime = 0x28; // float32
    public const nint m_flRealTime = 0x2C; // float32
    public const nint m_flRenderFrameTimeUnbounded = 0x30; // float32
    public const nint m_bRenderOnly = 0x34; // bool
}

public static partial class EventClientPauseSimulate_t {
}

public static partial class EventClientPollInput_t {
    public const nint m_LoopState = 0x0; // EngineLoopState_t
    public const nint m_flRealTime = 0x28; // float32
}

public static partial class EventClientPollNetworking_t {
    public const nint m_nTickCount = 0x0; // int32
}

public static partial class EventClientPostAdvanceTick_t {
}

public static partial class EventClientPostOutput_t {
    public const nint m_LoopState = 0x0; // EngineLoopState_t
    public const nint m_flRenderTime = 0x28; // float64
    public const nint m_flRenderFrameTime = 0x30; // float32
    public const nint m_flRenderFrameTimeUnbounded = 0x34; // float32
    public const nint m_bRenderOnly = 0x38; // bool
}

public static partial class EventClientPostSimulate_t {
}

public static partial class EventClientPreOutputParallelWithServer_t {
}

public static partial class EventClientPreOutput_t {
    public const nint m_LoopState = 0x0; // EngineLoopState_t
    public const nint m_flRenderTime = 0x28; // float64
    public const nint m_flRenderFrameTime = 0x30; // float64
    public const nint m_flRenderFrameTimeUnbounded = 0x38; // float64
    public const nint m_flRealTime = 0x40; // float32
    public const nint m_bRenderOnly = 0x44; // bool
}

public static partial class EventClientPreSimulate_t {
}

public static partial class EventClientProcessGameInput_t {
    public const nint m_LoopState = 0x0; // EngineLoopState_t
    public const nint m_flRealTime = 0x28; // float32
    public const nint m_flFrameTime = 0x2C; // float32
}

public static partial class EventClientProcessInput_t {
    public const nint m_LoopState = 0x0; // EngineLoopState_t
    public const nint m_flRealTime = 0x28; // float32
    public const nint m_flTickInterval = 0x2C; // float32
    public const nint m_flTickStartTime = 0x30; // float64
}

public static partial class EventClientProcessNetworking_t {
    public const nint m_nTickCount = 0x0; // int32
}

public static partial class EventClientSceneSystemThreadStateChange_t {
    public const nint m_bThreadsActive = 0x0; // bool
}

public static partial class EventClientSimulate_t {
}

public static partial class EventFrameBoundary_t {
    public const nint m_flFrameTime = 0x0; // float32
}

public static partial class EventModInitialized_t {
}

public static partial class EventPostAdvanceTick_t {
    public const nint m_nCurrentTick = 0x30; // int32
    public const nint m_nCurrentTickThisFrame = 0x34; // int32
    public const nint m_nTotalTicksThisFrame = 0x38; // int32
    public const nint m_nTotalTicks = 0x3C; // int32
}

public static partial class EventPostDataUpdate_t {
    public const nint m_nCount = 0x0; // int32
}

public static partial class EventPreDataUpdate_t {
    public const nint m_nCount = 0x0; // int32
}

public static partial class EventProfileStorageAvailable_t {
    public const nint m_nSplitScreenSlot = 0x0; // CSplitScreenSlot
}

public static partial class EventServerAdvanceTick_t {
}

public static partial class EventServerBeginAsyncPostTickWork_t {
    public const nint m_bIsOncePerFrameAsyncWorkPhase = 0x0; // bool
}

public static partial class EventServerBeginSimulate_t {
}

public static partial class EventServerEndAsyncPostTickWork_t {
}

public static partial class EventServerEndSimulate_t {
    public const nint m_bLastTick = 0x0; // bool
}

public static partial class EventServerPollNetworking_t {
}

public static partial class EventServerPostAdvanceTick_t {
    public const nint m_bLastTickBeforeClientUpdate = 0x40; // bool
}

public static partial class EventServerPostSimulate_t {
    public const nint m_bLastTickBeforeClientUpdate = 0x30; // bool
}

public static partial class EventServerProcessNetworking_t {
}

public static partial class EventSetTime_t {
    public const nint m_LoopState = 0x0; // EngineLoopState_t
    public const nint m_nClientOutputFrames = 0x28; // int32
    public const nint m_flRealTime = 0x30; // float64
    public const nint m_flRenderTime = 0x38; // float64
    public const nint m_flRenderFrameTime = 0x40; // float64
    public const nint m_flRenderFrameTimeUnbounded = 0x48; // float64
    public const nint m_flRenderFrameTimeUnscaled = 0x50; // float64
    public const nint m_flTickRemainder = 0x58; // float64
}

public static partial class EventSimpleLoopFrameUpdate_t {
    public const nint m_LoopState = 0x0; // EngineLoopState_t
    public const nint m_flRealTime = 0x28; // float32
    public const nint m_flFrameTime = 0x2C; // float32
}

public static partial class EventSimulate_t {
    public const nint m_LoopState = 0x0; // EngineLoopState_t
    public const nint m_bFirstTick = 0x28; // bool
    public const nint m_bLastTick = 0x29; // bool
}

public static partial class EventSplitScreenStateChanged_t {
}

public static partial class GameTick_t {
    public const nint m_Value = 0x0; // int32
}

public static partial class GameTime_t {
    public const nint m_Value = 0x0; // float32
}

public enum EntityDormancyType_t : int {
    ENTITY_NOT_DORMANT = 0,
    ENTITY_DORMANT = 1,
    ENTITY_SUSPENDED = 2,
}

public enum EntityIOTargetType_t : int {
    ENTITY_IO_TARGET_INVALID = -1,
    ENTITY_IO_TARGET_ENTITYNAME = 2,
    ENTITY_IO_TARGET_EHANDLE = 6,
    ENTITY_IO_TARGET_ENTITYNAME_OR_CLASSNAME = 7,
}

