// Generated by CS2Dumper — 2026-07-17T15:19:49Z
// Module: host.dll
namespace CS2Dumper.Schemas;

public static partial class CAnimScriptBase {
    public const nint m_bIsValid = 0x8; // bool
}

public static partial class EmptyTestScript {
    public const nint m_hTest = 0x10; // CAnimScriptParam<float32>
}

