// Generated by CS2Dumper — 2026-07-17T15:19:48Z
// Module: host.dll
#pragma once
#include <cstddef>
#include <cstdint>

namespace cs2_dumper::schemas::host_dll {

    // CAnimScriptBase
    namespace CAnimScriptBase {
        constexpr std::ptrdiff_t m_bIsValid = 0x8; // bool
    }

    // EmptyTestScript
    namespace EmptyTestScript {
        constexpr std::ptrdiff_t m_hTest = 0x10; // CAnimScriptParam<float32>
    }

} // namespace cs2_dumper::schemas::host_dll
