// Generated by CS2Dumper — 2026-07-17T15:19:48Z
#pragma once
#include <cstdint>

namespace cs2_dumper::info {

    constexpr uint32_t build_number = 14171;
    constexpr const char* timestamp = "2026-07-17T15:19:40Z";

} // namespace cs2_dumper::info
