// Generated by CS2Dumper — 2026-07-17T15:19:48Z
namespace CS2Dumper.Interfaces;

public static partial class animationsystem_dll {
    public const nint AnimationSystemUtils_001 = 0x90560;
    public const nint AnimationSystem_001 = 0x89940;
}

public static partial class client_dll {
    public const nint ClientBugBugServic001_Client = 0xB289E0;
    public const nint ClientToolsInfo_001 = 0xB289F0;
    public const nint EmptyWorldService001_Client = 0x75F730;
    public const nint GameClientExports001 = 0xB28A00;
    public const nint LegacyGameUI001 = 0xCE2910;
    public const nint Source2Client002 = 0xB28A10;
    public const nint Source2ClientConfig001 = 0x738770;
    public const nint Source2ClientPrediction001 = 0xB916B0;
    public const nint Source2ClientUI001 = 0xCA6390;
}

public static partial class engine2_dll {
    public const nint BenchmarkService001 = 0x1A5140;
    public const nint BugBugService001 = 0x1A9A50;
    public const nint BugService001 = 0x1A61A0;
    public const nint ClientServerEngineLoopService_001 = 0x221B40;
    public const nint ClientServerSharedHandleSystem001 = 0x1FCDB0;
    public const nint EngineGameUI001 = 0x13B310;
    public const nint EngineServiceMgr001 = 0x20F210;
    public const nint GameEventSystemClientV001 = 0x214AA0;
    public const nint GameEventSystemServerV001 = 0x214AB0;
    public const nint GameResourceServiceClientV001 = 0x1AD860;
    public const nint GameResourceServiceServerV001 = 0x1AD870;
    public const nint GameUIService_001 = 0x1B0DF0;
    public const nint HostStateMgr001 = 0x219530;
    public const nint INETSUPPORT_001 = 0x106B00;
    public const nint InputService_001 = 0x1B6230;
    public const nint KeyValueCache001 = 0x21BBE0;
    public const nint MapListService_001 = 0x1C9A80;
    public const nint NetworkClientService_001 = 0x1D1020;
    public const nint NetworkP2PService_001 = 0x1D8950;
    public const nint NetworkServerService_001 = 0x1DD520;
    public const nint NetworkService_001 = 0x1E3620;
    public const nint RenderService_001 = 0x1E3B10;
    public const nint ScreenshotService001 = 0x1E6970;
    public const nint SimpleEngineLoopService_001 = 0x231920;
    public const nint SoundService_001 = 0x1EB860;
    public const nint Source2EngineToClient001 = 0x753F0;
    public const nint Source2EngineToClientStringTable001 = 0x9B440;
    public const nint Source2EngineToServer001 = 0xA1EC0;
    public const nint Source2EngineToServerStringTable001 = 0xBA350;
    public const nint SplitScreenService_001 = 0x1F2310;
    public const nint StatsService_001 = 0x1F4F50;
    public const nint ToolService_001 = 0x1F9450;
    public const nint VENGINE_GAMEUIFUNCS_VERSION005 = 0x13C010;
    public const nint VProfService_001 = 0x1FA8D0;
}

public static partial class filesystem_stdio_dll {
    public const nint VAsyncFileSystem2_001 = 0x646B0;
    public const nint VFileSystem017 = 0x646A0;
}

public static partial class host_dll {
    public const nint DebugDrawQueueManager001 = 0x15920;
    public const nint GameModelInfo001 = 0x15E20;
    public const nint GameSystem2HostHook = 0x15F00;
    public const nint HostUtils001 = 0x168E0;
    public const nint PredictionDiffManager001 = 0x1C0A0;
    public const nint SaveRestoreDataVersion001 = 0x1E4F0;
    public const nint SinglePlayerSharedMemory001 = 0x1E500;
    public const nint Source2Host001 = 0x1E8B0;
}

public static partial class inputsystem_dll {
    public const nint InputStackSystemVersion001 = 0x17C0;
    public const nint InputSystemVersion001 = 0x29D0;
}

public static partial class localize_dll {
    public const nint Localize_001 = 0x1FD70;
}

public static partial class matchmaking_dll {
    public const nint GameTypes001 = 0x36320;
    public const nint MATCHFRAMEWORK_001 = 0xEA440;
}

public static partial class materialsystem2_dll {
    public const nint FontManager_001 = 0x47D60;
    public const nint MaterialUtils_001 = 0x63740;
    public const nint PostProcessingSystem_001 = 0x56F30;
    public const nint TextLayout_001 = 0x5F7A0;
    public const nint VMaterialSystem2_001 = 0x353A0;
}

public static partial class meshsystem_dll {
    public const nint MeshSystem001 = 0xAE50;
}

public static partial class networksystem_dll {
    public const nint FlattenedSerializersVersion001 = 0x9DF70;
    public const nint NetworkMessagesVersion001 = 0xD5050;
    public const nint NetworkSystemVersion001 = 0xE9510;
    public const nint SerializedEntitiesVersion001 = 0x103C70;
}

public static partial class panorama_dll {
    public const nint PanoramaUIEngine001 = 0x6D7D0;
}

public static partial class particles_dll {
    public const nint ParticleSystemMgr003 = 0xA3290;
}

public static partial class pulse_system_dll {
    public const nint IPulseSystem_001 = 0xA0A0;
}

public static partial class rendersystemdx11_dll {
    public const nint RenderDeviceMgr001 = 0x54B20;
    public const nint RenderUtils_001 = 0x65160;
    public const nint VRenderDeviceMgrBackdoor001 = 0x54B30;
}

public static partial class resourcesystem_dll {
    public const nint ResourceSystem013 = 0x138C0;
}

public static partial class scenefilecache_dll {
    public const nint ResponseRulesCache001 = 0x8BB0;
    public const nint SceneFileCache002 = 0xCC20;
}

public static partial class scenesystem_dll {
    public const nint RenderingPipelines_001 = 0xB5FF0;
    public const nint SceneSystem_002 = 0xDC370;
    public const nint SceneUtils_001 = 0x17D5C0;
}

public static partial class schemasystem_dll {
    public const nint SchemaSystem_001 = 0xD9B0;
}

public static partial class server_dll {
    public const nint EmptyWorldService001_Server = 0x927520;
    public const nint EntitySubclassUtilsV001 = 0x52BB20;
    public const nint NavGameTest001 = 0xFC4E20;
    public const nint ServerToolsInfo_001 = 0xD2E8D0;
    public const nint Source2GameClients001 = 0xD2E8E0;
    public const nint Source2GameDirector001 = 0x1F2980;
    public const nint Source2GameEntities001 = 0xD2E8F0;
    public const nint Source2Server001 = 0xD2E900;
    public const nint Source2ServerConfig001 = 0x905380;
    public const nint customnavsystem001 = 0x388810;
}

public static partial class soundsystem_dll {
    public const nint SoundBugBugService001_Client = 0x1E8B40;
    public const nint SoundOpSystem001 = 0x1D34D0;
    public const nint SoundOpSystemEdit001 = 0xBAA40;
    public const nint SoundSystem001 = 0x5D880;
    public const nint VMixEditTool001 = 0x94C30;
}

public static partial class steamaudio_dll {
    public const nint SteamAudio001 = 0x604D0;
}

public static partial class tier0_dll {
    public const nint TestScriptMgr001 = 0x169A40;
    public const nint VEngineCvar007 = 0x685A0;
    public const nint VProcessUtils002 = 0x1573E0;
    public const nint VStringTokenSystem001 = 0x1A0300;
}

public static partial class vphysics2_dll {
    public const nint VPhysics2_Interface_001 = 0x69580;
}

public static partial class worldrenderer_dll {
    public const nint WorldRendererMgr001 = 0x25AC0;
}

