// Generated by CS2Dumper — 2026-07-17T15:19:48Z
#pragma once
#include <cstddef>

namespace cs2_dumper::interfaces {

    namespace animationsystem_dll {
        constexpr std::ptrdiff_t AnimationSystemUtils_001 = 0x90560;
        constexpr std::ptrdiff_t AnimationSystem_001 = 0x89940;
    }

    namespace client_dll {
        constexpr std::ptrdiff_t ClientBugBugServic001_Client = 0xB289E0;
        constexpr std::ptrdiff_t ClientToolsInfo_001 = 0xB289F0;
        constexpr std::ptrdiff_t EmptyWorldService001_Client = 0x75F730;
        constexpr std::ptrdiff_t GameClientExports001 = 0xB28A00;
        constexpr std::ptrdiff_t LegacyGameUI001 = 0xCE2910;
        constexpr std::ptrdiff_t Source2Client002 = 0xB28A10;
        constexpr std::ptrdiff_t Source2ClientConfig001 = 0x738770;
        constexpr std::ptrdiff_t Source2ClientPrediction001 = 0xB916B0;
        constexpr std::ptrdiff_t Source2ClientUI001 = 0xCA6390;
    }

    namespace engine2_dll {
        constexpr std::ptrdiff_t BenchmarkService001 = 0x1A5140;
        constexpr std::ptrdiff_t BugBugService001 = 0x1A9A50;
        constexpr std::ptrdiff_t BugService001 = 0x1A61A0;
        constexpr std::ptrdiff_t ClientServerEngineLoopService_001 = 0x221B40;
        constexpr std::ptrdiff_t ClientServerSharedHandleSystem001 = 0x1FCDB0;
        constexpr std::ptrdiff_t EngineGameUI001 = 0x13B310;
        constexpr std::ptrdiff_t EngineServiceMgr001 = 0x20F210;
        constexpr std::ptrdiff_t GameEventSystemClientV001 = 0x214AA0;
        constexpr std::ptrdiff_t GameEventSystemServerV001 = 0x214AB0;
        constexpr std::ptrdiff_t GameResourceServiceClientV001 = 0x1AD860;
        constexpr std::ptrdiff_t GameResourceServiceServerV001 = 0x1AD870;
        constexpr std::ptrdiff_t GameUIService_001 = 0x1B0DF0;
        constexpr std::ptrdiff_t HostStateMgr001 = 0x219530;
        constexpr std::ptrdiff_t INETSUPPORT_001 = 0x106B00;
        constexpr std::ptrdiff_t InputService_001 = 0x1B6230;
        constexpr std::ptrdiff_t KeyValueCache001 = 0x21BBE0;
        constexpr std::ptrdiff_t MapListService_001 = 0x1C9A80;
        constexpr std::ptrdiff_t NetworkClientService_001 = 0x1D1020;
        constexpr std::ptrdiff_t NetworkP2PService_001 = 0x1D8950;
        constexpr std::ptrdiff_t NetworkServerService_001 = 0x1DD520;
        constexpr std::ptrdiff_t NetworkService_001 = 0x1E3620;
        constexpr std::ptrdiff_t RenderService_001 = 0x1E3B10;
        constexpr std::ptrdiff_t ScreenshotService001 = 0x1E6970;
        constexpr std::ptrdiff_t SimpleEngineLoopService_001 = 0x231920;
        constexpr std::ptrdiff_t SoundService_001 = 0x1EB860;
        constexpr std::ptrdiff_t Source2EngineToClient001 = 0x753F0;
        constexpr std::ptrdiff_t Source2EngineToClientStringTable001 = 0x9B440;
        constexpr std::ptrdiff_t Source2EngineToServer001 = 0xA1EC0;
        constexpr std::ptrdiff_t Source2EngineToServerStringTable001 = 0xBA350;
        constexpr std::ptrdiff_t SplitScreenService_001 = 0x1F2310;
        constexpr std::ptrdiff_t StatsService_001 = 0x1F4F50;
        constexpr std::ptrdiff_t ToolService_001 = 0x1F9450;
        constexpr std::ptrdiff_t VENGINE_GAMEUIFUNCS_VERSION005 = 0x13C010;
        constexpr std::ptrdiff_t VProfService_001 = 0x1FA8D0;
    }

    namespace filesystem_stdio_dll {
        constexpr std::ptrdiff_t VAsyncFileSystem2_001 = 0x646B0;
        constexpr std::ptrdiff_t VFileSystem017 = 0x646A0;
    }

    namespace host_dll {
        constexpr std::ptrdiff_t DebugDrawQueueManager001 = 0x15920;
        constexpr std::ptrdiff_t GameModelInfo001 = 0x15E20;
        constexpr std::ptrdiff_t GameSystem2HostHook = 0x15F00;
        constexpr std::ptrdiff_t HostUtils001 = 0x168E0;
        constexpr std::ptrdiff_t PredictionDiffManager001 = 0x1C0A0;
        constexpr std::ptrdiff_t SaveRestoreDataVersion001 = 0x1E4F0;
        constexpr std::ptrdiff_t SinglePlayerSharedMemory001 = 0x1E500;
        constexpr std::ptrdiff_t Source2Host001 = 0x1E8B0;
    }

    namespace inputsystem_dll {
        constexpr std::ptrdiff_t InputStackSystemVersion001 = 0x17C0;
        constexpr std::ptrdiff_t InputSystemVersion001 = 0x29D0;
    }

    namespace localize_dll {
        constexpr std::ptrdiff_t Localize_001 = 0x1FD70;
    }

    namespace matchmaking_dll {
        constexpr std::ptrdiff_t GameTypes001 = 0x36320;
        constexpr std::ptrdiff_t MATCHFRAMEWORK_001 = 0xEA440;
    }

    namespace materialsystem2_dll {
        constexpr std::ptrdiff_t FontManager_001 = 0x47D60;
        constexpr std::ptrdiff_t MaterialUtils_001 = 0x63740;
        constexpr std::ptrdiff_t PostProcessingSystem_001 = 0x56F30;
        constexpr std::ptrdiff_t TextLayout_001 = 0x5F7A0;
        constexpr std::ptrdiff_t VMaterialSystem2_001 = 0x353A0;
    }

    namespace meshsystem_dll {
        constexpr std::ptrdiff_t MeshSystem001 = 0xAE50;
    }

    namespace networksystem_dll {
        constexpr std::ptrdiff_t FlattenedSerializersVersion001 = 0x9DF70;
        constexpr std::ptrdiff_t NetworkMessagesVersion001 = 0xD5050;
        constexpr std::ptrdiff_t NetworkSystemVersion001 = 0xE9510;
        constexpr std::ptrdiff_t SerializedEntitiesVersion001 = 0x103C70;
    }

    namespace panorama_dll {
        constexpr std::ptrdiff_t PanoramaUIEngine001 = 0x6D7D0;
    }

    namespace particles_dll {
        constexpr std::ptrdiff_t ParticleSystemMgr003 = 0xA3290;
    }

    namespace pulse_system_dll {
        constexpr std::ptrdiff_t IPulseSystem_001 = 0xA0A0;
    }

    namespace rendersystemdx11_dll {
        constexpr std::ptrdiff_t RenderDeviceMgr001 = 0x54B20;
        constexpr std::ptrdiff_t RenderUtils_001 = 0x65160;
        constexpr std::ptrdiff_t VRenderDeviceMgrBackdoor001 = 0x54B30;
    }

    namespace resourcesystem_dll {
        constexpr std::ptrdiff_t ResourceSystem013 = 0x138C0;
    }

    namespace scenefilecache_dll {
        constexpr std::ptrdiff_t ResponseRulesCache001 = 0x8BB0;
        constexpr std::ptrdiff_t SceneFileCache002 = 0xCC20;
    }

    namespace scenesystem_dll {
        constexpr std::ptrdiff_t RenderingPipelines_001 = 0xB5FF0;
        constexpr std::ptrdiff_t SceneSystem_002 = 0xDC370;
        constexpr std::ptrdiff_t SceneUtils_001 = 0x17D5C0;
    }

    namespace schemasystem_dll {
        constexpr std::ptrdiff_t SchemaSystem_001 = 0xD9B0;
    }

    namespace server_dll {
        constexpr std::ptrdiff_t EmptyWorldService001_Server = 0x927520;
        constexpr std::ptrdiff_t EntitySubclassUtilsV001 = 0x52BB20;
        constexpr std::ptrdiff_t NavGameTest001 = 0xFC4E20;
        constexpr std::ptrdiff_t ServerToolsInfo_001 = 0xD2E8D0;
        constexpr std::ptrdiff_t Source2GameClients001 = 0xD2E8E0;
        constexpr std::ptrdiff_t Source2GameDirector001 = 0x1F2980;
        constexpr std::ptrdiff_t Source2GameEntities001 = 0xD2E8F0;
        constexpr std::ptrdiff_t Source2Server001 = 0xD2E900;
        constexpr std::ptrdiff_t Source2ServerConfig001 = 0x905380;
        constexpr std::ptrdiff_t customnavsystem001 = 0x388810;
    }

    namespace soundsystem_dll {
        constexpr std::ptrdiff_t SoundBugBugService001_Client = 0x1E8B40;
        constexpr std::ptrdiff_t SoundOpSystem001 = 0x1D34D0;
        constexpr std::ptrdiff_t SoundOpSystemEdit001 = 0xBAA40;
        constexpr std::ptrdiff_t SoundSystem001 = 0x5D880;
        constexpr std::ptrdiff_t VMixEditTool001 = 0x94C30;
    }

    namespace steamaudio_dll {
        constexpr std::ptrdiff_t SteamAudio001 = 0x604D0;
    }

    namespace tier0_dll {
        constexpr std::ptrdiff_t TestScriptMgr001 = 0x169A40;
        constexpr std::ptrdiff_t VEngineCvar007 = 0x685A0;
        constexpr std::ptrdiff_t VProcessUtils002 = 0x1573E0;
        constexpr std::ptrdiff_t VStringTokenSystem001 = 0x1A0300;
    }

    namespace vphysics2_dll {
        constexpr std::ptrdiff_t VPhysics2_Interface_001 = 0x69580;
    }

    namespace worldrenderer_dll {
        constexpr std::ptrdiff_t WorldRendererMgr001 = 0x25AC0;
    }

} // namespace cs2_dumper::interfaces
