// Generated by CS2Dumper — 2026-07-17T15:19:48Z
// Non-schema Source 2 layouts (GlobalVars, CCSGOInput, Prediction, EntitySystem).
#pragma once
#include <cstddef>
#include <cstdint>

namespace cs2_dumper::layouts {

    // CGameEntitySystem
    namespace CGameEntitySystem {
        constexpr std::ptrdiff_t EntityList_EntrySize = 0x70; // bytes per entity slot in chunk [doc]
        constexpr std::ptrdiff_t EntityList_Chunks = 0x10; // pointer to chunk table (documented) [doc]
        constexpr std::ptrdiff_t EntityHandle_IndexShift = 0x9; // handle >> 9 = chunk index [doc]
        constexpr std::ptrdiff_t EntityHandle_IndexMask = 0x1FF; // handle & 0x1FF = slot in chunk [doc]
        constexpr std::ptrdiff_t highestEntityIndex = 0x2090; // from offset dump / a2x [doc]
    }

    // CCSGOInput
    namespace CCSGOInput {
        constexpr std::ptrdiff_t thirdPersonSlotBase = 0x228; // lea rdi,[rcx+0x228] in ThirdPersonReset [doc]
        constexpr std::ptrdiff_t thirdPersonSlotStride = 0x928; // imul rax,rbx,0x928 per player slot [doc]
        constexpr std::ptrdiff_t bInThirdPerson = 0x229; // slotBase+1 (bool) [doc]
        constexpr std::ptrdiff_t thirdPersonAngles = 0x230; // QAngle near thirdperson slot [doc]
        constexpr std::ptrdiff_t viewAngles_field = 0x688; // from dwViewAngles_field pattern (dwCSGOInput embed + field) [doc]
        constexpr std::ptrdiff_t vt_handle_camera_angles = 0x8; // vtable index — AntiAim AllowCameraAngleChange [doc]
    }

    // CPrediction
    namespace CPrediction {
        constexpr std::ptrdiff_t InPrediction = 0x34; // bool — EnginePrediction [doc]
        constexpr std::ptrdiff_t FirstPrediction = 0x81; // bool — EnginePrediction [doc]
    }

    // CGlobalVars
    namespace CGlobalVars {
        constexpr std::ptrdiff_t m_flRealTime = 0x0; // float [doc]
        constexpr std::ptrdiff_t m_iFrameCount = 0x4; // int [doc]
        constexpr std::ptrdiff_t m_flFrameTime = 0x8; // float — AbsoluteFrameTime [doc]
        constexpr std::ptrdiff_t m_flFrameAdvance = 0xC; // float [doc]
        constexpr std::ptrdiff_t m_flCurTime = 0x30; // float — EnginePrediction verified [doc]
        constexpr std::ptrdiff_t m_flRenderTime = 0x34; // float [doc]
        constexpr std::ptrdiff_t m_flClientTickFraction = 0x38; // float [doc]
        constexpr std::ptrdiff_t m_flNextTickFraction = 0x3C; // float [doc]
        constexpr std::ptrdiff_t m_nTickCount = 0x48; // int — EnginePrediction verified [doc]
        constexpr std::ptrdiff_t m_uCurrentMapName = 0x188; // char* — CS2_Internal verified [doc]
    }

    // CUserCmd
    namespace CUserCmd {
        constexpr std::ptrdiff_t vftable = 0x0; // void* [doc]
        constexpr std::ptrdiff_t sequence_number = 0x8; // uint32 [doc]
        constexpr std::ptrdiff_t csgoUserCmd = 0x10; // CCSGOUserCmdPB embedded (size 0x48) [doc]
        constexpr std::ptrdiff_t nButtons = 0x58; // CInButtonState embedded (size 0x20) [doc]
        constexpr std::ptrdiff_t has_been_predicted = 0x88; // int32 — EnginePrediction [doc]
        constexpr std::ptrdiff_t prediction_cmd_type = 0x8C; // int32 [doc]
        constexpr std::ptrdiff_t cmd_type = 0x90; // int32 [doc]
        constexpr std::ptrdiff_t prediction_reason = 0x94; // int32 [doc]
        constexpr std::ptrdiff_t sizeof = 0x98; // bytes [doc]
        constexpr std::ptrdiff_t pBaseCmd_abs = 0x40; // CUserCmd+0x10+0x30 — shortcut to CBaseUserCmdPB* [doc]
    }

    // CCSGOUserCmdPB
    namespace CCSGOUserCmdPB {
        constexpr std::ptrdiff_t vtable = 0x0; // void* [doc]
        constexpr std::ptrdiff_t nHasBits = 0x8; // uint32 [doc]
        constexpr std::ptrdiff_t nCachedSize = 0x10; // uint64 [doc]
        constexpr std::ptrdiff_t pBaseCmd = 0x30; // CBaseUserCmdPB* [doc]
        constexpr std::ptrdiff_t sizeof = 0x48; // bytes [doc]
    }

    // CBaseUserCmdPB
    namespace CBaseUserCmdPB {
        constexpr std::ptrdiff_t vtable = 0x0; // void* [doc]
        constexpr std::ptrdiff_t nHasBits = 0x8; // uint32 [doc]
        constexpr std::ptrdiff_t nCachedBits = 0x10; // int64 — Bhop sets bit 0x2 when mutating buttons [doc]
        constexpr std::ptrdiff_t pSubtickMoves = 0x18; // start of inline RepeatedPtrField (24 bytes) [doc]
        constexpr std::ptrdiff_t nSubtickCurrentSize = 0x20; // int32 — RepeatedPtrField count [doc]
        constexpr std::ptrdiff_t nSubtickCapacity = 0x24; // int32 [doc]
        constexpr std::ptrdiff_t pSubtickContainer = 0x28; // CSubtickMoveStep** / elements ptr [doc]
        constexpr std::ptrdiff_t pMoveCrc = 0x30; // std::string* [doc]
        constexpr std::ptrdiff_t pInButtonState = 0x38; // CInButtonStatePB* [doc]
        constexpr std::ptrdiff_t pViewAngles = 0x40; // CMsgQAngle* [doc]
        constexpr std::ptrdiff_t pExecutionNotes = 0x48; // void* [doc]
        constexpr std::ptrdiff_t nLegacyCommandNumber = 0x50; // int32 [doc]
        constexpr std::ptrdiff_t nClientTick = 0x54; // int32 [doc]
        constexpr std::ptrdiff_t flForwardMove = 0x58; // float [doc]
        constexpr std::ptrdiff_t flSideMove = 0x5C; // float [doc]
        constexpr std::ptrdiff_t flUpMove = 0x60; // float [doc]
        constexpr std::ptrdiff_t nImpulse = 0x64; // int32 [doc]
        constexpr std::ptrdiff_t nWeaponSelect = 0x68; // int32 [doc]
        constexpr std::ptrdiff_t nRandomSeed = 0x6C; // int32 [doc]
        constexpr std::ptrdiff_t nMousedX = 0x70; // int32 [doc]
        constexpr std::ptrdiff_t nMousedY = 0x74; // int32 [doc]
        constexpr std::ptrdiff_t nPredictionOffsetTicksX256 = 0x78; // uint32 [doc]
        constexpr std::ptrdiff_t nConsumedServerAngleChanges = 0x7C; // uint32 [doc]
        constexpr std::ptrdiff_t nCmdFlags = 0x80; // int32 [doc]
        constexpr std::ptrdiff_t nPawnEntityHandle = 0x84; // uint32 [doc]
        constexpr std::ptrdiff_t sizeof = 0x88; // bytes [doc]
    }

    // RepeatedPtrField_Subtick
    namespace RepeatedPtrField_Subtick {
        constexpr std::ptrdiff_t arena_or_pMoves = 0x0; // relative to CBaseUserCmdPB+0x18 [doc]
        constexpr std::ptrdiff_t current_size = 0x8; // rel = abs 0x20 on CBaseUserCmdPB [doc]
        constexpr std::ptrdiff_t capacity = 0xC; // rel = abs 0x24 [doc]
        constexpr std::ptrdiff_t elements = 0x10; // rel = abs 0x28 — CSubtickMoveStep** [doc]
        constexpr std::ptrdiff_t sizeof = 0x18; // bytes inline [doc]
        constexpr std::ptrdiff_t base_on_CBaseUserCmdPB = 0x18; // lea rcx,[r14+0x18] before ProtobufAdd [doc]
    }

    // CSubtickMoveStep
    namespace CSubtickMoveStep {
        constexpr std::ptrdiff_t pVtable = 0x0; // void* [doc]
        constexpr std::ptrdiff_t pMetadata = 0x8; // void* [doc]
        constexpr std::ptrdiff_t nHasBits = 0x10; // uint32 — BUTTON|PRESSED|WHEN [doc]
        constexpr std::ptrdiff_t nCachedSize = 0x14; // uint32 [doc]
        constexpr std::ptrdiff_t nButton = 0x18; // uint64 — e.g. IN_JUMP [doc]
        constexpr std::ptrdiff_t bPressed = 0x20; // bool [doc]
        constexpr std::ptrdiff_t flWhen = 0x24; // float — land frac or 0 [doc]
        constexpr std::ptrdiff_t flAnalogForwardDelta = 0x28; // float [doc]
        constexpr std::ptrdiff_t flAnalogLeftDelta = 0x2C; // float [doc]
        constexpr std::ptrdiff_t flPitchDelta = 0x30; // float [doc]
        constexpr std::ptrdiff_t flYawDelta = 0x34; // float [doc]
        constexpr std::ptrdiff_t sizeof = 0x38; // bytes — CreateNewSubtickMoveStep imm B9 38 [doc]
        constexpr std::ptrdiff_t CSUBTICK_BITS_BUTTON = 0x1; // nHasBits flag [doc]
        constexpr std::ptrdiff_t CSUBTICK_BITS_PRESSED = 0x2; // nHasBits flag [doc]
        constexpr std::ptrdiff_t CSUBTICK_BITS_WHEN = 0x4; // nHasBits flag [doc]
    }

    // CInButtonState
    namespace CInButtonState {
        constexpr std::ptrdiff_t vtable = 0x0; // void* [doc]
        constexpr std::ptrdiff_t nValue = 0x8; // int64 — buttonstate1 [doc]
        constexpr std::ptrdiff_t nValueChanged = 0x10; // int64 — buttonstate2 [doc]
        constexpr std::ptrdiff_t nValueScroll = 0x18; // int64 — buttonstate3 [doc]
        constexpr std::ptrdiff_t sizeof = 0x20; // bytes [doc]
    }

    // CInButtonStatePB
    namespace CInButtonStatePB {
        constexpr std::ptrdiff_t c_base_pb_header = 0x0; // size 0x18 — protobuf header [doc]
        constexpr std::ptrdiff_t nHasBits = 0x10; // int32 — Bhop ORs 0x07 when mutating [doc]
        constexpr std::ptrdiff_t buttonstate1 = 0x18; // uint64 — mirrors CInButtonState.nValue [doc]
        constexpr std::ptrdiff_t buttonstate2 = 0x20; // uint64 — changed [doc]
        constexpr std::ptrdiff_t buttonstate3 = 0x28; // uint64 — scroll [doc]
    }

    // CMsgQAngle
    namespace CMsgQAngle {
        constexpr std::ptrdiff_t base = 0x0; // CBasePB* [doc]
        constexpr std::ptrdiff_t angValue = 0x18; // QAngle pitch/yaw/roll — AntiAim writes here [doc]
    }

    // InputButtonBits
    namespace InputButtonBits {
        constexpr std::ptrdiff_t IN_ATTACK = 0x1; // bit [doc]
        constexpr std::ptrdiff_t IN_JUMP = 0x2; // bit — Bhop/Subtick [doc]
        constexpr std::ptrdiff_t IN_DUCK = 0x4; // bit [doc]
        constexpr std::ptrdiff_t IN_FORWARD = 0x8; // bit — AutoStrafe [doc]
        constexpr std::ptrdiff_t IN_BACK = 0x10; // bit [doc]
        constexpr std::ptrdiff_t IN_USE = 0x20; // bit [doc]
        constexpr std::ptrdiff_t IN_MOVELEFT = 0x200; // bit [doc]
        constexpr std::ptrdiff_t IN_MOVERIGHT = 0x400; // bit [doc]
        constexpr std::ptrdiff_t IN_ATTACK2 = 0x800; // bit [doc]
        constexpr std::ptrdiff_t IN_RELOAD = 0x2000; // bit [doc]
        constexpr std::ptrdiff_t IN_SCORE = 0x10000; // bit [doc]
        constexpr std::ptrdiff_t FL_ONGROUND = 0x1; // m_fFlags bit 0 [doc]
        constexpr std::ptrdiff_t MOVETYPE_LADDER = 0x9; // enum [doc]
        constexpr std::ptrdiff_t MOVETYPE_NOCLIP = 0x8; // enum [doc]
        constexpr std::ptrdiff_t MOVETYPE_OBSERVER = 0xA; // enum [doc]
        constexpr std::ptrdiff_t PBITS_FORWARD = 0x40; // CBaseUserCmdPB.nHasBits — AutoStrafe [doc]
        constexpr std::ptrdiff_t PBITS_SIDE = 0x80; // CBaseUserCmdPB.nHasBits — AutoStrafe [doc]
        constexpr std::ptrdiff_t BTN_PB_HASBITS_ALL = 0x7; // CInButtonStatePB.nHasBits OR mask [doc]
        constexpr std::ptrdiff_t CACHED_BITS_BUTTONS = 0x2; // CBaseUserCmdPB.nCachedBits when mutating buttons [doc]
    }

    // EnginePrediction
    namespace EnginePrediction {
        constexpr std::ptrdiff_t CPrediction_InPrediction = 0x34; // bool on dwPrediction object [doc]
        constexpr std::ptrdiff_t CPrediction_FirstPrediction = 0x81; // bool on dwPrediction object [doc]
        constexpr std::ptrdiff_t MovementServices_VT_RunCommand = 0x1B; // vtable index [doc]
        constexpr std::ptrdiff_t MovementServices_VT_SetPredictionCommand = 0x2A; // vtable index [doc]
        constexpr std::ptrdiff_t MovementServices_VT_ResetPredictionCommand = 0x2B; // vtable index [doc]
        constexpr std::ptrdiff_t MovementServices_backup_size = 0x5E0; // bytes — hellcore backup window [doc]
        constexpr std::ptrdiff_t pawn_m_pMovementServices = 0x1248; // schema C_BasePlayerPawn — also cheat_fields [doc]
        constexpr std::ptrdiff_t MS_m_ModernJump = 0x6C8; // CCSPlayer_MovementServices embed [doc]
        constexpr std::ptrdiff_t ModernJump_m_nLastLandedTick = 0x20; // relative to CCSPlayerModernJump [doc]
        constexpr std::ptrdiff_t ModernJump_m_flLastLandedFrac = 0x24; // relative to CCSPlayerModernJump [doc]
        constexpr std::ptrdiff_t controller_m_nTickBase = 0x6B8; // CBasePlayerController [doc]
        constexpr std::ptrdiff_t CreateMove_slot_arg = 0x1; // CreateMove(this, int slot, CUserCmd*) [doc]
    }

    // CPlayer_MovementServices_VT
    namespace CPlayer_MovementServices_VT {
        constexpr std::ptrdiff_t RunCommand = 0x1B; // vtable index decimal [doc]
        constexpr std::ptrdiff_t SetPredictionCommand = 0x2A; // vtable index decimal [doc]
        constexpr std::ptrdiff_t ResetPredictionCommand = 0x2B; // vtable index decimal [doc]
        constexpr std::ptrdiff_t backup_size = 0x5E0; // bytes copied around RunCommand [doc]
    }

    // CNetworkGameClient
    namespace CNetworkGameClient {
        constexpr std::ptrdiff_t signOnState = 0x230; // also offsets::dwNetworkGameClient_signOnState [doc]
        constexpr std::ptrdiff_t maxClients = 0x240;
        constexpr std::ptrdiff_t deltaTick_serverTick = 0x24C; // shared field (delta/server tick) [doc]
        constexpr std::ptrdiff_t clientTickCount = 0x378;
        constexpr std::ptrdiff_t localPlayer = 0xF8; // handle — do NOT overwrite in prediction [doc]
    }

    // BoneMatrixPath
    namespace BoneMatrixPath {
        constexpr std::ptrdiff_t pawn_m_CBodyComponent = 0x30; // schema pointer [doc]
        constexpr std::ptrdiff_t body_m_skeletonInstance = 0x80; // EMBEDDED CSkeletonInstance [doc]
        constexpr std::ptrdiff_t skel_m_modelState = 0x140; // EMBEDDED CModelState [doc]
        constexpr std::ptrdiff_t body_to_modelState = 0x1C0; // 0x80+0x140 convenience [doc]
        constexpr std::ptrdiff_t pawn_m_pGameSceneNode = 0x330; // schema — CSkeletonInstance* often [doc]
        constexpr std::ptrdiff_t CModelState_boneArray = 0x80; // NOT schema — community-stable bone matrix ptr [doc]
        constexpr std::ptrdiff_t CModelState_m_hModel = 0xA0; // schema anchor (bones live below this) [doc]
        constexpr std::ptrdiff_t bone_matrix_stride = 0x20; // bytes per bone (matrix3x4_t) [doc]
        constexpr std::ptrdiff_t skel_m_nHitboxSet = 0x3FC; // schema CSkeletonInstance [doc]
        constexpr std::ptrdiff_t BONE_pelvis = 0x1; // index [doc]
        constexpr std::ptrdiff_t BONE_spine_upper = 0x4; // index [doc]
        constexpr std::ptrdiff_t BONE_neck = 0x6; // index [doc]
        constexpr std::ptrdiff_t BONE_head = 0x7; // index [doc]
        constexpr std::ptrdiff_t BONE_l_shoulder = 0x9; // index [doc]
        constexpr std::ptrdiff_t BONE_l_elbow = 0xA; // index [doc]
        constexpr std::ptrdiff_t BONE_l_hand = 0xB; // index [doc]
        constexpr std::ptrdiff_t BONE_r_shoulder = 0x10; // index [doc]
        constexpr std::ptrdiff_t BONE_r_elbow = 0xE; // index [doc]
        constexpr std::ptrdiff_t BONE_r_hand = 0xF; // index [doc]
        constexpr std::ptrdiff_t BONE_l_hip = 0x11; // index [doc]
        constexpr std::ptrdiff_t BONE_l_knee = 0x12; // index [doc]
        constexpr std::ptrdiff_t BONE_l_foot = 0x13; // index [doc]
        constexpr std::ptrdiff_t BONE_r_hip = 0x14; // index [doc]
        constexpr std::ptrdiff_t BONE_r_knee = 0x15; // index [doc]
        constexpr std::ptrdiff_t BONE_r_foot = 0x16; // index [doc]
    }

    // CGameSceneNode
    namespace CGameSceneNode {
        constexpr std::ptrdiff_t m_pOwner = 0x30; // CEntityInstance* — viewmodel backref [doc]
        constexpr std::ptrdiff_t m_pParent = 0x38; // CGameSceneNode* [doc]
        constexpr std::ptrdiff_t m_pChild = 0x40; // CGameSceneNode* — walk children [doc]
        constexpr std::ptrdiff_t m_pNextSibling = 0x48; // CGameSceneNode* — walk siblings [doc]
        constexpr std::ptrdiff_t m_vecOrigin = 0x80; // network origin [doc]
        constexpr std::ptrdiff_t m_vecAbsOrigin = 0xC8; // Vector — ESP position [doc]
        constexpr std::ptrdiff_t m_angAbsRotation = 0xD4; // QAngle [doc]
        constexpr std::ptrdiff_t m_bDormant = 0x103; // bool [doc]
    }

    // CGlowProperty
    namespace CGlowProperty {
        constexpr std::ptrdiff_t m_fGlowColor = 0x8; // Vector [doc]
        constexpr std::ptrdiff_t m_iGlowType = 0x30; // int — 0=none 1=outer 2=outline [doc]
        constexpr std::ptrdiff_t m_iGlowTeam = 0x34; // int [doc]
        constexpr std::ptrdiff_t m_nGlowRange = 0x38; // int [doc]
        constexpr std::ptrdiff_t m_nGlowRangeMin = 0x3C; // int [doc]
        constexpr std::ptrdiff_t m_glowColorOverride = 0x40; // Color RGBA [doc]
        constexpr std::ptrdiff_t m_bFlashing = 0x44; // bool [doc]
        constexpr std::ptrdiff_t m_flGlowTime = 0x48; // float [doc]
        constexpr std::ptrdiff_t m_bEligibleForScreenHighlight = 0x50; // bool [doc]
        constexpr std::ptrdiff_t m_bGlowing = 0x51; // bool [doc]
        constexpr std::ptrdiff_t BaseModel_m_Glow = 0xDE0; // C_BaseModelEntity embedded CGlowProperty [doc]
        constexpr std::ptrdiff_t dwGlowManager = 0x0; // use offsets::dwGlowManager — global list head [doc]
    }

    // CCollisionProperty
    namespace CCollisionProperty {
        constexpr std::ptrdiff_t m_collisionAttribute = 0x10; // VPhysicsCollisionAttribute_t [doc]
        constexpr std::ptrdiff_t m_vecMins = 0x40; // Vector [doc]
        constexpr std::ptrdiff_t m_vecMaxs = 0x4C; // Vector [doc]
        constexpr std::ptrdiff_t m_usSolidFlags = 0x5A; // uint8 [doc]
        constexpr std::ptrdiff_t m_nSolidType = 0x5B; // SolidType_t [doc]
        constexpr std::ptrdiff_t m_CollisionGroup = 0x5E; // uint8 [doc]
        constexpr std::ptrdiff_t m_flBoundingRadius = 0x60; // float [doc]
        constexpr std::ptrdiff_t m_vecSurroundingMins = 0x88; // Vector [doc]
        constexpr std::ptrdiff_t m_vecSurroundingMaxs = 0x7C; // Vector [doc]
        constexpr std::ptrdiff_t m_flCapsuleRadius = 0xAC; // float [doc]
        constexpr std::ptrdiff_t BaseModel_m_Collision = 0xD28; // embedded on C_BaseModelEntity [doc]
        constexpr std::ptrdiff_t BaseModel_m_CHitboxComponent = 0xAF8; // CHitboxComponent [doc]
    }

    // Camera_FOV
    namespace Camera_FOV {
        constexpr std::ptrdiff_t pawn_m_pCameraServices = 0x1240; // schema C_BasePlayerPawn [doc]
        constexpr std::ptrdiff_t CCSPlayerBase_CameraServices_m_iFOV = 0x290; // uint32 [doc]
        constexpr std::ptrdiff_t m_iFOVStart = 0x294; // uint32 [doc]
        constexpr std::ptrdiff_t m_flFOVTime = 0x298; // GameTime_t [doc]
        constexpr std::ptrdiff_t m_flFOVRate = 0x29C; // float [doc]
        constexpr std::ptrdiff_t m_flLastShotFOV = 0x2A4; // float [doc]
        constexpr std::ptrdiff_t dwViewRender = 0x0; // offsets::dwViewRender — CViewRender* global [doc]
        constexpr std::ptrdiff_t note_ViewSetup = 0x0; // FOV prefer CameraServices schema; CViewSetup inside ViewRender shifts often [doc]
    }

    // Animation_Pose
    namespace Animation_Pose {
        constexpr std::ptrdiff_t CBaseAnimGraph_m_pMainGraphController = 0x1048; // schema — modern anim graph (not classic layers) [doc]
        constexpr std::ptrdiff_t m_bAnimGraphUpdateEnabled = 0x1098; // bool [doc]
        constexpr std::ptrdiff_t m_nForceBone = 0x10A8; // int32 [doc]
        constexpr std::ptrdiff_t m_RagdollPose = 0x10D0; // PhysicsRagdollPose_t [doc]
        constexpr std::ptrdiff_t m_bRagdollClientSide = 0x1119; // bool [doc]
        constexpr std::ptrdiff_t PhysicsRagdollPose_m_Transforms = 0x8; // relative [doc]
        constexpr std::ptrdiff_t note = 0x0; // CS2 uses AnimGraph — no classic CAnimationLayer array; use graph + bones [doc]
    }

    // Weapon_Econ_VData
    namespace Weapon_Econ_VData {
        constexpr std::ptrdiff_t C_EconEntity_m_AttributeManager = 0x11A8; // also cheat_fields [doc]
        constexpr std::ptrdiff_t m_nFallbackPaintKit = 0x1680; // uint32 [doc]
        constexpr std::ptrdiff_t m_nFallbackSeed = 0x1684; // uint32 [doc]
        constexpr std::ptrdiff_t m_flFallbackWear = 0x1688; // float [doc]
        constexpr std::ptrdiff_t m_nFallbackStatTrak = 0x168C; // int32 [doc]
        constexpr std::ptrdiff_t C_AttributeContainer_m_Item = 0x50; // C_EconItemView embed [doc]
        constexpr std::ptrdiff_t C_EconItemView_m_iItemDefinitionIndex = 0x1BA; // uint16 [doc]
        constexpr std::ptrdiff_t m_iEntityQuality = 0x1BC; // int32 [doc]
        constexpr std::ptrdiff_t m_iItemIDHigh = 0x1D0; // uint32 [doc]
        constexpr std::ptrdiff_t m_iItemIDLow = 0x1D4; // uint32 [doc]
        constexpr std::ptrdiff_t m_szCustomName = 0x2F8; // char[161] [doc]
        constexpr std::ptrdiff_t VData_m_nDamage = 0x828; // CCSWeaponBaseVData — verify via cheat_fields [doc]
        constexpr std::ptrdiff_t VData_m_flRange = 0x838; // CCSWeaponBaseVData [doc]
        constexpr std::ptrdiff_t VData_m_WeaponType = 0x520; // CCSWeaponBaseVData [doc]
        constexpr std::ptrdiff_t VData_m_nPrice = 0x70C; // CCSWeaponBaseVData [doc]
    }

    // TraceStructs
    namespace TraceStructs {
        constexpr std::ptrdiff_t TraceFilter_t_sizeof = 0x60; // Internal Visibility / some use 0x40 [doc]
        constexpr std::ptrdiff_t CGameTrace_sizeof = 0x108; // common assert size [doc]
        constexpr std::ptrdiff_t CGameTrace_pHitEntity = 0x8; // void* [doc]
        constexpr std::ptrdiff_t CGameTrace_pHitBox = 0x10; // void* [doc]
        constexpr std::ptrdiff_t CGameTrace_nSurfaceFlags = 0x50; // uint32 [doc]
        constexpr std::ptrdiff_t CGameTrace_vecStart = 0x78; // Vector [doc]
        constexpr std::ptrdiff_t CGameTrace_vecEnd = 0x84; // Vector [doc]
        constexpr std::ptrdiff_t CGameTrace_vecNormal = 0x90; // Vector [doc]
        constexpr std::ptrdiff_t CGameTrace_fraction = 0xAC; // float [doc]
        constexpr std::ptrdiff_t CGameTrace_bStartSolid = 0xBB; // bool [doc]
        constexpr std::ptrdiff_t MASK_VISIBLE_CHECK = 0x1C300B; // trace mask [doc]
        constexpr std::ptrdiff_t TraceData_surface_stride = 0x38; // autowall handle index stride [doc]
    }

} // namespace cs2_dumper::layouts
