// Generated by CS2Dumper — 2026-07-17T15:19:48Z
// Module: meshsystem.dll
#pragma once
#include <cstddef>
#include <cstdint>

namespace cs2_dumper::schemas::meshsystem_dll {

} // namespace cs2_dumper::schemas::meshsystem_dll
