// Generated by CS2Dumper — 2026-07-17T15:19:48Z
// Module: networksystem.dll
namespace CS2Dumper.Schemas;

public static partial class ChangeAccessorFieldPathIndex_t {
    public const nint m_Value = 0x0; // int32
}

