// Generated by CS2Dumper — 2026-07-17T15:19:48Z
// Module: networksystem.dll
#pragma once
#include <cstddef>
#include <cstdint>

namespace cs2_dumper::schemas::networksystem_dll {

    // ChangeAccessorFieldPathIndex_t
    namespace ChangeAccessorFieldPathIndex_t {
        constexpr std::ptrdiff_t m_Value = 0x0; // int32
    }

} // namespace cs2_dumper::schemas::networksystem_dll
