// Generated by CS2Dumper — 2026-07-17T15:19:48Z
// Module: pulse_system.dll
namespace CS2Dumper.Schemas;

public static partial class CBasePulseGraphInstance {
}

public static partial class CPulseArraylib {
}

public static partial class CPulseCell_Base {
    public const nint m_nEditorNodeID = 0x8; // PulseDocNodeID_t
}

public static partial class CPulseCell_BaseFlow {
}

public static partial class CPulseCell_BaseLerp {
    public const nint m_WakeResume = 0xD8; // CPulse_ResumePoint
}

public static partial class CPulseCell_BaseLerp__CursorState_t {
    public const nint m_StartTime = 0x0; // GameTime_t
    public const nint m_EndTime = 0x4; // GameTime_t
}

public static partial class CPulseCell_BaseRequirement {
}

public static partial class CPulseCell_BaseState {
}

public static partial class CPulseCell_BaseValue {
}

public static partial class CPulseCell_BaseYieldingInflow {
    public const nint m_BaseFlow_OnAfterCancel = 0x48; // CPulse_ResumePoint
    public const nint m_BaseFlow_WhileActive = 0x90; // CPulse_ResumePoint
}

public static partial class CPulseCell_BooleanSwitchState {
    public const nint m_Condition = 0xD8; // CPulseObservableExpression<bool>
    public const nint m_WhenTrue = 0x150; // CPulse_OutflowConnection
    public const nint m_WhenFalse = 0x198; // CPulse_OutflowConnection
}

public static partial class CPulseCell_CursorQueue {
    public const nint m_nCursorsAllowedToRunParallel = 0x128; // int32
}

public static partial class CPulseCell_ExampleCriteria {
}

public static partial class CPulseCell_ExampleCriteria__Criteria_t {
    public const nint m_flFloatValue1 = 0x0; // float32
    public const nint m_flFloatValue2 = 0x4; // float32
    public const nint m_bMyBool = 0x8; // bool
}

public static partial class CPulseCell_ExampleSelector {
    public const nint m_OutflowList = 0x48; // PulseSelectorOutflowList_t
}

public static partial class CPulseCell_FireCursors {
    public const nint m_Outflows = 0xD8; // CUtlVector<CPulse_OutflowConnection>
    public const nint m_bWaitForChildOutflows = 0xF0; // bool
    public const nint m_OnFinished = 0xF8; // CPulse_ResumePoint
}

public static partial class CPulseCell_Inflow_BaseEntrypoint {
    public const nint m_EntryChunk = 0x48; // PulseRuntimeChunkIndex_t
    public const nint m_RegisterMap = 0x50; // PulseRegisterMap_t
}

public static partial class CPulseCell_Inflow_EntOutputHandler {
    public const nint m_SourceEntity = 0x80; // PulseSymbol_t
    public const nint m_SourceOutput = 0x90; // PulseSymbol_t
    public const nint m_ExpectedParamType = 0xA0; // CPulseValueFullType
}

public static partial class CPulseCell_Inflow_EventHandler {
    public const nint m_EventName = 0x80; // PulseSymbol_t
}

public static partial class CPulseCell_Inflow_GraphHook {
    public const nint m_HookName = 0x80; // PulseSymbol_t
}

public static partial class CPulseCell_Inflow_Method {
    public const nint m_MethodName = 0x80; // PulseSymbol_t
    public const nint m_Description = 0x90; // CUtlString
    public const nint m_bIsPublic = 0x98; // bool
    public const nint m_ReturnType = 0xA0; // CPulseValueFullType
    public const nint m_Args = 0xB8; // CUtlLeanVector<CPulseRuntimeMethodArg>
}

public static partial class CPulseCell_Inflow_ObservableVariableListener {
    public const nint m_nBlackboardReference = 0x80; // PulseRuntimeBlackboardReferenceIndex_t
    public const nint m_bSelfReference = 0x82; // bool
}

public static partial class CPulseCell_Inflow_Wait {
    public const nint m_WakeResume = 0xD8; // CPulse_ResumePoint
}

public static partial class CPulseCell_Inflow_Yield {
    public const nint m_UnyieldResume = 0xD8; // CPulse_ResumePoint
}

public static partial class CPulseCell_InlineNodeSkipSelector {
    public const nint m_nFlowNodeID = 0x48; // PulseDocNodeID_t
    public const nint m_bAnd = 0x4C; // bool
    public const nint m_PassOutflow = 0x50; // PulseSelectorOutflowList_t
    public const nint m_FailOutflow = 0x68; // CPulse_OutflowConnection
}

public static partial class CPulseCell_IntervalTimer {
    public const nint m_Completed = 0xD8; // CPulse_ResumePoint
    public const nint m_OnInterval = 0x120; // SignatureOutflow_Continue
}

public static partial class CPulseCell_IntervalTimer__CursorState_t {
    public const nint m_StartTime = 0x0; // GameTime_t
    public const nint m_EndTime = 0x4; // GameTime_t
    public const nint m_flWaitInterval = 0x8; // float32
    public const nint m_flWaitIntervalHigh = 0xC; // float32
    public const nint m_bCompleteOnNextWake = 0x10; // bool
}

public static partial class CPulseCell_IsRequirementValid {
}

public static partial class CPulseCell_IsRequirementValid__Criteria_t {
    public const nint m_bIsValid = 0x0; // bool
}

public static partial class CPulseCell_LimitCount {
    public const nint m_nLimitCount = 0x48; // int32
}

public static partial class CPulseCell_LimitCount__Criteria_t {
    public const nint m_bLimitCountPasses = 0x0; // bool
}

public static partial class CPulseCell_LimitCount__InstanceState_t {
    public const nint m_nCurrentCount = 0x0; // int32
}

public static partial class CPulseCell_Outflow_CycleOrdered {
    public const nint m_Outputs = 0x48; // CUtlVector<CPulse_OutflowConnection>
}

public static partial class CPulseCell_Outflow_CycleOrdered__InstanceState_t {
    public const nint m_nNextIndex = 0x0; // int32
}

public static partial class CPulseCell_Outflow_CycleRandom {
    public const nint m_Outputs = 0x48; // CUtlVector<CPulse_OutflowConnection>
}

public static partial class CPulseCell_Outflow_CycleShuffled {
    public const nint m_Outputs = 0x48; // CUtlVector<CPulse_OutflowConnection>
}

public static partial class CPulseCell_Outflow_CycleShuffled__InstanceState_t {
    public const nint m_Shuffle = 0x0; // CUtlVectorFixedGrowable<uint8,8>
    public const nint m_nNextShuffle = 0x20; // int32
}

public static partial class CPulseCell_Outflow_TestExplicitYesNo {
    public const nint m_Yes = 0x48; // CPulse_OutflowConnection
    public const nint m_No = 0x90; // CPulse_OutflowConnection
}

public static partial class CPulseCell_Outflow_TestRandomYesNo {
    public const nint m_Yes = 0x48; // CPulse_OutflowConnection
    public const nint m_No = 0x90; // CPulse_OutflowConnection
}

public static partial class CPulseCell_PickBestOutflowSelector {
    public const nint m_nCheckType = 0x48; // PulseBestOutflowRules_t
    public const nint m_OutflowList = 0x50; // PulseSelectorOutflowList_t
}

public static partial class CPulseCell_Step_CallExternalMethod {
    public const nint m_MethodName = 0xD8; // PulseSymbol_t
    public const nint m_nBlackboardIndex = 0xE8; // PulseRuntimeBlackboardReferenceIndex_t
    public const nint m_ExpectedArgs = 0xF0; // CUtlLeanVector<CPulseRuntimeMethodArg>
    public const nint m_nAsyncCallMode = 0x100; // PulseMethodCallMode_t
    public const nint m_OnFinished = 0x108; // CPulse_ResumePoint
}

public static partial class CPulseCell_Step_DebugLog {
}

public static partial class CPulseCell_Step_PublicOutput {
    public const nint m_OutputIndex = 0x48; // PulseRuntimeOutputIndex_t
}

public static partial class CPulseCell_Step_TestDomainCreateFakeEntity {
}

public static partial class CPulseCell_Step_TestDomainDestroyFakeEntity {
}

public static partial class CPulseCell_Step_TestDomainEntFire {
    public const nint m_Input = 0x48; // CUtlString
}

public static partial class CPulseCell_Step_TestDomainTracepoint {
}

public static partial class CPulseCell_TestEnums {
    public const nint m_nReferenceColor = 0x48; // PulseTestEnumColor_t
    public const nint m_nReferenceFlags = 0x4C; // PulseTestEnumFlags_t
}

public static partial class CPulseCell_TestWaitWithAutoTracepoints {
    public const nint m_TracePrefix = 0xD8; // CUtlString
    public const nint m_WakeResume = 0xE0; // CPulse_ResumePoint
}

public static partial class CPulseCell_TestWaitWithCursorState {
    public const nint m_WakeResume = 0xD8; // CPulse_ResumePoint
    public const nint m_WakeFail = 0x120; // CPulse_ResumePoint
}

public static partial class CPulseCell_TestWaitWithCursorState__CursorState_t {
    public const nint flWaitValue = 0x0; // float32
    public const nint bFail = 0x4; // bool
    public const nint m_hSelfCursor = 0x8; // HYieldedCursor
    public const nint m_hSelfCellInstanceUntyped = 0x14; // HPulseCellBase
    public const nint m_hSelfCellInstance = 0x1C; // HPulseCell<CPulseCell_TestWaitWithCursorState>
}

public static partial class CPulseCell_TestWaitWithCursorState__InstanceState_t {
    public const nint m_nDummy = 0x0; // int32
}

public static partial class CPulseCell_TestYieldForever {
}

public static partial class CPulseCell_TestYieldWithObservables {
    public const nint m_flWatchForFloatValue = 0xD8; // float32
    public const nint m_LiveFloatValue = 0xE0; // CPulseObservableExpression<float32>
    public const nint m_WatchForStringValue = 0x158; // CUtlString
    public const nint m_LiveStringValue = 0x160; // CPulseObservableExpression<CUtlString>
    public const nint m_WakeResume = 0x1D8; // CPulse_ResumePoint
}

public static partial class CPulseCell_Test_MultiInflow_NoDefault {
}

public static partial class CPulseCell_Test_MultiInflow_WithDefault {
}

public static partial class CPulseCell_Test_MultiOutflow_WithParams {
    public const nint m_Out1 = 0x48; // SignatureOutflow_Continue
    public const nint m_Out2 = 0x90; // SignatureOutflow_Continue
}

public static partial class CPulseCell_Test_MultiOutflow_WithParams_Yielding {
    public const nint m_Out1 = 0xD8; // SignatureOutflow_Continue
    public const nint m_AsyncChild1 = 0x120; // SignatureOutflow_Continue
    public const nint m_AsyncChild2 = 0x168; // SignatureOutflow_Continue
    public const nint m_YieldResume1 = 0x1B0; // SignatureOutflow_Resume
    public const nint m_YieldResume2 = 0x1F8; // SignatureOutflow_Resume
}

public static partial class CPulseCell_Test_MultiOutflow_WithParams_Yielding__CursorState_t {
    public const nint nTestStep = 0x0; // int32
}

public static partial class CPulseCell_Test_NoInflow {
}

public static partial class CPulseCell_Timeline {
    public const nint m_TimelineEvents = 0xD8; // CUtlVector<CPulseCell_Timeline::TimelineEvent_t>
    public const nint m_bWaitForChildOutflows = 0xF0; // bool
    public const nint m_OnFinished = 0xF8; // CPulse_ResumePoint
}

public static partial class CPulseCell_Timeline__TimelineEvent_t {
    public const nint m_flTimeFromPrevious = 0x0; // float32
    public const nint m_EventOutflow = 0x8; // CPulse_OutflowConnection
}

public static partial class CPulseCell_Unknown {
    public const nint m_UnknownKeys = 0x48; // KeyValues3
}

public static partial class CPulseCell_Val_TestDomainFindEntityByName {
}

public static partial class CPulseCell_Val_TestDomainGetEntityName {
}

public static partial class CPulseCell_Value_Curve {
    public const nint m_Curve = 0x48; // CPiecewiseCurve
}

public static partial class CPulseCell_Value_Gradient {
    public const nint m_Gradient = 0x48; // CColorGradient
}

public static partial class CPulseCell_Value_RandomFloat {
}

public static partial class CPulseCell_Value_RandomInt {
}

public static partial class CPulseCell_Value_TestValue50 {
}

public static partial class CPulseCell_WaitForCursorsWithTag {
    public const nint m_bTagSelfWhenComplete = 0x128; // bool
    public const nint m_nDesiredKillPriority = 0x12C; // PulseCursorCancelPriority_t
}

public static partial class CPulseCell_WaitForCursorsWithTagBase {
    public const nint m_nCursorsAllowedToWait = 0xD8; // int32
    public const nint m_WaitComplete = 0xE0; // CPulse_ResumePoint
}

public static partial class CPulseCell_WaitForObservable {
    public const nint m_Condition = 0xD8; // CPulseObservableExpression<bool>
    public const nint m_OnTrue = 0x150; // CPulse_ResumePoint
}

public static partial class CPulseCursorFuncs {
}

public static partial class CPulseEnumlib {
}

public static partial class CPulseExecCursor {
}

public static partial class CPulseGraphDef {
    public const nint m_DomainIdentifier = 0x8; // PulseSymbol_t
    public const nint m_DomainSubType = 0x18; // CPulseValueFullType
    public const nint m_ParentMapName = 0x30; // PulseSymbol_t
    public const nint m_ParentXmlName = 0x40; // PulseSymbol_t
    public const nint m_Chunks = 0x50; // CUtlVector<CPulse_Chunk*>
    public const nint m_Cells = 0x68; // CUtlVector<CPulseCell_Base*>
    public const nint m_Vars = 0x80; // CUtlVector<CPulse_Variable>
    public const nint m_PublicOutputs = 0x98; // CUtlVector<CPulse_PublicOutput>
    public const nint m_InvokeBindings = 0xB0; // CUtlVector<CPulse_InvokeBinding*>
    public const nint m_CallInfos = 0xC8; // CUtlVector<CPulse_CallInfo*>
    public const nint m_Constants = 0xE0; // CUtlVector<CPulse_Constant>
    public const nint m_DomainValues = 0xF8; // CUtlVector<CPulse_DomainValue>
    public const nint m_BlackboardReferences = 0x110; // CUtlVector<CPulse_BlackboardReference>
    public const nint m_OutputConnections = 0x128; // CUtlVector<CPulse_OutputConnection*>
}

public static partial class CPulseGraphInstance_TestDomain {
    public const nint m_bIsRunningUnitTests = 0x128; // bool
    public const nint m_bExplicitTimeStepping = 0x129; // bool
    public const nint m_bExpectingToDestroyWithYieldedCursors = 0x12A; // bool
    public const nint m_bQuietTracepoints = 0x12B; // bool
    public const nint m_bExpectingCursorTerminatedDueToMaxInstructions = 0x12C; // bool
    public const nint m_nCursorsTerminatedDueToMaxInstructions = 0x130; // int32
    public const nint m_nNextValidateIndex = 0x134; // int32
    public const nint m_Tracepoints = 0x138; // CUtlVector<CUtlString>
    public const nint m_bTestYesOrNoPath = 0x150; // bool
}

public static partial class CPulseGraphInstance_TestDomain_Derived {
    public const nint m_nInstanceValueX = 0x158; // int32
}

public static partial class CPulseGraphInstance_TestDomain_FakeEntityOwner {
}

public static partial class CPulseGraphInstance_TestDomain_UseReadOnlyBlackboardView {
}

public static partial class CPulseGraphInstance_TurtleGraphics {
}

public static partial class CPulseMathlib {
}

public static partial class CPulseStringlib {
}

public static partial class CPulseTestFuncs_LibraryA {
}

public static partial class CPulseTestScriptLib {
}

public static partial class CPulseTurtleGraphicsCursor {
    public const nint m_Color = 0xD8; // Color
    public const nint m_vPos = 0xDC; // Vector2D
    public const nint m_flHeadingDeg = 0xE4; // float32
    public const nint m_bPenUp = 0xE8; // bool
}

public static partial class CPulse_BlackboardReference {
    public const nint m_hBlackboardResource = 0x0; // CStrongHandle<InfoForResourceTypeIPulseGraphDef>
    public const nint m_BlackboardResource = 0x8; // PulseSymbol_t
    public const nint m_nNodeID = 0x18; // PulseDocNodeID_t
    public const nint m_NodeName = 0x20; // CGlobalSymbol
}

public static partial class CPulse_CallInfo {
    public const nint m_PortName = 0x0; // PulseSymbol_t
    public const nint m_nEditorNodeID = 0x10; // PulseDocNodeID_t
    public const nint m_RegisterMap = 0x18; // PulseRegisterMap_t
    public const nint m_CallMethodID = 0x48; // PulseDocNodeID_t
    public const nint m_nSrcChunk = 0x4C; // PulseRuntimeChunkIndex_t
    public const nint m_nSrcInstruction = 0x50; // int32
}

public static partial class CPulse_InvokeBinding {
    public const nint m_RegisterMap = 0x0; // PulseRegisterMap_t
    public const nint m_FuncName = 0x30; // PulseSymbol_t
    public const nint m_nCellIndex = 0x40; // PulseRuntimeCellIndex_t
    public const nint m_nSrcChunk = 0x44; // PulseRuntimeChunkIndex_t
    public const nint m_nSrcInstruction = 0x48; // int32
}

public static partial class CPulse_OutflowConnection {
    public const nint m_SourceOutflowName = 0x0; // PulseSymbol_t
    public const nint m_nDestChunk = 0x10; // PulseRuntimeChunkIndex_t
    public const nint m_nInstruction = 0x14; // int32
    public const nint m_OutflowRegisterMap = 0x18; // PulseRegisterMap_t
}

public static partial class CPulse_ResumePoint {
}

public static partial class CTestDomainDerived_Cursor {
    public const nint m_nCursorValueA = 0xD8; // int32
    public const nint m_nCursorValueB = 0xDC; // int32
}

public static partial class FakeEntityDerivedA_tAPI {
}

public static partial class FakeEntityDerivedB_tAPI {
}

public static partial class FakeEntity_tAPI {
}

public static partial class OutflowWithRequirements_t {
    public const nint m_Connection = 0x0; // CPulse_OutflowConnection
    public const nint m_DestinationFlowNodeID = 0x48; // PulseDocNodeID_t
    public const nint m_RequirementNodeIDs = 0x50; // CUtlVector<PulseDocNodeID_t>
    public const nint m_nCursorStateBlockIndex = 0x68; // CUtlVector<int32>
}

public static partial class PulseNodeDynamicOutflows_t {
    public const nint m_Outflows = 0x0; // CUtlVector<PulseNodeDynamicOutflows_t::DynamicOutflow_t>
}

public static partial class PulseNodeDynamicOutflows_t__DynamicOutflow_t {
    public const nint m_OutflowID = 0x0; // CGlobalSymbol
    public const nint m_Connection = 0x8; // CPulse_OutflowConnection
}

public static partial class PulseSelectorOutflowList_t {
    public const nint m_Outflows = 0x0; // CUtlVector<OutflowWithRequirements_t>
}

public static partial class SignatureOutflow_Continue {
}

public static partial class SignatureOutflow_Resume {
}

public static partial class TestComponent_t {
    public const nint m_ComponentData = 0x8; // CUtlString
}

public static partial class TestComponent_tAPI {
}

public enum PulseBestOutflowRules_t : int {
    SORT_BY_NUMBER_OF_VALID_CRITERIA = 0,
    SORT_BY_OUTFLOW_INDEX = 1,
}

public enum PulseCursorCancelPriority_t : int {
    None = 0,
    CancelOnSucceeded = 1,
    SoftCancel = 2,
    HardCancel = 3,
}

public enum PulseCursorWakePriority_t : int {
    WakeElegantly = 0,
    WakeImmediate = 1,
}

public enum PulseMethodCallMode_t : int {
    SYNC_WAIT_FOR_COMPLETION = 0,
    ASYNC_FIRE_AND_FORGET = 1,
}

public enum PulseTestEnumColor_t : int {
    BLACK = 0,
    WHITE = 1,
    RED = 2,
    GREEN = 3,
    BLUE = 4,
}

public enum PulseTestEnumFlagsAlt_t : int {
    NONE = 0,
    FIRST = 1,
}

public enum PulseTestEnumFlags_t : int {
    NONE = 0,
    FIRST = 1,
    SECOND = 2,
    THIRD = 4,
}

public enum PulseTestEnumShape_t : int {
    CIRCLE = 100,
    SQUARE = 200,
    TRIANGLE = 300,
}

