// Generated by CS2Dumper — 2026-07-17T15:19:48Z
// Module: pulse_system.dll
#pragma once
#include <cstddef>
#include <cstdint>

namespace cs2_dumper::schemas::pulse_system_dll {

    // CBasePulseGraphInstance
    namespace CBasePulseGraphInstance {
    }

    // CPulseArraylib
    namespace CPulseArraylib {
    }

    // CPulseCell_Base
    namespace CPulseCell_Base {
        constexpr std::ptrdiff_t m_nEditorNodeID = 0x8; // PulseDocNodeID_t
    }

    // CPulseCell_BaseFlow
    namespace CPulseCell_BaseFlow {
    }

    // CPulseCell_BaseLerp
    namespace CPulseCell_BaseLerp {
        constexpr std::ptrdiff_t m_WakeResume = 0xD8; // CPulse_ResumePoint
    }

    // CPulseCell_BaseLerp::CursorState_t
    namespace CPulseCell_BaseLerp__CursorState_t {
        constexpr std::ptrdiff_t m_StartTime = 0x0; // GameTime_t
        constexpr std::ptrdiff_t m_EndTime = 0x4; // GameTime_t
    }

    // CPulseCell_BaseRequirement
    namespace CPulseCell_BaseRequirement {
    }

    // CPulseCell_BaseState
    namespace CPulseCell_BaseState {
    }

    // CPulseCell_BaseValue
    namespace CPulseCell_BaseValue {
    }

    // CPulseCell_BaseYieldingInflow
    namespace CPulseCell_BaseYieldingInflow {
        constexpr std::ptrdiff_t m_BaseFlow_OnAfterCancel = 0x48; // CPulse_ResumePoint
        constexpr std::ptrdiff_t m_BaseFlow_WhileActive = 0x90; // CPulse_ResumePoint
    }

    // CPulseCell_BooleanSwitchState
    namespace CPulseCell_BooleanSwitchState {
        constexpr std::ptrdiff_t m_Condition = 0xD8; // CPulseObservableExpression<bool>
        constexpr std::ptrdiff_t m_WhenTrue = 0x150; // CPulse_OutflowConnection
        constexpr std::ptrdiff_t m_WhenFalse = 0x198; // CPulse_OutflowConnection
    }

    // CPulseCell_CursorQueue
    namespace CPulseCell_CursorQueue {
        constexpr std::ptrdiff_t m_nCursorsAllowedToRunParallel = 0x128; // int32
    }

    // CPulseCell_ExampleCriteria
    namespace CPulseCell_ExampleCriteria {
    }

    // CPulseCell_ExampleCriteria::Criteria_t
    namespace CPulseCell_ExampleCriteria__Criteria_t {
        constexpr std::ptrdiff_t m_flFloatValue1 = 0x0; // float32
        constexpr std::ptrdiff_t m_flFloatValue2 = 0x4; // float32
        constexpr std::ptrdiff_t m_bMyBool = 0x8; // bool
    }

    // CPulseCell_ExampleSelector
    namespace CPulseCell_ExampleSelector {
        constexpr std::ptrdiff_t m_OutflowList = 0x48; // PulseSelectorOutflowList_t
    }

    // CPulseCell_FireCursors
    namespace CPulseCell_FireCursors {
        constexpr std::ptrdiff_t m_Outflows = 0xD8; // CUtlVector<CPulse_OutflowConnection>
        constexpr std::ptrdiff_t m_bWaitForChildOutflows = 0xF0; // bool
        constexpr std::ptrdiff_t m_OnFinished = 0xF8; // CPulse_ResumePoint
    }

    // CPulseCell_Inflow_BaseEntrypoint
    namespace CPulseCell_Inflow_BaseEntrypoint {
        constexpr std::ptrdiff_t m_EntryChunk = 0x48; // PulseRuntimeChunkIndex_t
        constexpr std::ptrdiff_t m_RegisterMap = 0x50; // PulseRegisterMap_t
    }

    // CPulseCell_Inflow_EntOutputHandler
    namespace CPulseCell_Inflow_EntOutputHandler {
        constexpr std::ptrdiff_t m_SourceEntity = 0x80; // PulseSymbol_t
        constexpr std::ptrdiff_t m_SourceOutput = 0x90; // PulseSymbol_t
        constexpr std::ptrdiff_t m_ExpectedParamType = 0xA0; // CPulseValueFullType
    }

    // CPulseCell_Inflow_EventHandler
    namespace CPulseCell_Inflow_EventHandler {
        constexpr std::ptrdiff_t m_EventName = 0x80; // PulseSymbol_t
    }

    // CPulseCell_Inflow_GraphHook
    namespace CPulseCell_Inflow_GraphHook {
        constexpr std::ptrdiff_t m_HookName = 0x80; // PulseSymbol_t
    }

    // CPulseCell_Inflow_Method
    namespace CPulseCell_Inflow_Method {
        constexpr std::ptrdiff_t m_MethodName = 0x80; // PulseSymbol_t
        constexpr std::ptrdiff_t m_Description = 0x90; // CUtlString
        constexpr std::ptrdiff_t m_bIsPublic = 0x98; // bool
        constexpr std::ptrdiff_t m_ReturnType = 0xA0; // CPulseValueFullType
        constexpr std::ptrdiff_t m_Args = 0xB8; // CUtlLeanVector<CPulseRuntimeMethodArg>
    }

    // CPulseCell_Inflow_ObservableVariableListener
    namespace CPulseCell_Inflow_ObservableVariableListener {
        constexpr std::ptrdiff_t m_nBlackboardReference = 0x80; // PulseRuntimeBlackboardReferenceIndex_t
        constexpr std::ptrdiff_t m_bSelfReference = 0x82; // bool
    }

    // CPulseCell_Inflow_Wait
    namespace CPulseCell_Inflow_Wait {
        constexpr std::ptrdiff_t m_WakeResume = 0xD8; // CPulse_ResumePoint
    }

    // CPulseCell_Inflow_Yield
    namespace CPulseCell_Inflow_Yield {
        constexpr std::ptrdiff_t m_UnyieldResume = 0xD8; // CPulse_ResumePoint
    }

    // CPulseCell_InlineNodeSkipSelector
    namespace CPulseCell_InlineNodeSkipSelector {
        constexpr std::ptrdiff_t m_nFlowNodeID = 0x48; // PulseDocNodeID_t
        constexpr std::ptrdiff_t m_bAnd = 0x4C; // bool
        constexpr std::ptrdiff_t m_PassOutflow = 0x50; // PulseSelectorOutflowList_t
        constexpr std::ptrdiff_t m_FailOutflow = 0x68; // CPulse_OutflowConnection
    }

    // CPulseCell_IntervalTimer
    namespace CPulseCell_IntervalTimer {
        constexpr std::ptrdiff_t m_Completed = 0xD8; // CPulse_ResumePoint
        constexpr std::ptrdiff_t m_OnInterval = 0x120; // SignatureOutflow_Continue
    }

    // CPulseCell_IntervalTimer::CursorState_t
    namespace CPulseCell_IntervalTimer__CursorState_t {
        constexpr std::ptrdiff_t m_StartTime = 0x0; // GameTime_t
        constexpr std::ptrdiff_t m_EndTime = 0x4; // GameTime_t
        constexpr std::ptrdiff_t m_flWaitInterval = 0x8; // float32
        constexpr std::ptrdiff_t m_flWaitIntervalHigh = 0xC; // float32
        constexpr std::ptrdiff_t m_bCompleteOnNextWake = 0x10; // bool
    }

    // CPulseCell_IsRequirementValid
    namespace CPulseCell_IsRequirementValid {
    }

    // CPulseCell_IsRequirementValid::Criteria_t
    namespace CPulseCell_IsRequirementValid__Criteria_t {
        constexpr std::ptrdiff_t m_bIsValid = 0x0; // bool
    }

    // CPulseCell_LimitCount
    namespace CPulseCell_LimitCount {
        constexpr std::ptrdiff_t m_nLimitCount = 0x48; // int32
    }

    // CPulseCell_LimitCount::Criteria_t
    namespace CPulseCell_LimitCount__Criteria_t {
        constexpr std::ptrdiff_t m_bLimitCountPasses = 0x0; // bool
    }

    // CPulseCell_LimitCount::InstanceState_t
    namespace CPulseCell_LimitCount__InstanceState_t {
        constexpr std::ptrdiff_t m_nCurrentCount = 0x0; // int32
    }

    // CPulseCell_Outflow_CycleOrdered
    namespace CPulseCell_Outflow_CycleOrdered {
        constexpr std::ptrdiff_t m_Outputs = 0x48; // CUtlVector<CPulse_OutflowConnection>
    }

    // CPulseCell_Outflow_CycleOrdered::InstanceState_t
    namespace CPulseCell_Outflow_CycleOrdered__InstanceState_t {
        constexpr std::ptrdiff_t m_nNextIndex = 0x0; // int32
    }

    // CPulseCell_Outflow_CycleRandom
    namespace CPulseCell_Outflow_CycleRandom {
        constexpr std::ptrdiff_t m_Outputs = 0x48; // CUtlVector<CPulse_OutflowConnection>
    }

    // CPulseCell_Outflow_CycleShuffled
    namespace CPulseCell_Outflow_CycleShuffled {
        constexpr std::ptrdiff_t m_Outputs = 0x48; // CUtlVector<CPulse_OutflowConnection>
    }

    // CPulseCell_Outflow_CycleShuffled::InstanceState_t
    namespace CPulseCell_Outflow_CycleShuffled__InstanceState_t {
        constexpr std::ptrdiff_t m_Shuffle = 0x0; // CUtlVectorFixedGrowable<uint8,8>
        constexpr std::ptrdiff_t m_nNextShuffle = 0x20; // int32
    }

    // CPulseCell_Outflow_TestExplicitYesNo
    namespace CPulseCell_Outflow_TestExplicitYesNo {
        constexpr std::ptrdiff_t m_Yes = 0x48; // CPulse_OutflowConnection
        constexpr std::ptrdiff_t m_No = 0x90; // CPulse_OutflowConnection
    }

    // CPulseCell_Outflow_TestRandomYesNo
    namespace CPulseCell_Outflow_TestRandomYesNo {
        constexpr std::ptrdiff_t m_Yes = 0x48; // CPulse_OutflowConnection
        constexpr std::ptrdiff_t m_No = 0x90; // CPulse_OutflowConnection
    }

    // CPulseCell_PickBestOutflowSelector
    namespace CPulseCell_PickBestOutflowSelector {
        constexpr std::ptrdiff_t m_nCheckType = 0x48; // PulseBestOutflowRules_t
        constexpr std::ptrdiff_t m_OutflowList = 0x50; // PulseSelectorOutflowList_t
    }

    // CPulseCell_Step_CallExternalMethod
    namespace CPulseCell_Step_CallExternalMethod {
        constexpr std::ptrdiff_t m_MethodName = 0xD8; // PulseSymbol_t
        constexpr std::ptrdiff_t m_nBlackboardIndex = 0xE8; // PulseRuntimeBlackboardReferenceIndex_t
        constexpr std::ptrdiff_t m_ExpectedArgs = 0xF0; // CUtlLeanVector<CPulseRuntimeMethodArg>
        constexpr std::ptrdiff_t m_nAsyncCallMode = 0x100; // PulseMethodCallMode_t
        constexpr std::ptrdiff_t m_OnFinished = 0x108; // CPulse_ResumePoint
    }

    // CPulseCell_Step_DebugLog
    namespace CPulseCell_Step_DebugLog {
    }

    // CPulseCell_Step_PublicOutput
    namespace CPulseCell_Step_PublicOutput {
        constexpr std::ptrdiff_t m_OutputIndex = 0x48; // PulseRuntimeOutputIndex_t
    }

    // CPulseCell_Step_TestDomainCreateFakeEntity
    namespace CPulseCell_Step_TestDomainCreateFakeEntity {
    }

    // CPulseCell_Step_TestDomainDestroyFakeEntity
    namespace CPulseCell_Step_TestDomainDestroyFakeEntity {
    }

    // CPulseCell_Step_TestDomainEntFire
    namespace CPulseCell_Step_TestDomainEntFire {
        constexpr std::ptrdiff_t m_Input = 0x48; // CUtlString
    }

    // CPulseCell_Step_TestDomainTracepoint
    namespace CPulseCell_Step_TestDomainTracepoint {
    }

    // CPulseCell_TestEnums
    namespace CPulseCell_TestEnums {
        constexpr std::ptrdiff_t m_nReferenceColor = 0x48; // PulseTestEnumColor_t
        constexpr std::ptrdiff_t m_nReferenceFlags = 0x4C; // PulseTestEnumFlags_t
    }

    // CPulseCell_TestWaitWithAutoTracepoints
    namespace CPulseCell_TestWaitWithAutoTracepoints {
        constexpr std::ptrdiff_t m_TracePrefix = 0xD8; // CUtlString
        constexpr std::ptrdiff_t m_WakeResume = 0xE0; // CPulse_ResumePoint
    }

    // CPulseCell_TestWaitWithCursorState
    namespace CPulseCell_TestWaitWithCursorState {
        constexpr std::ptrdiff_t m_WakeResume = 0xD8; // CPulse_ResumePoint
        constexpr std::ptrdiff_t m_WakeFail = 0x120; // CPulse_ResumePoint
    }

    // CPulseCell_TestWaitWithCursorState::CursorState_t
    namespace CPulseCell_TestWaitWithCursorState__CursorState_t {
        constexpr std::ptrdiff_t flWaitValue = 0x0; // float32
        constexpr std::ptrdiff_t bFail = 0x4; // bool
        constexpr std::ptrdiff_t m_hSelfCursor = 0x8; // HYieldedCursor
        constexpr std::ptrdiff_t m_hSelfCellInstanceUntyped = 0x14; // HPulseCellBase
        constexpr std::ptrdiff_t m_hSelfCellInstance = 0x1C; // HPulseCell<CPulseCell_TestWaitWithCursorState>
    }

    // CPulseCell_TestWaitWithCursorState::InstanceState_t
    namespace CPulseCell_TestWaitWithCursorState__InstanceState_t {
        constexpr std::ptrdiff_t m_nDummy = 0x0; // int32
    }

    // CPulseCell_TestYieldForever
    namespace CPulseCell_TestYieldForever {
    }

    // CPulseCell_TestYieldWithObservables
    namespace CPulseCell_TestYieldWithObservables {
        constexpr std::ptrdiff_t m_flWatchForFloatValue = 0xD8; // float32
        constexpr std::ptrdiff_t m_LiveFloatValue = 0xE0; // CPulseObservableExpression<float32>
        constexpr std::ptrdiff_t m_WatchForStringValue = 0x158; // CUtlString
        constexpr std::ptrdiff_t m_LiveStringValue = 0x160; // CPulseObservableExpression<CUtlString>
        constexpr std::ptrdiff_t m_WakeResume = 0x1D8; // CPulse_ResumePoint
    }

    // CPulseCell_Test_MultiInflow_NoDefault
    namespace CPulseCell_Test_MultiInflow_NoDefault {
    }

    // CPulseCell_Test_MultiInflow_WithDefault
    namespace CPulseCell_Test_MultiInflow_WithDefault {
    }

    // CPulseCell_Test_MultiOutflow_WithParams
    namespace CPulseCell_Test_MultiOutflow_WithParams {
        constexpr std::ptrdiff_t m_Out1 = 0x48; // SignatureOutflow_Continue
        constexpr std::ptrdiff_t m_Out2 = 0x90; // SignatureOutflow_Continue
    }

    // CPulseCell_Test_MultiOutflow_WithParams_Yielding
    namespace CPulseCell_Test_MultiOutflow_WithParams_Yielding {
        constexpr std::ptrdiff_t m_Out1 = 0xD8; // SignatureOutflow_Continue
        constexpr std::ptrdiff_t m_AsyncChild1 = 0x120; // SignatureOutflow_Continue
        constexpr std::ptrdiff_t m_AsyncChild2 = 0x168; // SignatureOutflow_Continue
        constexpr std::ptrdiff_t m_YieldResume1 = 0x1B0; // SignatureOutflow_Resume
        constexpr std::ptrdiff_t m_YieldResume2 = 0x1F8; // SignatureOutflow_Resume
    }

    // CPulseCell_Test_MultiOutflow_WithParams_Yielding::CursorState_t
    namespace CPulseCell_Test_MultiOutflow_WithParams_Yielding__CursorState_t {
        constexpr std::ptrdiff_t nTestStep = 0x0; // int32
    }

    // CPulseCell_Test_NoInflow
    namespace CPulseCell_Test_NoInflow {
    }

    // CPulseCell_Timeline
    namespace CPulseCell_Timeline {
        constexpr std::ptrdiff_t m_TimelineEvents = 0xD8; // CUtlVector<CPulseCell_Timeline::TimelineEvent_t>
        constexpr std::ptrdiff_t m_bWaitForChildOutflows = 0xF0; // bool
        constexpr std::ptrdiff_t m_OnFinished = 0xF8; // CPulse_ResumePoint
    }

    // CPulseCell_Timeline::TimelineEvent_t
    namespace CPulseCell_Timeline__TimelineEvent_t {
        constexpr std::ptrdiff_t m_flTimeFromPrevious = 0x0; // float32
        constexpr std::ptrdiff_t m_EventOutflow = 0x8; // CPulse_OutflowConnection
    }

    // CPulseCell_Unknown
    namespace CPulseCell_Unknown {
        constexpr std::ptrdiff_t m_UnknownKeys = 0x48; // KeyValues3
    }

    // CPulseCell_Val_TestDomainFindEntityByName
    namespace CPulseCell_Val_TestDomainFindEntityByName {
    }

    // CPulseCell_Val_TestDomainGetEntityName
    namespace CPulseCell_Val_TestDomainGetEntityName {
    }

    // CPulseCell_Value_Curve
    namespace CPulseCell_Value_Curve {
        constexpr std::ptrdiff_t m_Curve = 0x48; // CPiecewiseCurve
    }

    // CPulseCell_Value_Gradient
    namespace CPulseCell_Value_Gradient {
        constexpr std::ptrdiff_t m_Gradient = 0x48; // CColorGradient
    }

    // CPulseCell_Value_RandomFloat
    namespace CPulseCell_Value_RandomFloat {
    }

    // CPulseCell_Value_RandomInt
    namespace CPulseCell_Value_RandomInt {
    }

    // CPulseCell_Value_TestValue50
    namespace CPulseCell_Value_TestValue50 {
    }

    // CPulseCell_WaitForCursorsWithTag
    namespace CPulseCell_WaitForCursorsWithTag {
        constexpr std::ptrdiff_t m_bTagSelfWhenComplete = 0x128; // bool
        constexpr std::ptrdiff_t m_nDesiredKillPriority = 0x12C; // PulseCursorCancelPriority_t
    }

    // CPulseCell_WaitForCursorsWithTagBase
    namespace CPulseCell_WaitForCursorsWithTagBase {
        constexpr std::ptrdiff_t m_nCursorsAllowedToWait = 0xD8; // int32
        constexpr std::ptrdiff_t m_WaitComplete = 0xE0; // CPulse_ResumePoint
    }

    // CPulseCell_WaitForObservable
    namespace CPulseCell_WaitForObservable {
        constexpr std::ptrdiff_t m_Condition = 0xD8; // CPulseObservableExpression<bool>
        constexpr std::ptrdiff_t m_OnTrue = 0x150; // CPulse_ResumePoint
    }

    // CPulseCursorFuncs
    namespace CPulseCursorFuncs {
    }

    // CPulseEnumlib
    namespace CPulseEnumlib {
    }

    // CPulseExecCursor
    namespace CPulseExecCursor {
    }

    // CPulseGraphDef
    namespace CPulseGraphDef {
        constexpr std::ptrdiff_t m_DomainIdentifier = 0x8; // PulseSymbol_t
        constexpr std::ptrdiff_t m_DomainSubType = 0x18; // CPulseValueFullType
        constexpr std::ptrdiff_t m_ParentMapName = 0x30; // PulseSymbol_t
        constexpr std::ptrdiff_t m_ParentXmlName = 0x40; // PulseSymbol_t
        constexpr std::ptrdiff_t m_Chunks = 0x50; // CUtlVector<CPulse_Chunk*>
        constexpr std::ptrdiff_t m_Cells = 0x68; // CUtlVector<CPulseCell_Base*>
        constexpr std::ptrdiff_t m_Vars = 0x80; // CUtlVector<CPulse_Variable>
        constexpr std::ptrdiff_t m_PublicOutputs = 0x98; // CUtlVector<CPulse_PublicOutput>
        constexpr std::ptrdiff_t m_InvokeBindings = 0xB0; // CUtlVector<CPulse_InvokeBinding*>
        constexpr std::ptrdiff_t m_CallInfos = 0xC8; // CUtlVector<CPulse_CallInfo*>
        constexpr std::ptrdiff_t m_Constants = 0xE0; // CUtlVector<CPulse_Constant>
        constexpr std::ptrdiff_t m_DomainValues = 0xF8; // CUtlVector<CPulse_DomainValue>
        constexpr std::ptrdiff_t m_BlackboardReferences = 0x110; // CUtlVector<CPulse_BlackboardReference>
        constexpr std::ptrdiff_t m_OutputConnections = 0x128; // CUtlVector<CPulse_OutputConnection*>
    }

    // CPulseGraphInstance_TestDomain
    namespace CPulseGraphInstance_TestDomain {
        constexpr std::ptrdiff_t m_bIsRunningUnitTests = 0x128; // bool
        constexpr std::ptrdiff_t m_bExplicitTimeStepping = 0x129; // bool
        constexpr std::ptrdiff_t m_bExpectingToDestroyWithYieldedCursors = 0x12A; // bool
        constexpr std::ptrdiff_t m_bQuietTracepoints = 0x12B; // bool
        constexpr std::ptrdiff_t m_bExpectingCursorTerminatedDueToMaxInstructions = 0x12C; // bool
        constexpr std::ptrdiff_t m_nCursorsTerminatedDueToMaxInstructions = 0x130; // int32
        constexpr std::ptrdiff_t m_nNextValidateIndex = 0x134; // int32
        constexpr std::ptrdiff_t m_Tracepoints = 0x138; // CUtlVector<CUtlString>
        constexpr std::ptrdiff_t m_bTestYesOrNoPath = 0x150; // bool
    }

    // CPulseGraphInstance_TestDomain_Derived
    namespace CPulseGraphInstance_TestDomain_Derived {
        constexpr std::ptrdiff_t m_nInstanceValueX = 0x158; // int32
    }

    // CPulseGraphInstance_TestDomain_FakeEntityOwner
    namespace CPulseGraphInstance_TestDomain_FakeEntityOwner {
    }

    // CPulseGraphInstance_TestDomain_UseReadOnlyBlackboardView
    namespace CPulseGraphInstance_TestDomain_UseReadOnlyBlackboardView {
    }

    // CPulseGraphInstance_TurtleGraphics
    namespace CPulseGraphInstance_TurtleGraphics {
    }

    // CPulseMathlib
    namespace CPulseMathlib {
    }

    // CPulseStringlib
    namespace CPulseStringlib {
    }

    // CPulseTestFuncs_LibraryA
    namespace CPulseTestFuncs_LibraryA {
    }

    // CPulseTestScriptLib
    namespace CPulseTestScriptLib {
    }

    // CPulseTurtleGraphicsCursor
    namespace CPulseTurtleGraphicsCursor {
        constexpr std::ptrdiff_t m_Color = 0xD8; // Color
        constexpr std::ptrdiff_t m_vPos = 0xDC; // Vector2D
        constexpr std::ptrdiff_t m_flHeadingDeg = 0xE4; // float32
        constexpr std::ptrdiff_t m_bPenUp = 0xE8; // bool
    }

    // CPulse_BlackboardReference
    namespace CPulse_BlackboardReference {
        constexpr std::ptrdiff_t m_hBlackboardResource = 0x0; // CStrongHandle<InfoForResourceTypeIPulseGraphDef>
        constexpr std::ptrdiff_t m_BlackboardResource = 0x8; // PulseSymbol_t
        constexpr std::ptrdiff_t m_nNodeID = 0x18; // PulseDocNodeID_t
        constexpr std::ptrdiff_t m_NodeName = 0x20; // CGlobalSymbol
    }

    // CPulse_CallInfo
    namespace CPulse_CallInfo {
        constexpr std::ptrdiff_t m_PortName = 0x0; // PulseSymbol_t
        constexpr std::ptrdiff_t m_nEditorNodeID = 0x10; // PulseDocNodeID_t
        constexpr std::ptrdiff_t m_RegisterMap = 0x18; // PulseRegisterMap_t
        constexpr std::ptrdiff_t m_CallMethodID = 0x48; // PulseDocNodeID_t
        constexpr std::ptrdiff_t m_nSrcChunk = 0x4C; // PulseRuntimeChunkIndex_t
        constexpr std::ptrdiff_t m_nSrcInstruction = 0x50; // int32
    }

    // CPulse_InvokeBinding
    namespace CPulse_InvokeBinding {
        constexpr std::ptrdiff_t m_RegisterMap = 0x0; // PulseRegisterMap_t
        constexpr std::ptrdiff_t m_FuncName = 0x30; // PulseSymbol_t
        constexpr std::ptrdiff_t m_nCellIndex = 0x40; // PulseRuntimeCellIndex_t
        constexpr std::ptrdiff_t m_nSrcChunk = 0x44; // PulseRuntimeChunkIndex_t
        constexpr std::ptrdiff_t m_nSrcInstruction = 0x48; // int32
    }

    // CPulse_OutflowConnection
    namespace CPulse_OutflowConnection {
        constexpr std::ptrdiff_t m_SourceOutflowName = 0x0; // PulseSymbol_t
        constexpr std::ptrdiff_t m_nDestChunk = 0x10; // PulseRuntimeChunkIndex_t
        constexpr std::ptrdiff_t m_nInstruction = 0x14; // int32
        constexpr std::ptrdiff_t m_OutflowRegisterMap = 0x18; // PulseRegisterMap_t
    }

    // CPulse_ResumePoint
    namespace CPulse_ResumePoint {
    }

    // CTestDomainDerived_Cursor
    namespace CTestDomainDerived_Cursor {
        constexpr std::ptrdiff_t m_nCursorValueA = 0xD8; // int32
        constexpr std::ptrdiff_t m_nCursorValueB = 0xDC; // int32
    }

    // FakeEntityDerivedA_tAPI
    namespace FakeEntityDerivedA_tAPI {
    }

    // FakeEntityDerivedB_tAPI
    namespace FakeEntityDerivedB_tAPI {
    }

    // FakeEntity_tAPI
    namespace FakeEntity_tAPI {
    }

    // OutflowWithRequirements_t
    namespace OutflowWithRequirements_t {
        constexpr std::ptrdiff_t m_Connection = 0x0; // CPulse_OutflowConnection
        constexpr std::ptrdiff_t m_DestinationFlowNodeID = 0x48; // PulseDocNodeID_t
        constexpr std::ptrdiff_t m_RequirementNodeIDs = 0x50; // CUtlVector<PulseDocNodeID_t>
        constexpr std::ptrdiff_t m_nCursorStateBlockIndex = 0x68; // CUtlVector<int32>
    }

    // PulseNodeDynamicOutflows_t
    namespace PulseNodeDynamicOutflows_t {
        constexpr std::ptrdiff_t m_Outflows = 0x0; // CUtlVector<PulseNodeDynamicOutflows_t::DynamicOutflow_t>
    }

    // PulseNodeDynamicOutflows_t::DynamicOutflow_t
    namespace PulseNodeDynamicOutflows_t__DynamicOutflow_t {
        constexpr std::ptrdiff_t m_OutflowID = 0x0; // CGlobalSymbol
        constexpr std::ptrdiff_t m_Connection = 0x8; // CPulse_OutflowConnection
    }

    // PulseSelectorOutflowList_t
    namespace PulseSelectorOutflowList_t {
        constexpr std::ptrdiff_t m_Outflows = 0x0; // CUtlVector<OutflowWithRequirements_t>
    }

    // SignatureOutflow_Continue
    namespace SignatureOutflow_Continue {
    }

    // SignatureOutflow_Resume
    namespace SignatureOutflow_Resume {
    }

    // TestComponent_t
    namespace TestComponent_t {
        constexpr std::ptrdiff_t m_ComponentData = 0x8; // CUtlString
    }

    // TestComponent_tAPI
    namespace TestComponent_tAPI {
    }

    // ── Enums ────────────────────────────────────
    enum class PulseBestOutflowRules_t : int32_t {
        SORT_BY_NUMBER_OF_VALID_CRITERIA = 0,
        SORT_BY_OUTFLOW_INDEX = 1,
    };

    enum class PulseCursorCancelPriority_t : int32_t {
        None = 0,
        CancelOnSucceeded = 1,
        SoftCancel = 2,
        HardCancel = 3,
    };

    enum class PulseCursorWakePriority_t : int32_t {
        WakeElegantly = 0,
        WakeImmediate = 1,
    };

    enum class PulseMethodCallMode_t : int32_t {
        SYNC_WAIT_FOR_COMPLETION = 0,
        ASYNC_FIRE_AND_FORGET = 1,
    };

    enum class PulseTestEnumColor_t : int32_t {
        BLACK = 0,
        WHITE = 1,
        RED = 2,
        GREEN = 3,
        BLUE = 4,
    };

    enum class PulseTestEnumFlagsAlt_t : int32_t {
        NONE = 0,
        FIRST = 1,
    };

    enum class PulseTestEnumFlags_t : int32_t {
        NONE = 0,
        FIRST = 1,
        SECOND = 2,
        THIRD = 4,
    };

    enum class PulseTestEnumShape_t : int32_t {
        CIRCLE = 100,
        SQUARE = 200,
        TRIANGLE = 300,
    };

} // namespace cs2_dumper::schemas::pulse_system_dll
