// Generated by CS2Dumper — 2026-07-17T15:19:48Z
// Module: rendersystemdx11.dll
namespace CS2Dumper.Schemas;

public static partial class RenderInputLayoutField_t {
    public const nint m_pSemanticName = 0x0; // char[32]
    public const nint m_nSemanticIndex = 0x20; // int8
    public const nint m_nOffset = 0x28; // int16
    public const nint m_nSlot = 0x2A; // int8
    public const nint m_nSlotType = 0x2B; // RenderSlotType_t
    public const nint m_szShaderSemantic = 0x2C; // char[32]
}

public static partial class RsBlendStateDesc_t {
    public const nint m_srcBlendBits = 0x0; // uint32
    public const nint m_blendOpBits = 0x0; // bitfield:30
    public const nint m_bAlphaToCoverageEnable = 0x0; // bitfield:1
    public const nint m_bIndependentBlendEnable = 0x0; // bitfield:1
    public const nint m_destBlendBits = 0x4; // uint32
    public const nint m_srcBlendAlphaBits = 0x8; // uint32
    public const nint m_destBlendAlphaBits = 0xC; // uint32
    public const nint m_renderTargetWriteMaskBits = 0x10; // uint32
    public const nint m_blendOpAlphaBits = 0x18; // uint32
    public const nint m_blendEnableBits = 0x1C; // uint8
    public const nint m_srgbWriteEnableBits = 0x1D; // uint8
}

public static partial class RsDepthStencilStateDesc_t {
    public const nint m_bDepthTestEnable = 0x0; // bitfield:1
    public const nint m_bDepthWriteEnable = 0x0; // bitfield:1
    public const nint m_depthFunc = 0x0; // bitfield:4
    public const nint m_stencilState = 0x2; // RsStencilStateDesc_t
}

public static partial class RsRasterizerStateDesc_t {
    public const nint m_nFillMode = 0x0; // RsFillMode_t
    public const nint m_nCullMode = 0x1; // RsCullMode_t
    public const nint m_bDepthClipEnable = 0x2; // bool
    public const nint m_bMultisampleEnable = 0x3; // bool
    public const nint m_nDepthBias = 0x4; // int32
    public const nint m_flDepthBiasClamp = 0x8; // float32
    public const nint m_flSlopeScaledDepthBias = 0xC; // float32
}

public static partial class RsStencilStateDesc_t {
    public const nint m_frontStencilFunc = 0x0; // bitfield:4
    public const nint m_backStencilFunc = 0x0; // bitfield:4
    public const nint m_bStencilEnable = 0x0; // bitfield:1
    public const nint m_frontStencilFailOp = 0x0; // bitfield:3
    public const nint m_frontStencilDepthFailOp = 0x0; // bitfield:3
    public const nint m_frontStencilPassOp = 0x0; // bitfield:3
    public const nint m_backStencilFailOp = 0x0; // bitfield:3
    public const nint m_backStencilDepthFailOp = 0x0; // bitfield:3
    public const nint m_backStencilPassOp = 0x0; // bitfield:3
    public const nint m_nStencilReadMask = 0x4; // uint8
    public const nint m_nStencilWriteMask = 0x5; // uint8
}

public static partial class SheetSequenceIntegerId_t {
    public const nint m_Value = 0x0; // uint32
}

public static partial class VsInputSignatureElement_t {
    public const nint m_pName = 0x0; // char[64]
    public const nint m_pSemantic = 0x40; // char[64]
    public const nint m_pD3DSemanticName = 0x80; // char[64]
    public const nint m_nD3DSemanticIndex = 0xC0; // int32
}

public static partial class VsInputSignature_t {
    public const nint m_elems = 0x0; // CUtlVector<VsInputSignatureElement_t>
    public const nint m_depth_elems = 0x18; // CUtlVector<VsInputSignatureElement_t>
}

public enum InputLayoutVariation_t : byte {
    INPUT_LAYOUT_VARIATION_DEFAULT = 0,
    INPUT_LAYOUT_VARIATION_STREAM1_INSTANCEID = 1,
    INPUT_LAYOUT_VARIATION_STREAM1_INSTANCEID_MORPH_VERT_ID = 2,
    INPUT_LAYOUT_VARIATION_MAX = 3,
}

public enum RenderBufferFlags_t : int {
    RENDER_BUFFER_USAGE_NONE = 0,
    RENDER_BUFFER_USAGE_VERTEX_BUFFER = 1,
    RENDER_BUFFER_USAGE_INDEX_BUFFER = 2,
    RENDER_BUFFER_USAGE_SHADER_RESOURCE = 4,
    RENDER_BUFFER_USAGE_UNORDERED_ACCESS = 8,
    RENDER_BUFFER_BYTEADDRESS_BUFFER = 16,
    RENDER_BUFFER_STRUCTURED_BUFFER = 32,
    RENDER_BUFFER_UAV_DRAW_INDIRECT_ARGS = 256,
    RENDER_BUFFER_ACCELERATION_STRUCTURE = 512,
    RENDER_BUFFER_SHADER_BINDING_TABLE = 1024,
    RENDER_BUFFER_POOL_ALLOCATED = 2048,
    RENDER_BUFFER_USAGE_CONDITIONAL_RENDERING = 4096,
    RENDER_BUFFER_IMMOVABLE_ALLOCATION = 8192,
    RENDER_BUFFER_DYNAMIC_ZERO_COPY = 16384,
}

public enum RenderMultisampleType_t : byte {
    RENDER_MULTISAMPLE_INVALID = -1,
    RENDER_MULTISAMPLE_NONE = 0,
    RENDER_MULTISAMPLE_2X = 1,
    RENDER_MULTISAMPLE_4X = 2,
    RENDER_MULTISAMPLE_6X = 3,
    RENDER_MULTISAMPLE_8X = 4,
    RENDER_MULTISAMPLE_16X = 5,
    RENDER_MULTISAMPLE_TYPE_COUNT = 6,
}

public enum RenderPrimitiveType_t : int {
    RENDER_PRIM_POINTS = 0,
    RENDER_PRIM_LINES = 1,
    RENDER_PRIM_LINES_WITH_ADJACENCY = 2,
    RENDER_PRIM_LINE_STRIP = 3,
    RENDER_PRIM_LINE_STRIP_WITH_ADJACENCY = 4,
    RENDER_PRIM_TRIANGLES = 5,
    RENDER_PRIM_TRIANGLES_WITH_ADJACENCY = 6,
    RENDER_PRIM_TRIANGLE_STRIP = 7,
    RENDER_PRIM_TRIANGLE_STRIP_WITH_ADJACENCY = 8,
    RENDER_PRIM_INSTANCED_QUADS = 9,
    RENDER_PRIM_HETEROGENOUS = 10,
    RENDER_PRIM_COMPUTE_SHADER = 11,
    RENDER_PRIM_MESH_SHADER = 12,
    RENDER_PRIM_TYPE_COUNT = 13,
}

public enum RenderSlotType_t : byte {
    RENDER_SLOT_INVALID = -1,
    RENDER_SLOT_PER_VERTEX = 0,
    RENDER_SLOT_PER_INSTANCE = 1,
}

public enum RsComparison_t : byte {
    RS_CMP_NEVER = 0,
    RS_CMP_LESS = 1,
    RS_CMP_EQUAL = 2,
    RS_CMP_LESS_EQUAL = 3,
    RS_CMP_GREATER = 4,
    RS_CMP_NOT_EQUAL = 5,
    RS_CMP_GREATER_EQUAL = 6,
    RS_CMP_ALWAYS = 7,
    RS_CMP_FUNC_MASK = 7,
    RS_CMP_CLOSER_FARTHER_FLAG = 8,
    RS_CMP_CLOSER = 9,
    RS_CMP_CLOSER_EQUAL = 11,
    RS_CMP_FARTHER = 12,
    RS_CMP_FARTHER_EQUAL = 14,
}

public enum RsCullMode_t : byte {
    RS_CULL_NONE = 0,
    RS_CULL_BACK = 1,
    RS_CULL_FRONT = 2,
}

public enum RsFillMode_t : byte {
    RS_FILL_SOLID = 0,
    RS_FILL_WIREFRAME = 1,
}

public enum UpscalerType_t : int {
    UPSCALER_NONE = 0,
    UPSCALER_AMD_FSR2 = 1,
    UPSCALER_AMD_FSR3 = 2,
    UPSCALER_NVIDIA_DLSS = 3,
    UPSCALER_INTEL_XESS = 4,
    UPSCALER_COUNT = 5,
}

