// Generated by CS2Dumper — 2026-07-17T15:19:48Z
// Module: resourcesystem.dll
namespace CS2Dumper.Schemas;

public static partial class AABBWS_t {
    public const nint m_vMinBounds = 0x0; // VectorWS
    public const nint m_vMaxBounds = 0xC; // VectorWS
}

public static partial class AABB_t {
    public const nint m_vMinBounds = 0x0; // Vector
    public const nint m_vMaxBounds = 0xC; // Vector
}

public static partial class CFuseProgram {
    public const nint m_programBuffer = 0x0; // CUtlVector<uint8>
    public const nint m_variablesRead = 0x18; // CUtlVector<FuseVariableIndex_t>
    public const nint m_variablesWritten = 0x30; // CUtlVector<FuseVariableIndex_t>
    public const nint m_nMaxTempVarsUsed = 0x48; // int32
}

public static partial class CFuseSymbolTable {
    public const nint m_constants = 0x0; // CUtlVector<ConstantInfo_t>
    public const nint m_variables = 0x18; // CUtlVector<VariableInfo_t>
    public const nint m_functions = 0x30; // CUtlVector<FunctionInfo_t>
    public const nint m_constantMap = 0x48; // CUtlHashtable<CUtlStringToken,int32>
    public const nint m_variableMap = 0x68; // CUtlHashtable<CUtlStringToken,int32>
    public const nint m_functionMap = 0x88; // CUtlHashtable<CUtlStringToken,int32>
}

public static partial class ConstantInfo_t {
    public const nint m_name = 0x0; // CUtlString
    public const nint m_nameToken = 0x8; // CUtlStringToken
    public const nint m_flValue = 0xC; // float32
}

public static partial class FourQuaternions {
    public const nint x = 0x0; // fltx4
    public const nint y = 0x10; // fltx4
    public const nint z = 0x20; // fltx4
    public const nint w = 0x30; // fltx4
}

public static partial class FunctionInfo_t {
    public const nint m_name = 0x8; // CUtlString
    public const nint m_nameToken = 0x10; // CUtlStringToken
    public const nint m_nParamCount = 0x14; // int32
    public const nint m_nIndex = 0x18; // FuseFunctionIndex_t
    public const nint m_bIsPure = 0x1A; // bool
}

public static partial class FuseFunctionIndex_t {
    public const nint m_Value = 0x0; // uint16
}

public static partial class FuseVariableIndex_t {
    public const nint m_Value = 0x0; // uint16
}

public static partial class InfoForResourceTypeCAnimData {
}

public static partial class InfoForResourceTypeCAnimationGroup {
}

public static partial class InfoForResourceTypeCCSGOEconItem {
}

public static partial class InfoForResourceTypeCChoreoSceneResource {
}

public static partial class InfoForResourceTypeCCompositeMaterialKit {
}

public static partial class InfoForResourceTypeCDOTANovelsList {
}

public static partial class InfoForResourceTypeCDOTAPatchNotesList {
}

public static partial class InfoForResourceTypeCDotaItemDefinitionResource {
}

public static partial class InfoForResourceTypeCEntityLump {
}

public static partial class InfoForResourceTypeCGcExportableExternalData {
}

public static partial class InfoForResourceTypeCJavaScriptResource {
}

public static partial class InfoForResourceTypeCModel {
}

public static partial class InfoForResourceTypeCMorphSetData {
}

public static partial class InfoForResourceTypeCNmClip {
}

public static partial class InfoForResourceTypeCNmGraphDefinition {
}

public static partial class InfoForResourceTypeCNmSkeleton {
}

public static partial class InfoForResourceTypeCPanoramaDynamicImages {
}

public static partial class InfoForResourceTypeCPanoramaLayout {
}

public static partial class InfoForResourceTypeCPanoramaStyle {
}

public static partial class InfoForResourceTypeCPhysAggregateData {
}

public static partial class InfoForResourceTypeCPostProcessingResource {
}

public static partial class InfoForResourceTypeCRenderMesh {
}

public static partial class InfoForResourceTypeCResponseRulesList {
}

public static partial class InfoForResourceTypeCSequenceGroupData {
}

public static partial class InfoForResourceTypeCSmartProp {
}

public static partial class InfoForResourceTypeCSurfaceGraph {
}

public static partial class InfoForResourceTypeCTestResourceData {
}

public static partial class InfoForResourceTypeCTextureBase {
}

public static partial class InfoForResourceTypeCTypeScriptResource {
}

public static partial class InfoForResourceTypeCVDataItemDefs {
}

public static partial class InfoForResourceTypeCVDataResource {
}

public static partial class InfoForResourceTypeCVMixListResource {
}

public static partial class InfoForResourceTypeCVPhysXSurfacePropertiesList {
}

public static partial class InfoForResourceTypeCVSoundEventScriptList {
}

public static partial class InfoForResourceTypeCVSoundStackScriptList {
}

public static partial class InfoForResourceTypeCVoiceContainerBase {
}

public static partial class InfoForResourceTypeCVoxelVisibility {
}

public static partial class InfoForResourceTypeCWorldNode {
}

public static partial class InfoForResourceTypeIAnimGraphModelBinding {
}

public static partial class InfoForResourceTypeIMaterial2 {
}

public static partial class InfoForResourceTypeIParticleSnapshot {
}

public static partial class InfoForResourceTypeIParticleSystemDefinition {
}

public static partial class InfoForResourceTypeIPulseGraphDef {
}

public static partial class InfoForResourceTypeIVectorGraphic {
}

public static partial class InfoForResourceTypeManifestTestResource_t {
}

public static partial class InfoForResourceTypeProceduralTestResource_t {
}

public static partial class InfoForResourceTypeWorld_t {
}

public static partial class ManifestTestResource_t {
    public const nint m_name = 0x0; // CUtlString
    public const nint m_child = 0x8; // CStrongHandle<InfoForResourceTypeManifestTestResource_t>
}

public static partial class PackedAABB_t {
    public const nint m_nPackedMin = 0x0; // uint32
    public const nint m_nPackedMax = 0x4; // uint32
}

public static partial class VariableInfo_t {
    public const nint m_name = 0x0; // CUtlString
    public const nint m_nameToken = 0x8; // CUtlStringToken
    public const nint m_nIndex = 0xC; // FuseVariableIndex_t
    public const nint m_nNumComponents = 0xE; // uint8
    public const nint m_eVarType = 0xF; // FuseVariableType_t
    public const nint m_eAccess = 0x10; // FuseVariableAccess_t
}

public enum FuseVariableAccess_t : byte {
    WRITABLE = 0,
    READ_ONLY = 1,
}

public enum FuseVariableType_t : byte {
    INVALID = 0,
    BOOL = 1,
    INT8 = 2,
    INT16 = 3,
    INT32 = 4,
    UINT8 = 5,
    UINT16 = 6,
    UINT32 = 7,
    FLOAT32 = 8,
}

