// Generated by CS2Dumper — 2026-07-17T15:19:48Z
// Module: resourcesystem.dll
#pragma once
#include <cstddef>
#include <cstdint>

namespace cs2_dumper::schemas::resourcesystem_dll {

    // AABBWS_t
    namespace AABBWS_t {
        constexpr std::ptrdiff_t m_vMinBounds = 0x0; // VectorWS
        constexpr std::ptrdiff_t m_vMaxBounds = 0xC; // VectorWS
    }

    // AABB_t
    namespace AABB_t {
        constexpr std::ptrdiff_t m_vMinBounds = 0x0; // Vector
        constexpr std::ptrdiff_t m_vMaxBounds = 0xC; // Vector
    }

    // CFuseProgram
    namespace CFuseProgram {
        constexpr std::ptrdiff_t m_programBuffer = 0x0; // CUtlVector<uint8>
        constexpr std::ptrdiff_t m_variablesRead = 0x18; // CUtlVector<FuseVariableIndex_t>
        constexpr std::ptrdiff_t m_variablesWritten = 0x30; // CUtlVector<FuseVariableIndex_t>
        constexpr std::ptrdiff_t m_nMaxTempVarsUsed = 0x48; // int32
    }

    // CFuseSymbolTable
    namespace CFuseSymbolTable {
        constexpr std::ptrdiff_t m_constants = 0x0; // CUtlVector<ConstantInfo_t>
        constexpr std::ptrdiff_t m_variables = 0x18; // CUtlVector<VariableInfo_t>
        constexpr std::ptrdiff_t m_functions = 0x30; // CUtlVector<FunctionInfo_t>
        constexpr std::ptrdiff_t m_constantMap = 0x48; // CUtlHashtable<CUtlStringToken,int32>
        constexpr std::ptrdiff_t m_variableMap = 0x68; // CUtlHashtable<CUtlStringToken,int32>
        constexpr std::ptrdiff_t m_functionMap = 0x88; // CUtlHashtable<CUtlStringToken,int32>
    }

    // ConstantInfo_t
    namespace ConstantInfo_t {
        constexpr std::ptrdiff_t m_name = 0x0; // CUtlString
        constexpr std::ptrdiff_t m_nameToken = 0x8; // CUtlStringToken
        constexpr std::ptrdiff_t m_flValue = 0xC; // float32
    }

    // FourQuaternions
    namespace FourQuaternions {
        constexpr std::ptrdiff_t x = 0x0; // fltx4
        constexpr std::ptrdiff_t y = 0x10; // fltx4
        constexpr std::ptrdiff_t z = 0x20; // fltx4
        constexpr std::ptrdiff_t w = 0x30; // fltx4
    }

    // FunctionInfo_t
    namespace FunctionInfo_t {
        constexpr std::ptrdiff_t m_name = 0x8; // CUtlString
        constexpr std::ptrdiff_t m_nameToken = 0x10; // CUtlStringToken
        constexpr std::ptrdiff_t m_nParamCount = 0x14; // int32
        constexpr std::ptrdiff_t m_nIndex = 0x18; // FuseFunctionIndex_t
        constexpr std::ptrdiff_t m_bIsPure = 0x1A; // bool
    }

    // FuseFunctionIndex_t
    namespace FuseFunctionIndex_t {
        constexpr std::ptrdiff_t m_Value = 0x0; // uint16
    }

    // FuseVariableIndex_t
    namespace FuseVariableIndex_t {
        constexpr std::ptrdiff_t m_Value = 0x0; // uint16
    }

    // InfoForResourceTypeCAnimData
    namespace InfoForResourceTypeCAnimData {
    }

    // InfoForResourceTypeCAnimationGroup
    namespace InfoForResourceTypeCAnimationGroup {
    }

    // InfoForResourceTypeCCSGOEconItem
    namespace InfoForResourceTypeCCSGOEconItem {
    }

    // InfoForResourceTypeCChoreoSceneResource
    namespace InfoForResourceTypeCChoreoSceneResource {
    }

    // InfoForResourceTypeCCompositeMaterialKit
    namespace InfoForResourceTypeCCompositeMaterialKit {
    }

    // InfoForResourceTypeCDOTANovelsList
    namespace InfoForResourceTypeCDOTANovelsList {
    }

    // InfoForResourceTypeCDOTAPatchNotesList
    namespace InfoForResourceTypeCDOTAPatchNotesList {
    }

    // InfoForResourceTypeCDotaItemDefinitionResource
    namespace InfoForResourceTypeCDotaItemDefinitionResource {
    }

    // InfoForResourceTypeCEntityLump
    namespace InfoForResourceTypeCEntityLump {
    }

    // InfoForResourceTypeCGcExportableExternalData
    namespace InfoForResourceTypeCGcExportableExternalData {
    }

    // InfoForResourceTypeCJavaScriptResource
    namespace InfoForResourceTypeCJavaScriptResource {
    }

    // InfoForResourceTypeCModel
    namespace InfoForResourceTypeCModel {
    }

    // InfoForResourceTypeCMorphSetData
    namespace InfoForResourceTypeCMorphSetData {
    }

    // InfoForResourceTypeCNmClip
    namespace InfoForResourceTypeCNmClip {
    }

    // InfoForResourceTypeCNmGraphDefinition
    namespace InfoForResourceTypeCNmGraphDefinition {
    }

    // InfoForResourceTypeCNmSkeleton
    namespace InfoForResourceTypeCNmSkeleton {
    }

    // InfoForResourceTypeCPanoramaDynamicImages
    namespace InfoForResourceTypeCPanoramaDynamicImages {
    }

    // InfoForResourceTypeCPanoramaLayout
    namespace InfoForResourceTypeCPanoramaLayout {
    }

    // InfoForResourceTypeCPanoramaStyle
    namespace InfoForResourceTypeCPanoramaStyle {
    }

    // InfoForResourceTypeCPhysAggregateData
    namespace InfoForResourceTypeCPhysAggregateData {
    }

    // InfoForResourceTypeCPostProcessingResource
    namespace InfoForResourceTypeCPostProcessingResource {
    }

    // InfoForResourceTypeCRenderMesh
    namespace InfoForResourceTypeCRenderMesh {
    }

    // InfoForResourceTypeCResponseRulesList
    namespace InfoForResourceTypeCResponseRulesList {
    }

    // InfoForResourceTypeCSequenceGroupData
    namespace InfoForResourceTypeCSequenceGroupData {
    }

    // InfoForResourceTypeCSmartProp
    namespace InfoForResourceTypeCSmartProp {
    }

    // InfoForResourceTypeCSurfaceGraph
    namespace InfoForResourceTypeCSurfaceGraph {
    }

    // InfoForResourceTypeCTestResourceData
    namespace InfoForResourceTypeCTestResourceData {
    }

    // InfoForResourceTypeCTextureBase
    namespace InfoForResourceTypeCTextureBase {
    }

    // InfoForResourceTypeCTypeScriptResource
    namespace InfoForResourceTypeCTypeScriptResource {
    }

    // InfoForResourceTypeCVDataItemDefs
    namespace InfoForResourceTypeCVDataItemDefs {
    }

    // InfoForResourceTypeCVDataResource
    namespace InfoForResourceTypeCVDataResource {
    }

    // InfoForResourceTypeCVMixListResource
    namespace InfoForResourceTypeCVMixListResource {
    }

    // InfoForResourceTypeCVPhysXSurfacePropertiesList
    namespace InfoForResourceTypeCVPhysXSurfacePropertiesList {
    }

    // InfoForResourceTypeCVSoundEventScriptList
    namespace InfoForResourceTypeCVSoundEventScriptList {
    }

    // InfoForResourceTypeCVSoundStackScriptList
    namespace InfoForResourceTypeCVSoundStackScriptList {
    }

    // InfoForResourceTypeCVoiceContainerBase
    namespace InfoForResourceTypeCVoiceContainerBase {
    }

    // InfoForResourceTypeCVoxelVisibility
    namespace InfoForResourceTypeCVoxelVisibility {
    }

    // InfoForResourceTypeCWorldNode
    namespace InfoForResourceTypeCWorldNode {
    }

    // InfoForResourceTypeIAnimGraphModelBinding
    namespace InfoForResourceTypeIAnimGraphModelBinding {
    }

    // InfoForResourceTypeIMaterial2
    namespace InfoForResourceTypeIMaterial2 {
    }

    // InfoForResourceTypeIParticleSnapshot
    namespace InfoForResourceTypeIParticleSnapshot {
    }

    // InfoForResourceTypeIParticleSystemDefinition
    namespace InfoForResourceTypeIParticleSystemDefinition {
    }

    // InfoForResourceTypeIPulseGraphDef
    namespace InfoForResourceTypeIPulseGraphDef {
    }

    // InfoForResourceTypeIVectorGraphic
    namespace InfoForResourceTypeIVectorGraphic {
    }

    // InfoForResourceTypeManifestTestResource_t
    namespace InfoForResourceTypeManifestTestResource_t {
    }

    // InfoForResourceTypeProceduralTestResource_t
    namespace InfoForResourceTypeProceduralTestResource_t {
    }

    // InfoForResourceTypeWorld_t
    namespace InfoForResourceTypeWorld_t {
    }

    // ManifestTestResource_t
    namespace ManifestTestResource_t {
        constexpr std::ptrdiff_t m_name = 0x0; // CUtlString
        constexpr std::ptrdiff_t m_child = 0x8; // CStrongHandle<InfoForResourceTypeManifestTestResource_t>
    }

    // PackedAABB_t
    namespace PackedAABB_t {
        constexpr std::ptrdiff_t m_nPackedMin = 0x0; // uint32
        constexpr std::ptrdiff_t m_nPackedMax = 0x4; // uint32
    }

    // VariableInfo_t
    namespace VariableInfo_t {
        constexpr std::ptrdiff_t m_name = 0x0; // CUtlString
        constexpr std::ptrdiff_t m_nameToken = 0x8; // CUtlStringToken
        constexpr std::ptrdiff_t m_nIndex = 0xC; // FuseVariableIndex_t
        constexpr std::ptrdiff_t m_nNumComponents = 0xE; // uint8
        constexpr std::ptrdiff_t m_eVarType = 0xF; // FuseVariableType_t
        constexpr std::ptrdiff_t m_eAccess = 0x10; // FuseVariableAccess_t
    }

    // ── Enums ────────────────────────────────────
    enum class FuseVariableAccess_t : uint8_t {
        WRITABLE = 0,
        READ_ONLY = 1,
    };

    enum class FuseVariableType_t : uint8_t {
        INVALID = 0,
        BOOL = 1,
        INT8 = 2,
        INT16 = 3,
        INT32 = 4,
        UINT8 = 5,
        UINT16 = 6,
        UINT32 = 7,
        FLOAT32 = 8,
    };

} // namespace cs2_dumper::schemas::resourcesystem_dll
