// Generated by CS2Dumper — 2026-07-17T15:19:48Z
// Module: scenesystem.dll
namespace CS2Dumper.Schemas;

public static partial class CSSDSEndFrameViewInfo {
    public const nint m_nViewId = 0x0; // uint64
    public const nint m_ViewName = 0x8; // CUtlString
}

public static partial class CSSDSMsg_EndFrame {
    public const nint m_Views = 0x0; // CUtlVector<CSSDSEndFrameViewInfo>
}

public static partial class CSSDSMsg_LayerBase {
    public const nint m_viewId = 0x0; // SceneViewId_t
    public const nint m_ViewName = 0x10; // CUtlString
    public const nint m_nLayerId = 0x18; // uint64
    public const nint m_LayerName = 0x20; // CUtlString
    public const nint m_displayText = 0x28; // CUtlString
}

public static partial class CSSDSMsg_PostLayer {
}

public static partial class CSSDSMsg_PreLayer {
}

public static partial class CSSDSMsg_ViewRender {
    public const nint m_viewId = 0x0; // SceneViewId_t
    public const nint m_ViewName = 0x10; // CUtlString
}

public static partial class CSSDSMsg_ViewTarget {
    public const nint m_Name = 0x0; // CUtlString
    public const nint m_TextureId = 0x8; // uint64
    public const nint m_nWidth = 0x10; // int32
    public const nint m_nHeight = 0x14; // int32
    public const nint m_nRequestedWidth = 0x18; // int32
    public const nint m_nRequestedHeight = 0x1C; // int32
    public const nint m_nNumMipLevels = 0x20; // int32
    public const nint m_nDepth = 0x24; // int32
    public const nint m_nMultisampleNumSamples = 0x28; // int32
    public const nint m_nFormat = 0x2C; // int32
}

public static partial class CSSDSMsg_ViewTargetList {
    public const nint m_viewId = 0x0; // SceneViewId_t
    public const nint m_ViewName = 0x10; // CUtlString
    public const nint m_Targets = 0x18; // CUtlVector<CSSDSMsg_ViewTarget>
}

public static partial class SceneViewId_t {
    public const nint m_nViewId = 0x0; // uint64
    public const nint m_nFrameCount = 0x8; // uint64
}

public enum DecalRtEncoding_t : byte {
    kDecalInvalid = 255,
    kDecalMin = 0,
    kDecalBlood = 0,
    kDecalCloak = 1,
    kDecalMax = 2,
    kDecalDefault = 0,
}

public enum DisableShadows_t : byte {
    kDisableShadows_None = 0,
    kDisableShadows_All = 1,
    kDisableShadows_Baked = 2,
    kDisableShadows_Realtime = 3,
    kDisableShadows_ReallyNone = 4,
}

public enum ESceneObjectMeshletVisualization : int {
    SCENEOBJECT_MESHLET_VIS_NONE = 0,
    SCENEOBJECT_MESHLET_VIS_MESHLET = 1,
    SCENEOBJECT_MESHLET_VIS_CULLED = 2,
}

public enum ESceneObjectVisualization : int {
    SCENEOBJECT_VIS_NONE = 0,
    SCENEOBJECT_VIS_OBJECT = 1,
    SCENEOBJECT_VIS_MATERIAL = 2,
    SCENEOBJECT_VIS_TEXTURE_SIZE = 3,
    SCENEOBJECT_VIS_LOD = 4,
    SCENEOBJECT_VIS_INSTANCING = 5,
}

public enum ESceneViewDebugOverlaysListenerDataType_t : int {
    k_ESceneViewDebugOverlaysListenerDataType_Unknown = 0,
    k_ESceneViewDebugOverlaysListenerDataType_Sphere = 1,
    k_ESceneViewDebugOverlaysListenerDataType_Capsule = 2,
    k_ESceneViewDebugOverlaysListenerDataType_BoxAngles = 3,
    k_ESceneViewDebugOverlaysListenerDataType_Line = 4,
    k_ESceneViewDebugOverlaysListenerDataType_SolidBoxAngles = 5,
    k_ESceneViewDebugOverlaysListenerDataType_Text3D = 6,
}

public enum ESilhouetteType_t : int {
    SILHOUETTE_NONE = 0,
    SILHOUETTE_LIGHT = 1,
    SILHOUETTE_ENVMAP = 2,
    SILHOUETTE_LPV = 4,
}

