// Generated by CS2Dumper — 2026-07-17T15:19:48Z
// Module: scenesystem.dll
#pragma once
#include <cstddef>
#include <cstdint>

namespace cs2_dumper::schemas::scenesystem_dll {

    // CSSDSEndFrameViewInfo
    namespace CSSDSEndFrameViewInfo {
        constexpr std::ptrdiff_t m_nViewId = 0x0; // uint64
        constexpr std::ptrdiff_t m_ViewName = 0x8; // CUtlString
    }

    // CSSDSMsg_EndFrame
    namespace CSSDSMsg_EndFrame {
        constexpr std::ptrdiff_t m_Views = 0x0; // CUtlVector<CSSDSEndFrameViewInfo>
    }

    // CSSDSMsg_LayerBase
    namespace CSSDSMsg_LayerBase {
        constexpr std::ptrdiff_t m_viewId = 0x0; // SceneViewId_t
        constexpr std::ptrdiff_t m_ViewName = 0x10; // CUtlString
        constexpr std::ptrdiff_t m_nLayerId = 0x18; // uint64
        constexpr std::ptrdiff_t m_LayerName = 0x20; // CUtlString
        constexpr std::ptrdiff_t m_displayText = 0x28; // CUtlString
    }

    // CSSDSMsg_PostLayer
    namespace CSSDSMsg_PostLayer {
    }

    // CSSDSMsg_PreLayer
    namespace CSSDSMsg_PreLayer {
    }

    // CSSDSMsg_ViewRender
    namespace CSSDSMsg_ViewRender {
        constexpr std::ptrdiff_t m_viewId = 0x0; // SceneViewId_t
        constexpr std::ptrdiff_t m_ViewName = 0x10; // CUtlString
    }

    // CSSDSMsg_ViewTarget
    namespace CSSDSMsg_ViewTarget {
        constexpr std::ptrdiff_t m_Name = 0x0; // CUtlString
        constexpr std::ptrdiff_t m_TextureId = 0x8; // uint64
        constexpr std::ptrdiff_t m_nWidth = 0x10; // int32
        constexpr std::ptrdiff_t m_nHeight = 0x14; // int32
        constexpr std::ptrdiff_t m_nRequestedWidth = 0x18; // int32
        constexpr std::ptrdiff_t m_nRequestedHeight = 0x1C; // int32
        constexpr std::ptrdiff_t m_nNumMipLevels = 0x20; // int32
        constexpr std::ptrdiff_t m_nDepth = 0x24; // int32
        constexpr std::ptrdiff_t m_nMultisampleNumSamples = 0x28; // int32
        constexpr std::ptrdiff_t m_nFormat = 0x2C; // int32
    }

    // CSSDSMsg_ViewTargetList
    namespace CSSDSMsg_ViewTargetList {
        constexpr std::ptrdiff_t m_viewId = 0x0; // SceneViewId_t
        constexpr std::ptrdiff_t m_ViewName = 0x10; // CUtlString
        constexpr std::ptrdiff_t m_Targets = 0x18; // CUtlVector<CSSDSMsg_ViewTarget>
    }

    // SceneViewId_t
    namespace SceneViewId_t {
        constexpr std::ptrdiff_t m_nViewId = 0x0; // uint64
        constexpr std::ptrdiff_t m_nFrameCount = 0x8; // uint64
    }

    // ── Enums ────────────────────────────────────
    enum class DecalRtEncoding_t : uint8_t {
        kDecalInvalid = 255,
        kDecalMin = 0,
        kDecalBlood = 0,
        kDecalCloak = 1,
        kDecalMax = 2,
        kDecalDefault = 0,
    };

    enum class DisableShadows_t : uint8_t {
        kDisableShadows_None = 0,
        kDisableShadows_All = 1,
        kDisableShadows_Baked = 2,
        kDisableShadows_Realtime = 3,
        kDisableShadows_ReallyNone = 4,
    };

    enum class ESceneObjectMeshletVisualization : int32_t {
        SCENEOBJECT_MESHLET_VIS_NONE = 0,
        SCENEOBJECT_MESHLET_VIS_MESHLET = 1,
        SCENEOBJECT_MESHLET_VIS_CULLED = 2,
    };

    enum class ESceneObjectVisualization : int32_t {
        SCENEOBJECT_VIS_NONE = 0,
        SCENEOBJECT_VIS_OBJECT = 1,
        SCENEOBJECT_VIS_MATERIAL = 2,
        SCENEOBJECT_VIS_TEXTURE_SIZE = 3,
        SCENEOBJECT_VIS_LOD = 4,
        SCENEOBJECT_VIS_INSTANCING = 5,
    };

    enum class ESceneViewDebugOverlaysListenerDataType_t : int32_t {
        k_ESceneViewDebugOverlaysListenerDataType_Unknown = 0,
        k_ESceneViewDebugOverlaysListenerDataType_Sphere = 1,
        k_ESceneViewDebugOverlaysListenerDataType_Capsule = 2,
        k_ESceneViewDebugOverlaysListenerDataType_BoxAngles = 3,
        k_ESceneViewDebugOverlaysListenerDataType_Line = 4,
        k_ESceneViewDebugOverlaysListenerDataType_SolidBoxAngles = 5,
        k_ESceneViewDebugOverlaysListenerDataType_Text3D = 6,
    };

    enum class ESilhouetteType_t : int32_t {
        SILHOUETTE_NONE = 0,
        SILHOUETTE_LIGHT = 1,
        SILHOUETTE_ENVMAP = 2,
        SILHOUETTE_LPV = 4,
    };

} // namespace cs2_dumper::schemas::scenesystem_dll
