// Generated by CS2Dumper — 2026-07-17T15:19:48Z
// Module: soundsystem.dll
#pragma once
#include <cstddef>
#include <cstdint>

namespace cs2_dumper::schemas::soundsystem_dll {

    // CAudioEmphasisSample
    namespace CAudioEmphasisSample {
        constexpr std::ptrdiff_t m_flTime = 0x0; // float32
        constexpr std::ptrdiff_t m_flValue = 0x4; // float32
    }

    // CAudioMorphData
    namespace CAudioMorphData {
        constexpr std::ptrdiff_t m_times = 0x0; // CUtlVector<float32>
        constexpr std::ptrdiff_t m_nameHashCodes = 0x18; // CUtlVector<uint32>
        constexpr std::ptrdiff_t m_nameStrings = 0x30; // CUtlVector<CUtlString>
        constexpr std::ptrdiff_t m_samples = 0x48; // CUtlVector<CUtlVector<float32>>
        constexpr std::ptrdiff_t m_flEaseIn = 0x60; // float32
        constexpr std::ptrdiff_t m_flEaseOut = 0x64; // float32
    }

    // CAudioPhonemeTag
    namespace CAudioPhonemeTag {
        constexpr std::ptrdiff_t m_flStartTime = 0x0; // float32
        constexpr std::ptrdiff_t m_flEndTime = 0x4; // float32
        constexpr std::ptrdiff_t m_nPhonemeCode = 0x8; // int32
    }

    // CAudioSentence
    namespace CAudioSentence {
        constexpr std::ptrdiff_t m_bShouldVoiceDuck = 0x0; // bool
        constexpr std::ptrdiff_t m_RunTimePhonemes = 0x8; // CUtlVector<CAudioPhonemeTag>
        constexpr std::ptrdiff_t m_EmphasisSamples = 0x20; // CUtlVector<CAudioEmphasisSample>
        constexpr std::ptrdiff_t m_morphData = 0x38; // CAudioMorphData
    }

    // CDSPMixgroupModifier
    namespace CDSPMixgroupModifier {
        constexpr std::ptrdiff_t m_mixgroup = 0x0; // CUtlString
        constexpr std::ptrdiff_t m_flModifier = 0x8; // float32
        constexpr std::ptrdiff_t m_flModifierMin = 0xC; // float32
        constexpr std::ptrdiff_t m_flSourceModifier = 0x10; // float32
        constexpr std::ptrdiff_t m_flSourceModifierMin = 0x14; // float32
        constexpr std::ptrdiff_t m_flListenerReverbModifierWhenSourceReverbIsActive = 0x18; // float32
    }

    // CDSPPresetMixgroupModifierTable
    namespace CDSPPresetMixgroupModifierTable {
        constexpr std::ptrdiff_t m_table = 0x0; // CUtlVector<CDspPresetModifierList>
    }

    // CDspPresetModifierList
    namespace CDspPresetModifierList {
        constexpr std::ptrdiff_t m_dspName = 0x0; // CUtlString
        constexpr std::ptrdiff_t m_modifiers = 0x8; // CUtlVector<CDSPMixgroupModifier>
    }

    // CRandomPannerControls
    namespace CRandomPannerControls {
        constexpr std::ptrdiff_t m_panningControlInputName = 0x0; // CUtlString
        constexpr std::ptrdiff_t m_volumeControlInputName = 0x8; // CUtlString
        constexpr std::ptrdiff_t m_flMinVolume = 0x10; // float32
        constexpr std::ptrdiff_t m_flMaxVolume = 0x14; // float32
        constexpr std::ptrdiff_t m_strVectorStackParam = 0x18; // CUtlString
    }

    // CSndBeatPattern
    namespace CSndBeatPattern {
        constexpr std::ptrdiff_t m_name = 0x0; // CUtlString
        constexpr std::ptrdiff_t m_launchSyncType = 0xC; // SndBeatLaunchSyncType_t
        constexpr std::ptrdiff_t m_flSyncPriority = 0x10; // float32
        constexpr std::ptrdiff_t m_timeSignature = 0x14; // SndBeatTimeSignature_t
        constexpr std::ptrdiff_t m_flLength = 0x1C; // float32
        constexpr std::ptrdiff_t m_bLooping = 0x20; // bool
        constexpr std::ptrdiff_t m_launchSyncEventType = 0x24; // SndBeatEventType_t
        constexpr std::ptrdiff_t m_flSyncBeatMult = 0x28; // float32
        constexpr std::ptrdiff_t m_playEventType = 0x2C; // SndBeatEventType_t
        constexpr std::ptrdiff_t m_flPlayBeatMult = 0x30; // float32
        constexpr std::ptrdiff_t m_keyType = 0x34; // SndBeatKeyType_t
        constexpr std::ptrdiff_t m_vecPatternKeys = 0x38; // CUtlVector<SndBeatEventKeys_t>
        constexpr std::ptrdiff_t m_vecPatternFloats = 0x50; // CUtlVector<SndBeatEventKeyedFloats_t>
        constexpr std::ptrdiff_t m_vecPatternSndEvts = 0x68; // CUtlVector<SndBeatEventKeyedSndEvts_t>
        constexpr std::ptrdiff_t m_vecPatternMidi = 0x80; // CUtlVector<SndBeatEventKeyedMidiNotes_t>
    }

    // CSndBeatPatternManager
    namespace CSndBeatPatternManager {
        constexpr std::ptrdiff_t m_vecPatterns = 0x38; // CUtlVector<CSndBeatPattern>
        constexpr std::ptrdiff_t m_vecActiveTracks = 0x70; // CUtlVector<CSndBeatTrack>
    }

    // CSndBeatTrack
    namespace CSndBeatTrack {
        constexpr std::ptrdiff_t m_name = 0x0; // CUtlString
        constexpr std::ptrdiff_t m_playbackType = 0x20; // SndBeatTrackPlaybackType_t
        constexpr std::ptrdiff_t m_nTranspose = 0x24; // int32
        constexpr std::ptrdiff_t m_bSyncToVoice = 0x28; // bool
        constexpr std::ptrdiff_t m_flBPM = 0x2C; // float32
    }

    // CSndSeqInstBaseSchema
    namespace CSndSeqInstBaseSchema {
        constexpr std::ptrdiff_t m_nType = 0x8; // SndSeqInstrumentType_t
        constexpr std::ptrdiff_t m_bStopCurrentEvents = 0xE; // bool
        constexpr std::ptrdiff_t m_flBPM = 0x10; // float32
        constexpr std::ptrdiff_t m_flBPMFactor = 0x14; // float32
        constexpr std::ptrdiff_t m_flBPMInvFactor = 0x18; // float32
    }

    // CSndSeqInstMidiSampler
    namespace CSndSeqInstMidiSampler {
        constexpr std::ptrdiff_t m_bIsSoundEvent = 0x20; // bool
        constexpr std::ptrdiff_t m_bStopPrevious = 0x21; // bool
        constexpr std::ptrdiff_t m_nMinNote = 0x22; // uint8
        constexpr std::ptrdiff_t m_nMaxNote = 0x23; // uint8
        constexpr std::ptrdiff_t m_flMinVelocityAtten = 0x24; // float32
        constexpr std::ptrdiff_t m_flMaxVelocityAtten = 0x28; // float32
        constexpr std::ptrdiff_t m_flAttack = 0x2C; // float32
        constexpr std::ptrdiff_t m_flRelease = 0x30; // float32
        constexpr std::ptrdiff_t m_bBeatEnvelopes = 0x34; // bool
        constexpr std::ptrdiff_t m_nNextVoiceSlot = 0xD4; // uint8
        constexpr std::ptrdiff_t m_hSoundEventHash = 0xD8; // uint32
    }

    // CSndSeqInstSndEvtSchema
    namespace CSndSeqInstSndEvtSchema {
    }

    // CSndSeqInstruments
    namespace CSndSeqInstruments {
    }

    // CSosGroupActionLimitSchema
    namespace CSosGroupActionLimitSchema {
        constexpr std::ptrdiff_t m_nMaxCount = 0x8; // int32
        constexpr std::ptrdiff_t m_nStopType = 0xC; // SosActionStopType_t
        constexpr std::ptrdiff_t m_nSortType = 0x10; // SosActionLimitSortType_t
        constexpr std::ptrdiff_t m_bStopImmediate = 0x14; // bool
        constexpr std::ptrdiff_t m_bCountStopped = 0x15; // bool
    }

    // CSosGroupActionMemberCountEnvelopeSchema
    namespace CSosGroupActionMemberCountEnvelopeSchema {
        constexpr std::ptrdiff_t m_nBaseCount = 0x8; // int32
        constexpr std::ptrdiff_t m_nTargetCount = 0xC; // int32
        constexpr std::ptrdiff_t m_flBaseValue = 0x10; // float32
        constexpr std::ptrdiff_t m_flTargetValue = 0x14; // float32
        constexpr std::ptrdiff_t m_flAttack = 0x18; // float32
        constexpr std::ptrdiff_t m_flDecay = 0x1C; // float32
        constexpr std::ptrdiff_t m_resultVarName = 0x20; // CUtlString
        constexpr std::ptrdiff_t m_bSaveToGroup = 0x28; // bool
    }

    // CSosGroupActionOcclusionSchema
    namespace CSosGroupActionOcclusionSchema {
        constexpr std::ptrdiff_t m_flCalculationInterval = 0x8; // float32
        constexpr std::ptrdiff_t m_flRadius = 0xC; // float32
        constexpr std::ptrdiff_t m_flOcclusionScale = 0x10; // float32
        constexpr std::ptrdiff_t m_flOcclusionMin = 0x14; // float32
        constexpr std::ptrdiff_t m_flOcclusionMax = 0x18; // float32
        constexpr std::ptrdiff_t m_flTestDepth = 0x1C; // float32
    }

    // CSosGroupActionSchema
    namespace CSosGroupActionSchema {
    }

    // CSosGroupActionSetSoundeventParameterSchema
    namespace CSosGroupActionSetSoundeventParameterSchema {
        constexpr std::ptrdiff_t m_nMaxCount = 0x8; // int32
        constexpr std::ptrdiff_t m_flMinValue = 0xC; // float32
        constexpr std::ptrdiff_t m_flMaxValue = 0x10; // float32
        constexpr std::ptrdiff_t m_opvarName = 0x18; // CUtlString
        constexpr std::ptrdiff_t m_nSortType = 0x20; // SosActionSetParamSortType_t
    }

    // CSosGroupActionSoundeventClusterSchema
    namespace CSosGroupActionSoundeventClusterSchema {
        constexpr std::ptrdiff_t m_nMinNearby = 0x8; // int32
        constexpr std::ptrdiff_t m_flClusterEpsilon = 0xC; // float32
        constexpr std::ptrdiff_t m_shouldPlayOpvar = 0x10; // CUtlString
        constexpr std::ptrdiff_t m_shouldPlayClusterChild = 0x18; // CUtlString
        constexpr std::ptrdiff_t m_clusterSizeOpvar = 0x20; // CUtlString
        constexpr std::ptrdiff_t m_groupBoundingBoxMinsOpvar = 0x28; // CUtlString
        constexpr std::ptrdiff_t m_groupBoundingBoxMaxsOpvar = 0x30; // CUtlString
    }

    // CSosGroupActionSoundeventCountSchema
    namespace CSosGroupActionSoundeventCountSchema {
        constexpr std::ptrdiff_t m_bExcludeStoppedSounds = 0x8; // bool
        constexpr std::ptrdiff_t m_strCountKeyName = 0x10; // CUtlString
    }

    // CSosGroupActionSoundeventMinMaxValuesSchema
    namespace CSosGroupActionSoundeventMinMaxValuesSchema {
        constexpr std::ptrdiff_t m_strQueryPublicFieldName = 0x8; // CUtlString
        constexpr std::ptrdiff_t m_strDelayPublicFieldName = 0x10; // CUtlString
        constexpr std::ptrdiff_t m_bExcludeStoppedSounds = 0x18; // bool
        constexpr std::ptrdiff_t m_bExcludeDelayedSounds = 0x19; // bool
        constexpr std::ptrdiff_t m_bExcludeSoundsBelowThreshold = 0x1A; // bool
        constexpr std::ptrdiff_t m_flExcludeSoundsMinThresholdValue = 0x1C; // float32
        constexpr std::ptrdiff_t m_bExcludSoundsAboveThreshold = 0x20; // bool
        constexpr std::ptrdiff_t m_flExcludeSoundsMaxThresholdValue = 0x24; // float32
        constexpr std::ptrdiff_t m_strMinValueName = 0x28; // CUtlString
        constexpr std::ptrdiff_t m_strMaxValueName = 0x30; // CUtlString
    }

    // CSosGroupActionSoundeventPrioritySchema
    namespace CSosGroupActionSoundeventPrioritySchema {
        constexpr std::ptrdiff_t m_priorityValue = 0x8; // CUtlString
        constexpr std::ptrdiff_t m_priorityVolumeScalar = 0x10; // CUtlString
        constexpr std::ptrdiff_t m_priorityContributeButDontRead = 0x18; // CUtlString
        constexpr std::ptrdiff_t m_bPriorityReadButDontContribute = 0x20; // CUtlString
    }

    // CSosGroupActionTimeBlockLimitSchema
    namespace CSosGroupActionTimeBlockLimitSchema {
        constexpr std::ptrdiff_t m_nMaxCount = 0x8; // int32
        constexpr std::ptrdiff_t m_flMaxDuration = 0xC; // float32
    }

    // CSosGroupActionTimeLimitSchema
    namespace CSosGroupActionTimeLimitSchema {
        constexpr std::ptrdiff_t m_flMaxDuration = 0x8; // float32
    }

    // CSosSoundEventGroupSchema
    namespace CSosSoundEventGroupSchema {
        constexpr std::ptrdiff_t m_nGroupType = 0x8; // SosGroupType_t
        constexpr std::ptrdiff_t m_bBlocksEvents = 0xC; // bool
        constexpr std::ptrdiff_t m_nBlockMaxCount = 0x10; // int32
        constexpr std::ptrdiff_t m_flMemberLifespanTime = 0x14; // float32
        constexpr std::ptrdiff_t m_bInvertMatch = 0x18; // bool
        constexpr std::ptrdiff_t m_Behavior_EventName = 0x1C; // SosGroupFieldBehavior_t
        constexpr std::ptrdiff_t m_matchSoundEventName = 0x20; // CUtlString
        constexpr std::ptrdiff_t m_bMatchEventSubString = 0x28; // bool
        constexpr std::ptrdiff_t m_matchSoundEventSubString = 0x30; // CUtlString
        constexpr std::ptrdiff_t m_Behavior_EntIndex = 0x38; // SosGroupFieldBehavior_t
        constexpr std::ptrdiff_t m_flEntIndex = 0x3C; // float32
        constexpr std::ptrdiff_t m_Behavior_Opvar = 0x40; // SosGroupFieldBehavior_t
        constexpr std::ptrdiff_t m_flOpvar = 0x44; // float32
        constexpr std::ptrdiff_t m_Behavior_String = 0x48; // SosGroupFieldBehavior_t
        constexpr std::ptrdiff_t m_opvarString = 0x50; // CUtlString
        constexpr std::ptrdiff_t m_vActions = 0x58; // CUtlVector<CSosGroupActionSchema*>
    }

    // CSoundContainerReference
    namespace CSoundContainerReference {
        constexpr std::ptrdiff_t m_namespace = 0x0; // CUtlString
        constexpr std::ptrdiff_t m_bUseReference = 0x8; // bool
        constexpr std::ptrdiff_t m_sound = 0x10; // CStrongHandle<InfoForResourceTypeCVoiceContainerBase>
        constexpr std::ptrdiff_t m_pSound = 0x18; // CVoiceContainerBase*
    }

    // CSoundContainerReferenceArray
    namespace CSoundContainerReferenceArray {
        constexpr std::ptrdiff_t m_bUseReference = 0x0; // bool
        constexpr std::ptrdiff_t m_sounds = 0x8; // CUtlVector<CStrongHandle<InfoForResourceTypeCVoiceContainerBase>>
        constexpr std::ptrdiff_t m_pSounds = 0x20; // CUtlVector<CVoiceContainerBase*>
    }

    // CSoundEventMetaData
    namespace CSoundEventMetaData {
        constexpr std::ptrdiff_t m_soundEventVMix = 0x0; // CStrongHandle<InfoForResourceTypeCVMixListResource>
    }

    // CSoundInfoHeader
    namespace CSoundInfoHeader {
    }

    // CVMixAdditionalOutput
    namespace CVMixAdditionalOutput {
        constexpr std::ptrdiff_t m_name = 0x0; // CUtlString
    }

    // CVMixAudioMeter
    namespace CVMixAudioMeter {
        constexpr std::ptrdiff_t m_name = 0x0; // CUtlString
        constexpr std::ptrdiff_t m_displayName = 0x8; // CUtlString
    }

    // CVMixAutoFilterProcessorDesc
    namespace CVMixAutoFilterProcessorDesc {
        constexpr std::ptrdiff_t m_desc = 0x20; // VMixAutoFilterDesc_t
    }

    // CVMixAutomaticControlInput
    namespace CVMixAutomaticControlInput {
        constexpr std::ptrdiff_t m_name = 0x0; // CUtlString
        constexpr std::ptrdiff_t m_nControlInputIndex = 0x8; // int32
        constexpr std::ptrdiff_t m_bIsTrackSend = 0xC; // bool
        constexpr std::ptrdiff_t m_bIsStackVar = 0xD; // bool
    }

    // CVMixBaseProcessorDesc
    namespace CVMixBaseProcessorDesc {
        constexpr std::ptrdiff_t m_name = 0x8; // CUtlString
        constexpr std::ptrdiff_t m_nChannels = 0x14; // int32
        constexpr std::ptrdiff_t m_flxfade = 0x18; // float32
    }

    // CVMixBoxverb2ProcessorDesc
    namespace CVMixBoxverb2ProcessorDesc {
        constexpr std::ptrdiff_t m_desc = 0x20; // VMixBoxverbDesc_t
    }

    // CVMixBoxverbProcessorDesc
    namespace CVMixBoxverbProcessorDesc {
        constexpr std::ptrdiff_t m_desc = 0x20; // VMixBoxverbDesc_t
    }

    // CVMixCommand
    namespace CVMixCommand {
        constexpr std::ptrdiff_t m_nCommand = 0x0; // VMixGraphCommandID_t
        constexpr std::ptrdiff_t m_nParameterNameHash = 0x4; // uint32
        constexpr std::ptrdiff_t m_nOutputSubmix = 0x8; // int32
        constexpr std::ptrdiff_t m_nInputSubmix0 = 0xC; // int32
        constexpr std::ptrdiff_t m_nInputSubmix1 = 0x10; // int32
        constexpr std::ptrdiff_t m_nProcessor = 0x14; // int32
        constexpr std::ptrdiff_t m_nInputValue0 = 0x18; // int32
        constexpr std::ptrdiff_t m_nInputValue1 = 0x1C; // int32
    }

    // CVMixControlInput
    namespace CVMixControlInput {
        constexpr std::ptrdiff_t m_flDefaultValue = 0x10; // float32
    }

    // CVMixControlInputArray
    namespace CVMixControlInputArray {
        constexpr std::ptrdiff_t m_nArrayIndex = 0x10; // int32
    }

    // CVMixControlMeter
    namespace CVMixControlMeter {
        constexpr std::ptrdiff_t m_nValueIndex = 0x10; // int32
    }

    // CVMixControlOutput
    namespace CVMixControlOutput {
        constexpr std::ptrdiff_t m_flDefaultValue = 0x10; // float32
    }

    // CVMixConvolutionProcessorDesc
    namespace CVMixConvolutionProcessorDesc {
        constexpr std::ptrdiff_t m_desc = 0x20; // VMixConvolutionDesc_t
    }

    // CVMixCurveHeader
    namespace CVMixCurveHeader {
        constexpr std::ptrdiff_t m_nControlPointCount = 0x0; // uint32
        constexpr std::ptrdiff_t m_nControlPointStart = 0x4; // uint32
    }

    // CVMixDelayProcessorDesc
    namespace CVMixDelayProcessorDesc {
        constexpr std::ptrdiff_t m_desc = 0x20; // VMixDelayDesc_t
    }

    // CVMixDiffusorProcessorDesc
    namespace CVMixDiffusorProcessorDesc {
        constexpr std::ptrdiff_t m_desc = 0x20; // VMixDiffusorDesc_t
    }

    // CVMixDualCompressorProcessorDesc
    namespace CVMixDualCompressorProcessorDesc {
        constexpr std::ptrdiff_t m_desc = 0x20; // VMixDualCompressorDesc_t
    }

    // CVMixDynamics3BandProcessorDesc
    namespace CVMixDynamics3BandProcessorDesc {
        constexpr std::ptrdiff_t m_desc = 0x20; // VMixDynamics3BandDesc_t
    }

    // CVMixDynamicsCompressorProcessorDesc
    namespace CVMixDynamicsCompressorProcessorDesc {
        constexpr std::ptrdiff_t m_desc = 0x20; // VMixDynamicsCompressorDesc_t
    }

    // CVMixDynamicsProcessorDesc
    namespace CVMixDynamicsProcessorDesc {
        constexpr std::ptrdiff_t m_desc = 0x20; // VMixDynamicsDesc_t
    }

    // CVMixEQ8ProcessorDesc
    namespace CVMixEQ8ProcessorDesc {
        constexpr std::ptrdiff_t m_desc = 0x20; // VMixEQ8Desc_t
    }

    // CVMixEffectChainProcessorDesc
    namespace CVMixEffectChainProcessorDesc {
        constexpr std::ptrdiff_t m_desc = 0x20; // VMixEffectChainDesc_t
    }

    // CVMixEnvelopeProcessorDesc
    namespace CVMixEnvelopeProcessorDesc {
        constexpr std::ptrdiff_t m_desc = 0x20; // VMixEnvelopeDesc_t
    }

    // CVMixFilterProcessorDesc
    namespace CVMixFilterProcessorDesc {
        constexpr std::ptrdiff_t m_desc = 0x20; // VMixFilterDesc_t
    }

    // CVMixFlangerProcessorDesc
    namespace CVMixFlangerProcessorDesc {
        constexpr std::ptrdiff_t m_desc = 0x20; // VMixFlangerDesc_t
    }

    // CVMixFreeverbProcessorDesc
    namespace CVMixFreeverbProcessorDesc {
        constexpr std::ptrdiff_t m_desc = 0x20; // VMixFreeverbDesc_t
    }

    // CVMixGraphDescData
    namespace CVMixGraphDescData {
        constexpr std::ptrdiff_t m_name = 0x0; // CUtlString
        constexpr std::ptrdiff_t m_nGraphOutputChannels = 0x8; // int32
        constexpr std::ptrdiff_t m_bIsMainGraph = 0xC; // bool
    }

    // CVMixImpulseResponseInput
    namespace CVMixImpulseResponseInput {
    }

    // CVMixInputBase
    namespace CVMixInputBase {
        constexpr std::ptrdiff_t m_name = 0x0; // CUtlString
    }

    // CVMixModDelayProcessorDesc
    namespace CVMixModDelayProcessorDesc {
        constexpr std::ptrdiff_t m_desc = 0x20; // VMixModDelayDesc_t
    }

    // CVMixNameInput
    namespace CVMixNameInput {
        constexpr std::ptrdiff_t m_defaultValue = 0x10; // CUtlString
    }

    // CVMixNameInputMeter
    namespace CVMixNameInputMeter {
        constexpr std::ptrdiff_t m_nValueIndex = 0x10; // int32
    }

    // CVMixOscProcessorDesc
    namespace CVMixOscProcessorDesc {
        constexpr std::ptrdiff_t m_desc = 0x20; // VMixOscDesc_t
    }

    // CVMixPannerProcessorDesc
    namespace CVMixPannerProcessorDesc {
        constexpr std::ptrdiff_t m_desc = 0x20; // VMixPannerDesc_t
    }

    // CVMixPitchShiftProcessorDesc
    namespace CVMixPitchShiftProcessorDesc {
        constexpr std::ptrdiff_t m_desc = 0x20; // VMixPitchShiftDesc_t
    }

    // CVMixPlateReverbProcessorDesc
    namespace CVMixPlateReverbProcessorDesc {
        constexpr std::ptrdiff_t m_desc = 0x20; // VMixPlateverbDesc_t
    }

    // CVMixPresetDSPProcessorDesc
    namespace CVMixPresetDSPProcessorDesc {
        constexpr std::ptrdiff_t m_desc = 0x20; // VMixPresetDSPDesc_t
    }

    // CVMixShaperProcessorDesc
    namespace CVMixShaperProcessorDesc {
        constexpr std::ptrdiff_t m_desc = 0x20; // VMixShaperDesc_t
    }

    // CVMixSteamAudioDirectProcessorDesc
    namespace CVMixSteamAudioDirectProcessorDesc {
    }

    // CVMixSteamAudioHRTFProcessorDesc
    namespace CVMixSteamAudioHRTFProcessorDesc {
    }

    // CVMixSteamAudioHybridReverbProcessorDesc
    namespace CVMixSteamAudioHybridReverbProcessorDesc {
    }

    // CVMixSteamAudioPathingProcessorDesc
    namespace CVMixSteamAudioPathingProcessorDesc {
    }

    // CVMixStereoDelayProcessorDesc
    namespace CVMixStereoDelayProcessorDesc {
    }

    // CVMixSubgraphSwitchProcessorDesc
    namespace CVMixSubgraphSwitchProcessorDesc {
        constexpr std::ptrdiff_t m_desc = 0x20; // VMixSubgraphSwitchDesc_t
    }

    // CVMixUtilityProcessorDesc
    namespace CVMixUtilityProcessorDesc {
        constexpr std::ptrdiff_t m_desc = 0x20; // VMixUtilityDesc_t
    }

    // CVMixVocoderProcessorDesc
    namespace CVMixVocoderProcessorDesc {
        constexpr std::ptrdiff_t m_desc = 0x20; // VMixVocoderDesc_t
    }

    // CVMixVsndInput
    namespace CVMixVsndInput {
        constexpr std::ptrdiff_t m_defaultValue = 0x10; // CUtlString
        constexpr std::ptrdiff_t m_nProcessor = 0x18; // int32
    }

    // CVSound
    namespace CVSound {
        constexpr std::ptrdiff_t m_Sentences = 0x0; // CUtlLeanVector<CAudioSentence>
        constexpr std::ptrdiff_t m_nRate = 0x10; // int32
        constexpr std::ptrdiff_t m_nFormat = 0x14; // CVSoundFormat_t
        constexpr std::ptrdiff_t m_nChannels = 0x18; // uint32
        constexpr std::ptrdiff_t m_nLoopStart = 0x1C; // int32
        constexpr std::ptrdiff_t m_nSampleCount = 0x20; // uint32
        constexpr std::ptrdiff_t m_flDuration = 0x24; // float32
        constexpr std::ptrdiff_t m_nStreamingSize = 0x28; // uint32
        constexpr std::ptrdiff_t m_nLoopEnd = 0x2C; // int32
    }

    // CVoiceContainerAmpedDecayingSineWave
    namespace CVoiceContainerAmpedDecayingSineWave {
        constexpr std::ptrdiff_t m_flGainAmount = 0x78; // float32
    }

    // CVoiceContainerAnalysisBase
    namespace CVoiceContainerAnalysisBase {
        constexpr std::ptrdiff_t m_curve = 0x8; // CPiecewiseCurve
    }

    // CVoiceContainerAsyncGenerator
    namespace CVoiceContainerAsyncGenerator {
    }

    // CVoiceContainerBase
    namespace CVoiceContainerBase {
        constexpr std::ptrdiff_t m_vSound = 0x28; // CVSound
        constexpr std::ptrdiff_t m_pEnvelopeAnalyzer = 0x68; // CVoiceContainerAnalysisBase*
    }

    // CVoiceContainerBlender
    namespace CVoiceContainerBlender {
        constexpr std::ptrdiff_t m_firstSound = 0x70; // CSoundContainerReference
        constexpr std::ptrdiff_t m_secondSound = 0x90; // CSoundContainerReference
        constexpr std::ptrdiff_t m_flBlendFactor = 0xB0; // float32
    }

    // CVoiceContainerDecayingSineWave
    namespace CVoiceContainerDecayingSineWave {
        constexpr std::ptrdiff_t m_flFrequency = 0x70; // float32
        constexpr std::ptrdiff_t m_flDecayTime = 0x74; // float32
    }

    // CVoiceContainerDefault
    namespace CVoiceContainerDefault {
    }

    // CVoiceContainerEnum
    namespace CVoiceContainerEnum {
        constexpr std::ptrdiff_t m_soundsToPlay = 0x70; // CSoundContainerReferenceArray
        constexpr std::ptrdiff_t m_iSelection = 0xA8; // int32
        constexpr std::ptrdiff_t m_flCrossfadeTime = 0xAC; // float32
    }

    // CVoiceContainerEnvelopeAnalyzer
    namespace CVoiceContainerEnvelopeAnalyzer {
        constexpr std::ptrdiff_t m_mode = 0x48; // EMode_t
        constexpr std::ptrdiff_t m_fAnalysisWindowMs = 0x4C; // float32
        constexpr std::ptrdiff_t m_flThreshold = 0x50; // float32
    }

    // CVoiceContainerGenerator
    namespace CVoiceContainerGenerator {
    }

    // CVoiceContainerGranulator
    namespace CVoiceContainerGranulator {
        constexpr std::ptrdiff_t m_flGrainLength = 0x80; // float32
        constexpr std::ptrdiff_t m_flGrainCrossfadeAmount = 0x84; // float32
        constexpr std::ptrdiff_t m_flStartJitter = 0x88; // float32
        constexpr std::ptrdiff_t m_flPlaybackJitter = 0x8C; // float32
        constexpr std::ptrdiff_t m_bShouldWraparound = 0x90; // bool
        constexpr std::ptrdiff_t m_sourceAudio = 0x98; // CStrongHandle<InfoForResourceTypeCVoiceContainerBase>
    }

    // CVoiceContainerLoopTrigger
    namespace CVoiceContainerLoopTrigger {
        constexpr std::ptrdiff_t m_flRetriggerTimeMin = 0x70; // float32
        constexpr std::ptrdiff_t m_flRetriggerTimeMax = 0x74; // float32
        constexpr std::ptrdiff_t m_flFadeTime = 0x78; // float32
        constexpr std::ptrdiff_t m_bCrossFade = 0x7C; // bool
        constexpr std::ptrdiff_t m_sound = 0x80; // CSoundContainerReference
    }

    // CVoiceContainerLoopTriggerWithRandomPanner
    namespace CVoiceContainerLoopTriggerWithRandomPanner {
        constexpr std::ptrdiff_t m_randomPannerControls = 0xA0; // CRandomPannerControls
    }

    // CVoiceContainerLoopXFade
    namespace CVoiceContainerLoopXFade {
        constexpr std::ptrdiff_t m_sound = 0x70; // CSoundContainerReference
        constexpr std::ptrdiff_t m_flLoopEnd = 0x90; // float32
        constexpr std::ptrdiff_t m_flLoopStart = 0x94; // float32
        constexpr std::ptrdiff_t m_flFadeOut = 0x98; // float32
        constexpr std::ptrdiff_t m_flFadeIn = 0x9C; // float32
        constexpr std::ptrdiff_t m_bPlayHead = 0xA0; // bool
        constexpr std::ptrdiff_t m_bPlayTail = 0xA1; // bool
        constexpr std::ptrdiff_t m_bEqualPow = 0xA2; // bool
    }

    // CVoiceContainerMultiBlender
    namespace CVoiceContainerMultiBlender {
        constexpr std::ptrdiff_t m_soundsToPlay = 0x70; // CSoundContainerReferenceArray
        constexpr std::ptrdiff_t m_flBlendFactor = 0xA8; // float32
        constexpr std::ptrdiff_t m_flCrossover = 0xAC; // float32
    }

    // CVoiceContainerNull
    namespace CVoiceContainerNull {
    }

    // CVoiceContainerParameterBlender
    namespace CVoiceContainerParameterBlender {
        constexpr std::ptrdiff_t m_firstSound = 0x70; // CSoundContainerReference
        constexpr std::ptrdiff_t m_secondSound = 0x90; // CSoundContainerReference
        constexpr std::ptrdiff_t m_bEnableOcclusionBlend = 0xB0; // bool
        constexpr std::ptrdiff_t m_curve1 = 0xB8; // CPiecewiseCurve
        constexpr std::ptrdiff_t m_curve2 = 0xF8; // CPiecewiseCurve
        constexpr std::ptrdiff_t m_bEnableDistanceBlend = 0x138; // bool
        constexpr std::ptrdiff_t m_curve3 = 0x140; // CPiecewiseCurve
        constexpr std::ptrdiff_t m_curve4 = 0x180; // CPiecewiseCurve
    }

    // CVoiceContainerRandomSampler
    namespace CVoiceContainerRandomSampler {
        constexpr std::ptrdiff_t m_flAmplitude = 0x80; // float32
        constexpr std::ptrdiff_t m_flAmplitudeJitter = 0x84; // float32
        constexpr std::ptrdiff_t m_flTimeJitter = 0x88; // float32
        constexpr std::ptrdiff_t m_flMaxLength = 0x8C; // float32
        constexpr std::ptrdiff_t m_nNumDelayVariations = 0x90; // int32
        constexpr std::ptrdiff_t m_grainResources = 0x98; // CUtlVector<CStrongHandle<InfoForResourceTypeCVoiceContainerBase>>
    }

    // CVoiceContainerRealtimeFMSineWave
    namespace CVoiceContainerRealtimeFMSineWave {
        constexpr std::ptrdiff_t m_flCarrierFrequency = 0x70; // float32
        constexpr std::ptrdiff_t m_flModulatorFrequency = 0x74; // float32
        constexpr std::ptrdiff_t m_flModulatorAmount = 0x78; // float32
    }

    // CVoiceContainerSelector
    namespace CVoiceContainerSelector {
        constexpr std::ptrdiff_t m_mode = 0x70; // PlayBackMode_t
        constexpr std::ptrdiff_t m_soundsToPlay = 0x78; // CSoundContainerReferenceArray
        constexpr std::ptrdiff_t m_fProbabilityWeights = 0xB0; // CUtlVector<float32>
    }

    // CVoiceContainerSet
    namespace CVoiceContainerSet {
        constexpr std::ptrdiff_t m_soundsToPlay = 0x70; // CUtlVector<CVoiceContainerSetElement>
    }

    // CVoiceContainerSetElement
    namespace CVoiceContainerSetElement {
        constexpr std::ptrdiff_t m_sound = 0x0; // CSoundContainerReference
        constexpr std::ptrdiff_t m_flVolumeDB = 0x20; // float32
    }

    // CVoiceContainerShapedNoise
    namespace CVoiceContainerShapedNoise {
        constexpr std::ptrdiff_t m_bUseCurveForFrequency = 0x70; // bool
        constexpr std::ptrdiff_t m_flFrequency = 0x74; // float32
        constexpr std::ptrdiff_t m_frequencySweep = 0x78; // CPiecewiseCurve
        constexpr std::ptrdiff_t m_bUseCurveForResonance = 0xB8; // bool
        constexpr std::ptrdiff_t m_flResonance = 0xBC; // float32
        constexpr std::ptrdiff_t m_resonanceSweep = 0xC0; // CPiecewiseCurve
        constexpr std::ptrdiff_t m_bUseCurveForAmplitude = 0x100; // bool
        constexpr std::ptrdiff_t m_flGainInDecibels = 0x104; // float32
        constexpr std::ptrdiff_t m_gainSweep = 0x108; // CPiecewiseCurve
    }

    // CVoiceContainerStaticAdditiveSynth
    namespace CVoiceContainerStaticAdditiveSynth {
        constexpr std::ptrdiff_t m_tones = 0x80; // CUtlVector<CVoiceContainerStaticAdditiveSynth::CTone>
    }

    // CVoiceContainerStaticAdditiveSynth::CGainScalePerInstance
    namespace CVoiceContainerStaticAdditiveSynth__CGainScalePerInstance {
        constexpr std::ptrdiff_t m_flMinVolume = 0x0; // float32
        constexpr std::ptrdiff_t m_nInstancesAtMinVolume = 0x4; // int32
        constexpr std::ptrdiff_t m_flMaxVolume = 0x8; // float32
        constexpr std::ptrdiff_t m_nInstancesAtMaxVolume = 0xC; // int32
    }

    // CVoiceContainerStaticAdditiveSynth::CHarmonic
    namespace CVoiceContainerStaticAdditiveSynth__CHarmonic {
        constexpr std::ptrdiff_t m_nWaveform = 0x0; // EWaveform
        constexpr std::ptrdiff_t m_nFundamental = 0x1; // EMidiNote
        constexpr std::ptrdiff_t m_nOctave = 0x4; // int32
        constexpr std::ptrdiff_t m_flCents = 0x8; // float32
        constexpr std::ptrdiff_t m_flPhase = 0xC; // float32
        constexpr std::ptrdiff_t m_curve = 0x10; // CPiecewiseCurve
        constexpr std::ptrdiff_t m_volumeScaling = 0x50; // CVoiceContainerStaticAdditiveSynth::CGainScalePerInstance
    }

    // CVoiceContainerStaticAdditiveSynth::CTone
    namespace CVoiceContainerStaticAdditiveSynth__CTone {
        constexpr std::ptrdiff_t m_harmonics = 0x0; // CUtlVector<CVoiceContainerStaticAdditiveSynth::CHarmonic>
        constexpr std::ptrdiff_t m_curve = 0x18; // CPiecewiseCurve
        constexpr std::ptrdiff_t m_bSyncInstances = 0x58; // bool
    }

    // CVoiceContainerSwitch
    namespace CVoiceContainerSwitch {
        constexpr std::ptrdiff_t m_soundsToPlay = 0x70; // CUtlVector<CSoundContainerReference>
    }

    // CVoiceContainerTapePlayer
    namespace CVoiceContainerTapePlayer {
        constexpr std::ptrdiff_t m_bShouldWraparound = 0x80; // bool
        constexpr std::ptrdiff_t m_sourceAudio = 0x88; // CStrongHandle<InfoForResourceTypeCVoiceContainerBase>
        constexpr std::ptrdiff_t m_flTapeSpeedAttackTime = 0x90; // float32
        constexpr std::ptrdiff_t m_flTapeSpeedReleaseTime = 0x94; // float32
    }

    // CVoiceContainerVMixSnd
    namespace CVoiceContainerVMixSnd {
    }

    // CVoiceContainerVsndRadioButton
    namespace CVoiceContainerVsndRadioButton {
        constexpr std::ptrdiff_t m_namespace = 0x70; // CUtlString
        constexpr std::ptrdiff_t m_slot1 = 0x78; // CVsndRadioButtonSlot
        constexpr std::ptrdiff_t m_slot2 = 0x100; // CVsndRadioButtonSlot
        constexpr std::ptrdiff_t m_slot3 = 0x188; // CVsndRadioButtonSlot
        constexpr std::ptrdiff_t m_slot4 = 0x210; // CVsndRadioButtonSlot
        constexpr std::ptrdiff_t m_slot5 = 0x298; // CVsndRadioButtonSlot
        constexpr std::ptrdiff_t m_slot6 = 0x320; // CVsndRadioButtonSlot
        constexpr std::ptrdiff_t m_slot7 = 0x3A8; // CVsndRadioButtonSlot
        constexpr std::ptrdiff_t m_slot8 = 0x430; // CVsndRadioButtonSlot
        constexpr std::ptrdiff_t m_slot9 = 0x4B8; // CVsndRadioButtonSlot
        constexpr std::ptrdiff_t m_slot10 = 0x540; // CVsndRadioButtonSlot
        constexpr std::ptrdiff_t m_slot11 = 0x5C8; // CVsndRadioButtonSlot
        constexpr std::ptrdiff_t m_slot12 = 0x650; // CVsndRadioButtonSlot
        constexpr std::ptrdiff_t m_slot13 = 0x6D8; // CVsndRadioButtonSlot
        constexpr std::ptrdiff_t m_slot14 = 0x760; // CVsndRadioButtonSlot
        constexpr std::ptrdiff_t m_slot15 = 0x7E8; // CVsndRadioButtonSlot
        constexpr std::ptrdiff_t m_slot16 = 0x870; // CVsndRadioButtonSlot
    }

    // CVoiceContainerVsndTrigger
    namespace CVoiceContainerVsndTrigger {
        constexpr std::ptrdiff_t m_namespace = 0x70; // CUtlString
        constexpr std::ptrdiff_t m_slot1 = 0x78; // CVsndTriggerSlot
        constexpr std::ptrdiff_t m_slot2 = 0x100; // CVsndTriggerSlot
        constexpr std::ptrdiff_t m_slot3 = 0x188; // CVsndTriggerSlot
        constexpr std::ptrdiff_t m_slot4 = 0x210; // CVsndTriggerSlot
        constexpr std::ptrdiff_t m_slot5 = 0x298; // CVsndTriggerSlot
        constexpr std::ptrdiff_t m_slot6 = 0x320; // CVsndTriggerSlot
        constexpr std::ptrdiff_t m_slot7 = 0x3A8; // CVsndTriggerSlot
        constexpr std::ptrdiff_t m_slot8 = 0x430; // CVsndTriggerSlot
        constexpr std::ptrdiff_t m_slot9 = 0x4B8; // CVsndTriggerSlot
        constexpr std::ptrdiff_t m_slot10 = 0x540; // CVsndTriggerSlot
        constexpr std::ptrdiff_t m_slot11 = 0x5C8; // CVsndTriggerSlot
        constexpr std::ptrdiff_t m_slot12 = 0x650; // CVsndTriggerSlot
        constexpr std::ptrdiff_t m_slot13 = 0x6D8; // CVsndTriggerSlot
        constexpr std::ptrdiff_t m_slot14 = 0x760; // CVsndTriggerSlot
        constexpr std::ptrdiff_t m_slot15 = 0x7E8; // CVsndTriggerSlot
        constexpr std::ptrdiff_t m_slot16 = 0x870; // CVsndTriggerSlot
    }

    // CVsndRadioButtonSlot
    namespace CVsndRadioButtonSlot {
        constexpr std::ptrdiff_t m_bEnableVsnd = 0x0; // bool
        constexpr std::ptrdiff_t m_vsnd = 0x8; // CSoundContainerReference
        constexpr std::ptrdiff_t m_bEnableEndcap = 0x28; // bool
        constexpr std::ptrdiff_t m_endcapVsnd = 0x30; // CSoundContainerReference
        constexpr std::ptrdiff_t m_bEnableLoopcap = 0x50; // bool
        constexpr std::ptrdiff_t m_loopcapVsnd = 0x58; // CSoundContainerReference
        constexpr std::ptrdiff_t m_group = 0x78; // int32
        constexpr std::ptrdiff_t m_volume = 0x7C; // float32
        constexpr std::ptrdiff_t m_fadeOut = 0x80; // float32
        constexpr std::ptrdiff_t m_mode = 0x84; // EVsndPlaybackMode
    }

    // CVsndTriggerSlot
    namespace CVsndTriggerSlot {
        constexpr std::ptrdiff_t m_bEnableVsnd = 0x0; // bool
        constexpr std::ptrdiff_t m_vsnd = 0x8; // CSoundContainerReference
        constexpr std::ptrdiff_t m_bEnableEndcap = 0x28; // bool
        constexpr std::ptrdiff_t m_endcapVsnd = 0x30; // CSoundContainerReference
        constexpr std::ptrdiff_t m_bEnableLoopcap = 0x50; // bool
        constexpr std::ptrdiff_t m_loopcapVsnd = 0x58; // CSoundContainerReference
        constexpr std::ptrdiff_t m_volume = 0x78; // float32
        constexpr std::ptrdiff_t m_fadeOut = 0x7C; // float32
        constexpr std::ptrdiff_t m_mode = 0x80; // EVsndTriggerMode
    }

    // ISndSeqInstruments
    namespace ISndSeqInstruments {
    }

    // KeyGroup_t
    namespace KeyGroup_t {
        constexpr std::ptrdiff_t nCenterNote = 0x0; // uint8
        constexpr std::ptrdiff_t nMinNote = 0x1; // uint8
        constexpr std::ptrdiff_t nMaxNote = 0x2; // uint8
        constexpr std::ptrdiff_t nNumVelocityZones = 0x3; // uint8
        constexpr std::ptrdiff_t pVelocityZones = 0x8; // VelocityZone_t*
    }

    // SamplerVoice_t
    namespace SamplerVoice_t {
        constexpr std::ptrdiff_t nNoteNum = 0x0; // uint8
    }

    // SelectedEditItemInfo_t
    namespace SelectedEditItemInfo_t {
        constexpr std::ptrdiff_t m_EditItems = 0x0; // CUtlVector<SosEditItemInfo_t>
    }

    // SndBeatEventKeyedFloats_t
    namespace SndBeatEventKeyedFloats_t {
        constexpr std::ptrdiff_t m_flFloat = 0x10; // float32
    }

    // SndBeatEventKeyedMidiNotes_t
    namespace SndBeatEventKeyedMidiNotes_t {
        constexpr std::ptrdiff_t m_nStatus = 0x10; // uint8
        constexpr std::ptrdiff_t m_nNote = 0x11; // uint8
        constexpr std::ptrdiff_t m_nVelocity = 0x12; // uint8
    }

    // SndBeatEventKeyedSndEvts_t
    namespace SndBeatEventKeyedSndEvts_t {
        constexpr std::ptrdiff_t m_strSoundEventName = 0x10; // CUtlString
    }

    // SndBeatEventKeys_t
    namespace SndBeatEventKeys_t {
        constexpr std::ptrdiff_t m_flKey = 0x8; // float32
    }

    // SndBeatTimeSignature_t
    namespace SndBeatTimeSignature_t {
        constexpr std::ptrdiff_t nNumerator = 0x0; // uint8
        constexpr std::ptrdiff_t nDenominator = 0x1; // uint8
    }

    // SosEditItemInfo_t
    namespace SosEditItemInfo_t {
        constexpr std::ptrdiff_t itemType = 0x0; // SosEditItemType_t
        constexpr std::ptrdiff_t itemName = 0x8; // CUtlString
        constexpr std::ptrdiff_t itemTypeName = 0x10; // CUtlString
        constexpr std::ptrdiff_t itemKVString = 0x20; // CUtlString
        constexpr std::ptrdiff_t itemPos = 0x28; // Vector2D
    }

    // VMixAutoFilterDesc_t
    namespace VMixAutoFilterDesc_t {
        constexpr std::ptrdiff_t m_flEnvelopeAmount = 0x0; // float32
        constexpr std::ptrdiff_t m_flAttackTimeMS = 0x4; // float32
        constexpr std::ptrdiff_t m_flReleaseTimeMS = 0x8; // float32
        constexpr std::ptrdiff_t m_filter = 0xC; // VMixFilterDesc_t
        constexpr std::ptrdiff_t m_flLFOAmount = 0x1C; // float32
        constexpr std::ptrdiff_t m_flLFORate = 0x20; // float32
        constexpr std::ptrdiff_t m_flPhase = 0x24; // float32
        constexpr std::ptrdiff_t m_nLFOShape = 0x28; // VMixLFOShape_t
    }

    // VMixBoxverbDesc_t
    namespace VMixBoxverbDesc_t {
        constexpr std::ptrdiff_t m_flSizeMax = 0x0; // float32
        constexpr std::ptrdiff_t m_flSizeMin = 0x4; // float32
        constexpr std::ptrdiff_t m_flComplexity = 0x8; // float32
        constexpr std::ptrdiff_t m_flDiffusion = 0xC; // float32
        constexpr std::ptrdiff_t m_flModDepth = 0x10; // float32
        constexpr std::ptrdiff_t m_flModRate = 0x14; // float32
        constexpr std::ptrdiff_t m_bParallel = 0x18; // bool
        constexpr std::ptrdiff_t m_filterType = 0x1C; // VMixFilterDesc_t
        constexpr std::ptrdiff_t m_flWidth = 0x2C; // float32
        constexpr std::ptrdiff_t m_flHeight = 0x30; // float32
        constexpr std::ptrdiff_t m_flDepth = 0x34; // float32
        constexpr std::ptrdiff_t m_flFeedbackScale = 0x38; // float32
        constexpr std::ptrdiff_t m_flFeedbackWidth = 0x3C; // float32
        constexpr std::ptrdiff_t m_flFeedbackHeight = 0x40; // float32
        constexpr std::ptrdiff_t m_flFeedbackDepth = 0x44; // float32
        constexpr std::ptrdiff_t m_flOutputGain = 0x48; // float32
        constexpr std::ptrdiff_t m_flTaps = 0x4C; // float32
    }

    // VMixConvolutionDesc_t
    namespace VMixConvolutionDesc_t {
        constexpr std::ptrdiff_t m_fldbGain = 0x0; // float32
        constexpr std::ptrdiff_t m_flPreDelayMS = 0x4; // float32
        constexpr std::ptrdiff_t m_flWetMix = 0x8; // float32
        constexpr std::ptrdiff_t m_fldbLow = 0xC; // float32
        constexpr std::ptrdiff_t m_fldbMid = 0x10; // float32
        constexpr std::ptrdiff_t m_fldbHigh = 0x14; // float32
        constexpr std::ptrdiff_t m_flLowCutoffFreq = 0x18; // float32
        constexpr std::ptrdiff_t m_flHighCutoffFreq = 0x1C; // float32
    }

    // VMixDelayDesc_t
    namespace VMixDelayDesc_t {
        constexpr std::ptrdiff_t m_feedbackFilter = 0x0; // VMixFilterDesc_t
        constexpr std::ptrdiff_t m_bEnableFilter = 0x10; // bool
        constexpr std::ptrdiff_t m_flDelay = 0x14; // float32
        constexpr std::ptrdiff_t m_flDirectGain = 0x18; // float32
        constexpr std::ptrdiff_t m_flDelayGain = 0x1C; // float32
        constexpr std::ptrdiff_t m_flFeedbackGain = 0x20; // float32
        constexpr std::ptrdiff_t m_flWidth = 0x24; // float32
    }

    // VMixDiffusorDesc_t
    namespace VMixDiffusorDesc_t {
        constexpr std::ptrdiff_t m_flSize = 0x0; // float32
        constexpr std::ptrdiff_t m_flComplexity = 0x4; // float32
        constexpr std::ptrdiff_t m_flFeedback = 0x8; // float32
        constexpr std::ptrdiff_t m_flOutputGain = 0xC; // float32
    }

    // VMixDualCompressorDesc_t
    namespace VMixDualCompressorDesc_t {
        constexpr std::ptrdiff_t m_flRMSTimeMS = 0x0; // float32
        constexpr std::ptrdiff_t m_fldbKneeWidth = 0x4; // float32
        constexpr std::ptrdiff_t m_flWetMix = 0x8; // float32
        constexpr std::ptrdiff_t m_bPeakMode = 0xC; // bool
        constexpr std::ptrdiff_t m_bandDesc = 0x10; // VMixDynamicsBand_t
    }

    // VMixDynamics3BandDesc_t
    namespace VMixDynamics3BandDesc_t {
        constexpr std::ptrdiff_t m_fldbGainOutput = 0x0; // float32
        constexpr std::ptrdiff_t m_flRMSTimeMS = 0x4; // float32
        constexpr std::ptrdiff_t m_fldbKneeWidth = 0x8; // float32
        constexpr std::ptrdiff_t m_flDepth = 0xC; // float32
        constexpr std::ptrdiff_t m_flWetMix = 0x10; // float32
        constexpr std::ptrdiff_t m_flTimeScale = 0x14; // float32
        constexpr std::ptrdiff_t m_flLowCutoffFreq = 0x18; // float32
        constexpr std::ptrdiff_t m_flHighCutoffFreq = 0x1C; // float32
        constexpr std::ptrdiff_t m_bPeakMode = 0x20; // bool
        constexpr std::ptrdiff_t m_bandDesc = 0x24; // VMixDynamicsBand_t[3]
    }

    // VMixDynamicsBand_t
    namespace VMixDynamicsBand_t {
        constexpr std::ptrdiff_t m_fldbGainInput = 0x0; // float32
        constexpr std::ptrdiff_t m_fldbGainOutput = 0x4; // float32
        constexpr std::ptrdiff_t m_fldbThresholdBelow = 0x8; // float32
        constexpr std::ptrdiff_t m_fldbThresholdAbove = 0xC; // float32
        constexpr std::ptrdiff_t m_flRatioBelow = 0x10; // float32
        constexpr std::ptrdiff_t m_flRatioAbove = 0x14; // float32
        constexpr std::ptrdiff_t m_flAttackTimeMS = 0x18; // float32
        constexpr std::ptrdiff_t m_flReleaseTimeMS = 0x1C; // float32
        constexpr std::ptrdiff_t m_bEnable = 0x20; // bool
        constexpr std::ptrdiff_t m_bSolo = 0x21; // bool
    }

    // VMixDynamicsCompressorDesc_t
    namespace VMixDynamicsCompressorDesc_t {
        constexpr std::ptrdiff_t m_fldbOutputGain = 0x0; // float32
        constexpr std::ptrdiff_t m_fldbCompressionThreshold = 0x4; // float32
        constexpr std::ptrdiff_t m_fldbKneeWidth = 0x8; // float32
        constexpr std::ptrdiff_t m_flCompressionRatio = 0xC; // float32
        constexpr std::ptrdiff_t m_flAttackTimeMS = 0x10; // float32
        constexpr std::ptrdiff_t m_flReleaseTimeMS = 0x14; // float32
        constexpr std::ptrdiff_t m_flRMSTimeMS = 0x18; // float32
        constexpr std::ptrdiff_t m_flWetMix = 0x1C; // float32
        constexpr std::ptrdiff_t m_bPeakMode = 0x20; // bool
    }

    // VMixDynamicsDesc_t
    namespace VMixDynamicsDesc_t {
        constexpr std::ptrdiff_t m_fldbGain = 0x0; // float32
        constexpr std::ptrdiff_t m_fldbNoiseGateThreshold = 0x4; // float32
        constexpr std::ptrdiff_t m_fldbCompressionThreshold = 0x8; // float32
        constexpr std::ptrdiff_t m_fldbLimiterThreshold = 0xC; // float32
        constexpr std::ptrdiff_t m_fldbKneeWidth = 0x10; // float32
        constexpr std::ptrdiff_t m_flRatio = 0x14; // float32
        constexpr std::ptrdiff_t m_flLimiterRatio = 0x18; // float32
        constexpr std::ptrdiff_t m_flAttackTimeMS = 0x1C; // float32
        constexpr std::ptrdiff_t m_flReleaseTimeMS = 0x20; // float32
        constexpr std::ptrdiff_t m_flRMSTimeMS = 0x24; // float32
        constexpr std::ptrdiff_t m_flWetMix = 0x28; // float32
        constexpr std::ptrdiff_t m_bPeakMode = 0x2C; // bool
    }

    // VMixEQ8Desc_t
    namespace VMixEQ8Desc_t {
        constexpr std::ptrdiff_t m_stages = 0x0; // VMixFilterDesc_t[8]
    }

    // VMixEffectChainDesc_t
    namespace VMixEffectChainDesc_t {
        constexpr std::ptrdiff_t m_effectName = 0x0; // CUtlString
    }

    // VMixEnvelopeDesc_t
    namespace VMixEnvelopeDesc_t {
        constexpr std::ptrdiff_t m_flAttackTimeMS = 0x0; // float32
        constexpr std::ptrdiff_t m_flHoldTimeMS = 0x4; // float32
        constexpr std::ptrdiff_t m_flReleaseTimeMS = 0x8; // float32
    }

    // VMixFilterDesc_t
    namespace VMixFilterDesc_t {
        constexpr std::ptrdiff_t m_nFilterType = 0x0; // VMixFilterType_t
        constexpr std::ptrdiff_t m_nFilterSlope = 0x2; // VMixFilterSlope_t
        constexpr std::ptrdiff_t m_bEnabled = 0x3; // bool
        constexpr std::ptrdiff_t m_fldbGain = 0x4; // float32
        constexpr std::ptrdiff_t m_flCutoffFreq = 0x8; // float32
        constexpr std::ptrdiff_t m_flQ = 0xC; // float32
    }

    // VMixFlangerDesc_t
    namespace VMixFlangerDesc_t {
        constexpr std::ptrdiff_t m_bPhaseInvert = 0x0; // bool
        constexpr std::ptrdiff_t m_flGlideTime = 0x4; // float32
        constexpr std::ptrdiff_t m_flDelay = 0x8; // float32
        constexpr std::ptrdiff_t m_flOutputGain = 0xC; // float32
        constexpr std::ptrdiff_t m_flFeedbackGain = 0x10; // float32
        constexpr std::ptrdiff_t m_flFeedforwardGain = 0x14; // float32
        constexpr std::ptrdiff_t m_flModRate = 0x18; // float32
        constexpr std::ptrdiff_t m_flModDepth = 0x1C; // float32
        constexpr std::ptrdiff_t m_bApplyAntialiasing = 0x20; // bool
    }

    // VMixFreeverbDesc_t
    namespace VMixFreeverbDesc_t {
        constexpr std::ptrdiff_t m_flRoomSize = 0x0; // float32
        constexpr std::ptrdiff_t m_flDamp = 0x4; // float32
        constexpr std::ptrdiff_t m_flWidth = 0x8; // float32
        constexpr std::ptrdiff_t m_flLateReflections = 0xC; // float32
    }

    // VMixModDelayDesc_t
    namespace VMixModDelayDesc_t {
        constexpr std::ptrdiff_t m_feedbackFilter = 0x0; // VMixFilterDesc_t
        constexpr std::ptrdiff_t m_bPhaseInvert = 0x10; // bool
        constexpr std::ptrdiff_t m_flGlideTime = 0x14; // float32
        constexpr std::ptrdiff_t m_flDelay = 0x18; // float32
        constexpr std::ptrdiff_t m_flOutputGain = 0x1C; // float32
        constexpr std::ptrdiff_t m_flFeedbackGain = 0x20; // float32
        constexpr std::ptrdiff_t m_flModRate = 0x24; // float32
        constexpr std::ptrdiff_t m_flModDepth = 0x28; // float32
        constexpr std::ptrdiff_t m_bApplyAntialiasing = 0x2C; // bool
    }

    // VMixOscDesc_t
    namespace VMixOscDesc_t {
        constexpr std::ptrdiff_t oscType = 0x0; // VMixLFOShape_t
        constexpr std::ptrdiff_t m_freq = 0x4; // float32
        constexpr std::ptrdiff_t m_flPhase = 0x8; // float32
    }

    // VMixPannerDesc_t
    namespace VMixPannerDesc_t {
        constexpr std::ptrdiff_t m_type = 0x0; // VMixPannerType_t
        constexpr std::ptrdiff_t m_flStrength = 0x4; // float32
    }

    // VMixPitchShiftDesc_t
    namespace VMixPitchShiftDesc_t {
        constexpr std::ptrdiff_t m_nGrainSampleCount = 0x0; // int32
        constexpr std::ptrdiff_t m_flPitchShift = 0x4; // float32
        constexpr std::ptrdiff_t m_nQuality = 0x8; // int32
        constexpr std::ptrdiff_t m_nProcType = 0xC; // int32
    }

    // VMixPlateverbDesc_t
    namespace VMixPlateverbDesc_t {
        constexpr std::ptrdiff_t m_flPrefilter = 0x0; // float32
        constexpr std::ptrdiff_t m_flInputDiffusion1 = 0x4; // float32
        constexpr std::ptrdiff_t m_flInputDiffusion2 = 0x8; // float32
        constexpr std::ptrdiff_t m_flDecay = 0xC; // float32
        constexpr std::ptrdiff_t m_flDamp = 0x10; // float32
        constexpr std::ptrdiff_t m_flFeedbackDiffusion1 = 0x14; // float32
        constexpr std::ptrdiff_t m_flFeedbackDiffusion2 = 0x18; // float32
    }

    // VMixPresetDSPDesc_t
    namespace VMixPresetDSPDesc_t {
        constexpr std::ptrdiff_t m_effectName = 0x0; // CUtlString
    }

    // VMixShaperDesc_t
    namespace VMixShaperDesc_t {
        constexpr std::ptrdiff_t m_nShape = 0x0; // int32
        constexpr std::ptrdiff_t m_fldbDrive = 0x4; // float32
        constexpr std::ptrdiff_t m_fldbOutputGain = 0x8; // float32
        constexpr std::ptrdiff_t m_flWetMix = 0xC; // float32
        constexpr std::ptrdiff_t m_nOversampleFactor = 0x10; // int32
    }

    // VMixSubgraphSwitchDesc_t
    namespace VMixSubgraphSwitchDesc_t {
        constexpr std::ptrdiff_t m_name = 0x0; // CUtlString
        constexpr std::ptrdiff_t m_effectName = 0x8; // CUtlString
        constexpr std::ptrdiff_t m_subgraphs = 0x10; // CUtlVector<CUtlString>
        constexpr std::ptrdiff_t m_interpolationMode = 0x28; // VMixSubgraphSwitchInterpolationType_t
        constexpr std::ptrdiff_t m_bOnlyTailsOnFadeOut = 0x2C; // bool
        constexpr std::ptrdiff_t m_flInterpolationTime = 0x30; // float32
    }

    // VMixUtilityDesc_t
    namespace VMixUtilityDesc_t {
        constexpr std::ptrdiff_t m_nOp = 0x0; // VMixChannelOperation_t
        constexpr std::ptrdiff_t m_flInputPan = 0x4; // float32
        constexpr std::ptrdiff_t m_flOutputBalance = 0x8; // float32
        constexpr std::ptrdiff_t m_fldbOutputGain = 0xC; // float32
        constexpr std::ptrdiff_t m_bBassMono = 0x10; // bool
        constexpr std::ptrdiff_t m_flBassFreq = 0x14; // float32
    }

    // VMixVocoderDesc_t
    namespace VMixVocoderDesc_t {
        constexpr std::ptrdiff_t m_nBandCount = 0x0; // int32
        constexpr std::ptrdiff_t m_flBandwidth = 0x4; // float32
        constexpr std::ptrdiff_t m_fldBModGain = 0x8; // float32
        constexpr std::ptrdiff_t m_flFreqRangeStart = 0xC; // float32
        constexpr std::ptrdiff_t m_flFreqRangeEnd = 0x10; // float32
        constexpr std::ptrdiff_t m_fldBUnvoicedGain = 0x14; // float32
        constexpr std::ptrdiff_t m_flAttackTimeMS = 0x18; // float32
        constexpr std::ptrdiff_t m_flReleaseTimeMS = 0x1C; // float32
        constexpr std::ptrdiff_t m_nDebugBand = 0x20; // int32
        constexpr std::ptrdiff_t m_bPeakMode = 0x24; // bool
    }

    // VelocityZone_t
    namespace VelocityZone_t {
        constexpr std::ptrdiff_t nMaxVel = 0x0; // uint8
        constexpr std::ptrdiff_t nNextSelection = 0x1; // uint8
        constexpr std::ptrdiff_t nNumSamples = 0x2; // uint8
        constexpr std::ptrdiff_t pSamples = 0x4; // uint32[4]
    }

    // ── Enums ────────────────────────────────────
    enum class CVSoundFormat_t : uint8_t {
        PCM16 = 0,
        PCM8 = 1,
        MP3 = 2,
        ADPCM = 3,
    };

    enum class EMidiNote : uint8_t {
        C = 0,
        C_Sharp = 1,
        D = 2,
        D_Sharp = 3,
        E = 4,
        F = 5,
        F_Sharp = 6,
        G = 7,
        G_Sharp = 8,
        A = 9,
        A_Sharp = 10,
        B = 11,
        Count = 12,
    };

    enum class EMode_t : int32_t {
        Peak = 0,
        RMS = 1,
    };

    enum class EVsndPlaybackMode : int32_t {
        Trigger = 0,
        Gate = 1,
    };

    enum class EVsndTriggerMode : int32_t {
        Trigger = 0,
        Gate = 1,
    };

    enum class EWaveform : uint8_t {
        Sine = 0,
        Square = 1,
        Saw = 2,
        Triangle = 3,
        Noise = 4,
    };

    enum class PlayBackMode_t : int32_t {
        Random = 0,
        RandomNoRepeats = 1,
        RandomAvoidLast = 2,
        Sequential = 3,
        RandomWeights = 4,
    };

    enum class SndBeatEventType_t : int32_t {
        eSndBeatEventTypeInvalid = 0,
        eSndBeatEventTypeBeat = 1,
        eSndBeatEventTypeBar = 2,
        eSndBeatEventTypePhrase = 3,
        eSndBeatEventTypeLength = 4,
        eSndBeatEventTypeKeys = 5,
    };

    enum class SndBeatKeyType_t : int32_t {
        eSndBeatPatternTypeNone = 0,
        eSndBeatPatternTypeKeys = 1,
        eSndBeatPatternTypeKeyedFloats = 2,
        eSndBeatPatternTypeKeyedSndEvts = 3,
        eSndBeatPatternTypeKeyedMidi = 4,
    };

    enum class SndBeatLaunchSyncType_t : int32_t {
        eSndBeatLaunchSyncTypeInvalid = 0,
        eSndBeatLaunchSyncTypeQueue = 1,
        eSndBeatLaunchSyncTypeSeek = 2,
        eSndBeatLaunchSyncTypeReset = 3,
    };

    enum class SndBeatMidiStatusType_t : int32_t {
        SndSeqMidiStatusNoteOff = 8,
        SndSeqMidiStatusNoteOn = 9,
        SndSeqMidiStatusKeyPressure = 10,
        SndSeqMidiStatusCtrlChange = 11,
        SndSeqMidiStatusProgramChange = 12,
        SndSeqMidiStatusChannelPressure = 13,
        SndSeqMidiStatusPitchBend = 14,
    };

    enum class SndBeatTrackPlaybackType_t : int32_t {
        eSndBeatTrackPlaybackTypeStep = 0,
        eSndBeatTrackPlaybackTypeFwd = 1,
    };

    enum class SndSeqInstrumentType_t : int32_t {
        eSndSeqInstNull = 0,
        eSndSeqInstSndEvt = 1,
        eSndSeqInstMidiSampler = 2,
    };

    enum class SosActionLimitSortType_t : int32_t {
        SOS_LIMIT_SORTTYPE_HIGHEST = 0,
        SOS_LIMIT_SORTTYPE_LOWEST = 1,
    };

    enum class SosActionSetParamSortType_t : int32_t {
        SOS_SETPARAM_SORTTYPE_HIGHEST = 0,
        SOS_SETPARAM_SORTTYPE_LOWEST = 1,
    };

    enum class SosActionStopType_t : int32_t {
        SOS_STOPTYPE_NONE = 0,
        SOS_STOPTYPE_TIME = 1,
        SOS_STOPTYPE_OPVAR = 2,
    };

    enum class SosEditItemType_t : int32_t {
        SOS_EDIT_ITEM_TYPE_SOUNDEVENTS = 0,
        SOS_EDIT_ITEM_TYPE_SOUNDEVENT = 1,
        SOS_EDIT_ITEM_TYPE_LIBRARYSTACKS = 2,
        SOS_EDIT_ITEM_TYPE_STACK = 3,
        SOS_EDIT_ITEM_TYPE_OPERATOR = 4,
        SOS_EDIT_ITEM_TYPE_FIELD = 5,
    };

    enum class SosGroupFieldBehavior_t : int32_t {
        kIgnore = 0,
        kBranch = 1,
        kMatch = 2,
    };

    enum class SosGroupType_t : int32_t {
        SOS_GROUPTYPE_DYNAMIC = 0,
        SOS_GROUPTYPE_STATIC = 1,
    };

    enum class VMixChannelOperation_t : int32_t {
        VMIX_CHAN_STEREO = 0,
        VMIX_CHAN_LEFT = 1,
        VMIX_CHAN_RIGHT = 2,
        VMIX_CHAN_SWAP = 3,
        VMIX_CHAN_MONO = 4,
        VMIX_CHAN_MID_SIDE = 5,
    };

    enum class VMixFilterSlope_t : uint8_t {
        FILTER_SLOPE_1POLE_6dB = 0,
        FILTER_SLOPE_1POLE_12dB = 1,
        FILTER_SLOPE_1POLE_18dB = 2,
        FILTER_SLOPE_1POLE_24dB = 3,
        FILTER_SLOPE_12dB = 4,
        FILTER_SLOPE_24dB = 5,
        FILTER_SLOPE_36dB = 6,
        FILTER_SLOPE_48dB = 7,
        FILTER_SLOPE_MAX = 7,
    };

    enum class VMixFilterType_t : uint16_t {
        FILTER_UNKNOWN = -1,
        FILTER_LOWPASS = 0,
        FILTER_HIGHPASS = 1,
        FILTER_BANDPASS = 2,
        FILTER_NOTCH = 3,
        FILTER_PEAKING_EQ = 4,
        FILTER_LOW_SHELF = 5,
        FILTER_HIGH_SHELF = 6,
        FILTER_ALLPASS = 7,
        FILTER_PASSTHROUGH = 8,
    };

    enum class VMixGraphCommandID_t : int32_t {
        CMD_INVALID = -1,
        CMD_CONTROL_INPUT_STORE = 1,
        CMD_CONTROL_INPUT_STORE_DB = 2,
        CMD_CONTROL_TRANSIENT_INPUT_STORE = 3,
        CMD_CONTROL_TRANSIENT_INPUT_RESET = 4,
        CMD_CONTROL_OUTPUT_STORE = 5,
        CMD_CONTROL_EVALUATE_CURVE = 6,
        CMD_CONTROL_COPY = 7,
        CMD_CONTROL_COND_COPY_IF_NEGATIVE = 8,
        CMD_CONTROL_REMAP_LINEAR = 9,
        CMD_CONTROL_REMAP_SINE = 10,
        CMD_CONTROL_REMAP_LOGLINEAR = 11,
        CMD_CONTROL_MAX = 12,
        CMD_CONTROL_RESET_TIMER = 13,
        CMD_CONTROL_INCREMENT_TIMER = 14,
        CMD_CONTROL_EVAL_ENVELOPE = 15,
        CMD_CONTROL_SINE_BLEND = 16,
        CMD_PROCESSOR_SET_CONTROL_VALUE = 17,
        CMD_PROCESSOR_SET_NAME_INPUT = 18,
        CMD_PROCESSOR_SET_CONTROL_ARRAYVALUE = 19,
        CMD_PROCESSOR_STORE_CONTROL_VALUE = 20,
        CMD_PROCESSOR_SET_VSND_VALUE = 21,
        CMD_SUBMIX_PROCESS = 22,
        CMD_SUBMIX_GENERATE = 23,
        CMD_SUBMIX_GENERATE_SIDECHAIN = 24,
        CMD_SUBMIX_EXTRACTCONTAINER = 25,
        CMD_SUBMIX_DEBUG = 26,
        CMD_SUBMIX_MIX2x1 = 27,
        CMD_SUBMIX_OUTPUT = 28,
        CMD_SUBMIX_OUTPUTx2 = 29,
        CMD_SUBMIX_COPY = 30,
        CMD_SUBMIX_ACCUMULATE = 31,
        CMD_SUBMIX_METER = 32,
        CMD_SUBMIX_METER_SPECTRUM = 33,
        CMD_IMPULSERESPONSE_INPUT_STORE = 34,
        CMD_PROCESSOR_SET_IMPULSERESPONSE_VALUE = 35,
        CMD_REMAP_VSND_TO_IMPULSERESPONSE = 36,
        CMD_IMPULSERESPONSE_RESET = 37,
        CMD_BLEND_VSNDS_TO_IMPULSERESPONSE = 38,
        CMD_IMPULSERESPONSE_DELAY = 39,
    };

    enum class VMixLFOShape_t : int32_t {
        LFO_SHAPE_SINE = 0,
        LFO_SHAPE_SQUARE = 1,
        LFO_SHAPE_TRI = 2,
        LFO_SHAPE_SAW = 3,
        LFO_SHAPE_NOISE = 4,
    };

    enum class VMixPannerType_t : int32_t {
        PANNER_TYPE_LINEAR = 0,
        PANNER_TYPE_EQUAL_POWER = 1,
    };

    enum class VMixSubgraphSwitchInterpolationType_t : int32_t {
        SUBGRAPH_INTERPOLATION_TEMPORAL_CROSSFADE = 0,
        SUBGRAPH_INTERPOLATION_TEMPORAL_FADE_OUT = 1,
        SUBGRAPH_INTERPOLATION_KEEP_LAST_SUBGRAPH_RUNNING = 2,
    };

    enum class soundlevel_t : int32_t {
        SNDLVL_NONE = 0,
        SNDLVL_20dB = 20,
        SNDLVL_25dB = 25,
        SNDLVL_30dB = 30,
        SNDLVL_35dB = 35,
        SNDLVL_40dB = 40,
        SNDLVL_45dB = 45,
        SNDLVL_50dB = 50,
        SNDLVL_55dB = 55,
        SNDLVL_IDLE = 60,
        SNDLVL_60dB = 60,
        SNDLVL_65dB = 65,
        SNDLVL_STATIC = 66,
        SNDLVL_70dB = 70,
        SNDLVL_NORM = 75,
        SNDLVL_75dB = 75,
        SNDLVL_80dB = 80,
        SNDLVL_TALKING = 80,
        SNDLVL_85dB = 85,
        SNDLVL_90dB = 90,
        SNDLVL_95dB = 95,
        SNDLVL_100dB = 100,
        SNDLVL_105dB = 105,
        SNDLVL_110dB = 110,
        SNDLVL_120dB = 120,
        SNDLVL_130dB = 130,
        SNDLVL_GUNFIRE = 140,
        SNDLVL_140dB = 140,
        SNDLVL_150dB = 150,
        SNDLVL_180dB = 180,
    };

} // namespace cs2_dumper::schemas::soundsystem_dll
